### ISSUE TITLE
Is it possible to test error codes with dredd?

### ISSUE THREAD

**Issue by WldmrSbrt** [apiaryio/dredd#1006]
Hi dredd team!
Is it possible to test error codes / different workflows for one path with dredd?

Example:
`Path /task/{id} can have 3 type of responses: 
200 -> OK
404 -> Task not found 
403 -> Forbidden(not your task)`

The path "task" has three different responses, depending on the id parameter. Is there a way to test all 3 paths?

Thanks!

**Comment by WldmrSbrt** [comment]
Thanks for the Documentation Points! I'm using swagger.

**Comment by honzajavorek** [comment]
And do the points solve your problem? :-)

**Comment by WldmrSbrt** [comment]
That is a really good question! :-)
Do you have an example for testing of multiple requests for one path in swagger? In the documentation there is only a "how-to-execute-skipped-tests" description. 
E.g:
Test #1: /task/123 -> Response 200 with Task Body
Test #2: /task/4321 -> Response 404 -> Item not found

Thanks!

**Comment by honzajavorek** [comment]
Would something like this work for you?

```yaml
swagger: '2.0'
info:
  title: "My API"
  version: '1.0'
produces:
  - application/json; charset=utf-8
paths:
  '/task/123':
    get:
      responses:
        200:
          description: 'Task exists'
          examples:
            application/json; charset=utf-8:
              test: 'Task #123: wash dishes'
  '/task/4321':
    get:
      responses:
        404:
          description: 'Task does not exist'
          examples:
            application/json; charset=utf-8:
              test: 'Task #4321 does not exist'
```

**Comment by WldmrSbrt** [comment]
thanks, I will try it 👍

**Comment by honzajavorek** [comment]
@WldmrSbrt Did it solve your issue?

**Comment by WldmrSbrt** [comment]
Hi, thanks! I think this issue is solved. 
As I understand I have to duplicate the paths to cover more then one scenario, but in this case I have to manipulate and "blow up" the documentation. And I am currently not able to design "collaborations" between different parameters.

I think Ineed a possibility to design example descriptions, something like:
`examples: [
	example1: {
	  Parameters: [
			parameter1: "1234", //required
			parameter2: "{name: 'test', description:'short description'}, //optional
			parameter3: "inactive" //optional
			],
		expectedResult: 200;
		
	},
	example2: {
	  Parameters: [
			parameter1: "1234654321"
			],
		expectedResult: 200;		
	},
	example3: {
	  Parameters: [
			parameter2: "{name: 'test', description:'short description'}, //optional
			parameter3: "inactive" //optional
			],
		expectedResult: 400;		
	}

]`

 but that is not an issue :-)

**Comment by honzajavorek** [comment]
This would be a limitation of the API description format. I don't think this is possible with Swagger at this moment. Look at using [`$ref`](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03), could help you to make the document [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
