### ISSUE TITLE
add an option for hooks to fail test

### ISSUE THREAD

**Issue by vadim-hbo** [apiaryio/dredd#101]
In some cases hooks cannot prepare data properly for the blueprint, or do additional validation of the request or of the  actual vs. expected result. It would be nice to have ability to mark test failed in such cases.

The `transaction.skip` mechanism is not sufficient, because in this case the transaction is not executed (good), but the overall blueprint is marked successful (bad). As result, the problem might went unnoticed for quite awhile. OTOH, not marking transaction creates extensive noise in the output -- test fails, but a lot of irrelevant information dumped (request, expected response, actual response).

**Comment by jpemberthy** [comment]
:+1:

**Comment by netmilk** [comment]
Hi,
  this was [implemented](https://github.com/apiaryio/dredd/pull/156) and [documented](https://github.com/apiaryio/dredd/blob/master/docs/hooks.md#fail-or-skip-a-transaction-inside-a-hook)

Just set `fail` property on [transaction object](https://github.com/apiaryio/dredd/blob/master/docs/transaction.md) in any hook to `true` or string with message and transaction will result to failed regardless result of its validation. 

You can use `chai` library for setting custom assertions as well.

```coffee
before 'My resource > Create', (transaction) ->
  transaction.fail = 'Failed in before hook' 
```

Adam
