### ISSUE TITLE
How to make Dredd to upload to a given collection on Apiary

### ISSUE THREAD

**Issue by erajkovic** [apiaryio/dredd#1022]
#### Describe your problem

I have been trying to upload some dredd local runs to my remote account, so that I could share the result and measure progress as I make correction to my local Swagger document, but ran into an issue uploading to the expected target instance.

Until I got external help with reviewing my setup and fixing the issue, I was going nowhere. It would be nice to get better error reporting for novice users. 

Part of the challenge was that I was not getting an explicit error message, and that the URL provided by Dredd was working, just not what I intended it to be.
 
#### What command line options do you use?

```
$ dredd
```
Yes, I was trying to use a config file...
```
$ dredd --config dredd-eric.yml
```

#### What is in your `dredd.yml`?

only the diff between the working vs. bad file

```yaml
8,10c8
< custom:
<   apiaryApiKey: c90f07bf914065fd4f0179xxxxx
<   apiaryApiName: ohcapirr
---
> custom: {apiaryApiKey:c90f07bf914065fd4f0179xxxxx, apiaryApiName:ohcapirr}
```

#### What's your `dredd --version` output?

```
dredd v5.1.6 (Darwin 17.4.0; x64)
```

#### Does `dredd --level=debug` uncover something?

Not really from using debug, but the difference in output between good and bad runs
complete: See results in Apiary at: https://app.apiary.io/public/tests/run/48f0f115-be3b-4599-a623-6ef5597018e4
complete: See results in Apiary at: https://app.apiary.io/ohcapirr/tests/run/18316469-0b08-45c0-a67f-031c59c2c531

I have to find a good setup/configuration, when I can see some output without to get all the 'noise' for those expected warnings. It's hard to find a good balance between the amount of data to output for a new user vs. the amount that can be stored in files for out of bound review.

**Comment by honzajavorek** [comment]
In case one uses `--reporter=apiary`, Dredd looks for the `apiaryApiKey` and `apiaryApiName` configuration values. If Dredd fails to find values for those, it prints following warning in the beginning of the CLI output:

```
warn:
Apiary API Key or API Project Subdomain were not provided.
Configure Dredd to be able to save test reports alongside your Apiary API project:
https://dredd.readthedocs.io/en/latest/how-to-guides/#using-apiary-reporter-and-apiary-tests
```

Then I can see _public_ link at the end of the output:

```
https://app.apiary.io/public/tests/run/...
```

If the configuration is in place (e.g. by adding `-j apiaryApiKey:abcd... -j apiaryApiName:gargamel`), the warning is gone and I can see correct link at the end of the output:

```
https://app.apiary.io/gargamel/tests/run/...
```

**Comment by honzajavorek** [comment]
@erajkovic Is this still happening to you? Were you able to resolve the issue or to discover the root cause?

**Comment by erajkovic** [comment]
Not yet, there are days when it just works and others when it fails - I have not looked at it recently, so I'll do it and get back to you - most likely close it with the HowTo to detail my user errors.

**Comment by erajkovic** [comment]
Today, I was not able to reproduce any of the errors I got earlier - I am using a more recent version of dredd in case it could have add some impact - dredd v5.1.9 (Darwin 17.5.0; x64) 
Even with a single line format for the custom tags in my yaml file, I was able to upload to the specified API - zztop in my latest test.
Closing the issue. Thanks.
