### ISSUE TITLE
How to validate Responses if the response body does not have all the attributes

### ISSUE THREAD

**Issue by thesageinpilani** [apiaryio/dredd#1032]
Hi guys,
I have a server which responds with Response Body having key value pairs depending upon the context of the request, For example, one of my test is failing at,

fail: body: At '/firstName' Missing required property: firstName
body: At '/phone' Missing required property: phone
body: At '/email' Missing required property: email
body: At '/amount' Invalid type: null (expected number)
body: At '/validThrough' Invalid type: null (expected number)
body: At '/additionalInfo' Invalid type: null (expected object)

the context that i am running, we don't require firstName or the remaining properties! can you tell me if their is a provision to skip this validation? Thanks 😀

**Comment by honzajavorek** [comment]
How do you specify the bodies in your Swagger document? As examples or as schemes?

**Comment by thesageinpilani** [comment]
I specify using schemas, where required, i am giving default values.


definitions:
  successBinDetails:
    type: object
    properties:
      bin:
        type: number
      brand:
        type: string
      issuer:
        type: string
      countryCode:
        type: string
      country:
        type: string
      categoryCode:
        type: string
      category:
        type: string
      programCode:
        type: string
      program:
        type: string
      status:
        type: string
      sisupported:
        type: string
      zeroRedirectSupported:
        type: string

**Comment by honzajavorek** [comment]
Hmm 🤔 Are you sure you don't specify [required](https://spacetelescope.github.io/understanding-json-schema/reference/object.html#required) anywhere? Dredd (or, more precisely, Gavel) follows whatever is in your schema. If you do not specify `required` anywhere, it should not require the properties to be present.

**Comment by honzajavorek** [comment]
😄 no problem. So, does it work for you now?

**Comment by thesageinpilani** [comment]
Yes, But i have another problem, it is about required, can you please take a look at it and get back to me, if you know the solution. thanks 😀

https://github.com/swagger-api/swagger-editor/issues/1795
