### ISSUE TITLE
How to support Multiple Optional query Parameters in dredd?

### ISSUE THREAD

**Issue by thesageinpilani** [apiaryio/dredd#1071]
for example, i have 3 pairs of query parameters and I need only one pair at any given point of time. 
Therefore i want to test for each pair. I haven't came across the solution for this in Swagger. is it possible to send the request for each pair and then validate the response for each pair. If i specify all query parameters and with "required: false", I would choose any one pair(that is two query parameters) and change the transaction.request.uri according to it. Then dredd would perform the request and would move to another request. But i want dredd to make the same request again with different query parameters. Is there any option to do this in hooks?. if you can support me, it would be of great help. Thank you 😀.

**Comment by honzajavorek** [comment]
Yes, you can do this using hooks: https://github.com/apiaryio/dredd/issues/995
