### ISSUE TITLE
How can I run a specific request by Dredd?

### ISSUE THREAD

**Issue by KonstantinxVx** [apiaryio/dredd#1074]
I have many HTTP requests in my `.apib` file. How can I run only one specific request instead of all?
E.g. I have:
```
## Group Login
## Login [/login]
### POST [POST /login]
+ Request (application/vnd.api+json)
...
## Login Key [/login_key]
### POST [POST /login_key]
+ Request (application/vnd.api+json)
...
```
What CLI option I have to use for that if I want to run only `POST /login` request? 

I've tried `--name Login` and `--only Login` but those seem to be not right ones.

#### What command line options do you use?

```
$ dredd --name Login
$ dredd --only Login
```

#### What's your `dredd --version` output?

```
dredd v5.1.7
```

**Comment by honzajavorek** [comment]
[`--only`](https://dredd.readthedocs.io/en/latest/usage-cli.html#only-x) should work. First, run Dredd with `--names`, which lists the "transaction names". Then use the "transaction name" as value for `--only`.

**Comment by KonstantinxVx** [comment]
@honzajavorek thanks!
