### ISSUE TITLE
Request stash in hooks: Using data from previous responses

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#108]
I’d like to present concept of stashing responses. It’s support for full entity life-cycle without use of fixtures accessing directly the database. You can transform a request in hooks with data from some previous response before its execution.

This solves situation where you create an entity, server returns unique ID and you want use this ID as a  URI parameter in next action to retrieve the entity.

```coffee
{before, after} = require 'hooks'

responseStash = {}

after "Machines > Machines collection > Create a Machine", (transaction) ->
  responseStash[transaction.name] = transaction.real

before "Machines > Machine > Retrieve a Machine", (transaction) ->
  stash = responseStash['Machines > Machines collection > Create a Machine']
  bodyObject = JSON.parse stash.body
  newId = bodyObject['_id']
  transaction.request.uri = transaction.request.uri.replace '52341870ed55224b15ff07ef', newId
  transaction.fullPath = transaction.fullPath.replace '52341870ed55224b15ff07ef', newId
```

I've created an [example application][example] in CI and a [proposal][proposal] for API in hooks.

[example]: https://github.com/apiaryio/dredd-example/tree/netmilk/response-stashes
[proposal]: https://gist.github.com/netmilk/b52a329b79ef307cbf70

**Comment by rickke** [comment]
Request stash is a great idea. But I do not think it could fix the issue in #96.

**Comment by netmilk** [comment]
@rickke Why do you think it's not a usable workaround?

**Comment by rickke** [comment]
@netmilk  For my understanding, stashing response use after event to get server response from one transaction and modify the request info in another transaction use before event. Is it right? The id mentioned in #96 is from server side and nothing to do with client request. So there is no way to fix it with stashng response. Am I wrong? Thanks

**Comment by netmilk** [comment]
@rickke You can modify both, the request and the expectation as well in the before hook. 

But you are right that in blueprint example form #96 there is no previous request, where expected id of the entity can be retrieved from the server for later  modification of the expected response. (for example in when creating entity in the collection).  So this does not solves #96. Thanks for noticing that!

**Comment by pocketmax** [comment]
Sorry for my confusion but was this ever fixed?

**Comment by netmilk** [comment]
@pocketmax Do you mean this issue or #96?

**Comment by pocketmax** [comment]
ug, sorry, yeah I mean #96
