### ISSUE TITLE
Is the official docker container still supported?

### ISSUE THREAD

**Issue by BetaGrumm** [apiaryio/dredd#1106]
Just a quick question.
I noticed the docker container hasn't been updated since 5.1.5 (4 months ago) and hasn't been updated very often in the past.
See: [https://hub.docker.com/r/apiaryio/dredd/tags/](https://hub.docker.com/r/apiaryio/dredd/tags/)
Is the official docker container active or should it be considered dead/build your own?

Thanks.

**Comment by honzajavorek** [comment]
Hi, it is, but we should set up some kind of pipeline to update the version after each release, especially given Dredd releasing itself is automated.

@apiaryio/sre would you be able to help with this? (At least with designing the solution?)

**Comment by w-vi** [comment]
It is updated on the need basis not tracking dredd versions. We can definitelly improve it and follow the dredd releases.

**Comment by abtris** [comment]
I think you can add stage after release to build and push docker image.  Travis support build docker images - https://docs.travis-ci.com/user/docker/#building-a-docker-image-from-a-dockerfile and [dockerfile is available](https://github.com/apiaryio/docker-base-images/blob/master/dredd/Dockerfile) and [build.sh](https://github.com/apiaryio/docker-base-images/blob/master/dredd/build.sh) and [simple script to get latest tag](https://github.com/apiaryio/docker-base-images/blob/master/scripts/getLatestStableNodePackage) there too.

**Comment by abtris** [comment]
@honzajavorek I can prepare repo and PR if you think that my proposal is ok.

**Comment by honzajavorek** [comment]
@abtris Sounds good to me! Dredd's `stable` and `latest` tags point to the same version for a long time already and we're not using pre-releases or anything like that, we have Semantic Release. So I wouldn't bother with that, just use `latest`.

**Comment by abtris** [comment]
@honzajavorek Here is test version https://github.com/apiaryio/dredd-docker/pull/1

**Comment by honzajavorek** [comment]
Thank you all, I'll get to this soon-ish and finalize this. I'm sorry for the delays.

**Comment by honzajavorek** [comment]
BTW once this is done it closes https://github.com/apiaryio/dredd/issues/422

**Comment by honzajavorek** [comment]
Working on https://github.com/apiaryio/dredd-docker/pull/1, stay tuned! Sorry for the delay.

**Comment by honzajavorek** [comment]
An official and up-to-date Docker image is now available at [apiaryio/dredd-docker](https://github.com/apiaryio/dredd-docker). Please check it out and let me know if it works for you. Thanks!
