### ISSUE TITLE
Unable to install Dredd on High Sierra MacOS

### ISSUE THREAD

**Issue by hunzai** [apiaryio/dredd#1109]
I am trying to install dredd but getting following error 
**node -v . -> v10.9.0**

**npm -v .  -> 6.4.1**

#### Unable to install Dredd on High Sierra MacOs. 

I am also getting following error when try to install Dredd
`6609 verbose lifecycle jsonpath@1.0.0~postinstall: CWD: /usr/local/lib/node_modules/dredd/node_modules/jsonpath
6610 silly lifecycle jsonpath@1.0.0~postinstall: Args: [ '-c', 'node lib/aesprim.js > generated/aesprim-browser.js' ]
6611 silly lifecycle jsonpath@1.0.0~postinstall: Returned: code: 1  signal: null
6612 info lifecycle jsonpath@1.0.0~postinstall: Failed to exec postinstall script
6613 timing action:postinstall Completed in 28ms
6614 verbose unlock done using /Users/amjad.saleem/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
6615 timing stage:rollbackFailedOptional Completed in 1359ms
6616 timing stage:runTopLevelLifecycles Completed in 9341ms
6617 warn optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 (node_modules/dredd/node_modules/protagonist):
6618 warn optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 install: `node-gyp rebuild`
6618 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
6619 verbose optional SKIPPING OPTIONAL DEPENDENCY:
6619 verbose optional Failed at the protagonist@1.6.8 install script.
6619 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
6620 verbose stack Error: jsonpath@1.0.0 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
6620 verbose stack Exit status 1
6620 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
6620 verbose stack     at EventEmitter.emit (events.js:182:13)
6620 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
6620 verbose stack     at ChildProcess.emit (events.js:182:13)
6620 verbose stack     at maybeClose (internal/child_process.js:961:16)
6620 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
6621 verbose pkgid jsonpath@1.0.0
6622 verbose cwd /Users/amjad.saleem
6623 verbose Darwin 17.7.0
6624 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "dredd"
6625 verbose node v10.9.0
6626 verbose npm  v6.2.0
6627 error code ELIFECYCLE
6628 error errno 1
6629 error jsonpath@1.0.0 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
6629 error Exit status 1
6630 error Failed at the jsonpath@1.0.0 postinstall script.
6630 error This is probably not a problem with npm. There is likely additional logging output above.
6631 verbose exit [ 1, true ]`

#### What command line options do you use?

```
 npm install -g dredd
```

#### What is in your `dredd.yml`?

```yaml
( paste your dredd.yml contents here )
```

#### What's your `dredd --version` output?

```
( paste your output here )
```

**Comment by hunzai** [comment]
It was related to permission on my machine. 

I installed node with sudo that is messing up writing to folders. Just install node without sudo then all works

**Comment by honzajavorek** [comment]
I’m glad you got it working!
