### ISSUE TITLE
Examples from swagger schema definitions are ignored when generating requests

### ISSUE THREAD

**Issue by skyellin** [apiaryio/dredd#1115]
#### Describe your problem

Examples from swagger schema definitions are ignored when generating requests.  Given the swagger definition provided below, I would expect the `email` field to have a value of `test@example.com`.  Instead, I see the following output:

```
request: 
method: POST
uri: /api/test
headers: 
    Content-Type: application/json
    User-Agent: Dredd/5.1.11 (Linux 4.9.93-linuxkit-aufs; x64)
    Accept:  application/json
    Content-Length: 63

body: 
{
  "id": 58730817,
  "email": "proident sunt ipsum occaecat"
}
```
#### What command line options do you use?

```
dredd --config=/www/tests/dredd/config.yml
```

#### What is in your `dredd.yml`?

```yaml
blueprint: "http://127.0.0.1/apidoc.json"
endpoint: "http://127.0.0.1"
path: []
color: true
header: ["Accept: application/json"]
```

#### What's your `dredd --version` output?

```
dredd v5.1.11 (Linux 4.9.93-linuxkit-aufs; x64)
```

#### Swagger

```json
{
  "swagger": "2.0",
   "info": {
    "title": "Test",
    "description": "Test",
    "version": "1.0.0"
  },
  "consumes": [
    "application/json"
  ],
  "paths": {
    "/api/test": {
      "post": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "description": "test",
            "schema": {
              "$ref": "#/definitions/test_definition"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Test"
          }
        }
      }
    }
  },
  "definitions": {
    "test_definition": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "email": {
          "example": "test@example.com",
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by honzajavorek** [comment]
@skyellin I don't think this way of providing examples is supported in Swagger/OpenAPI 2.0. You can provide examples for request parameters using [x-example](https://help.apiary.io/api_101/swagger-extensions/#x-example). You can provide examples for response bodies using the [example object](https://swagger.io/specification/v2/#exampleObject).

**Comment by skyellin** [comment]
@honzajavorek I could well be mis-reading, but this seems to suggest that they are supported: https://swagger.io/docs/specification/2-0/adding-examples/

**Comment by honzajavorek** [comment]
@skyellin You are right. Let me verify the [Swagger adapter](https://github.com/apiaryio/fury-adapter-swagger) supports that.

**Comment by honzajavorek** [comment]
So this is not currently supported correctly and should be supported once https://github.com/apiaryio/fury-adapter-swagger/pull/203 gets done.

**Comment by honzajavorek** [comment]
I think this should be resolved by now. Please report under this issue or create a new one if the problems persist.
