### ISSUE TITLE
Error connecting to server under test!

### ISSUE THREAD

**Issue by shilpa2112** [apiaryio/dredd#1125]
I tried comparing the spec to real endpoint responses (using Https url), its throwing error 
fail: Error connecting to server under test!

What will be the configuration required to use self signed certificate for hitting https url.

**Comment by honzajavorek** [comment]
Hi @shilpa2112, thanks for trying Dredd! This is because of https://github.com/apiaryio/dredd/issues/913 and https://github.com/apiaryio/dredd/issues/323.

There is a workaround mentioned in https://github.com/apiaryio/dredd/issues/913#issuecomment-381419699, would it work for you?

**Comment by honzajavorek** [comment]
@shilpa2112 Does that answer your question?

**Comment by honzajavorek** [comment]
@shilpa2112 I hope my answer has helped you. I'm closing this now, but feel free to comment if you have further questions.
