### ISSUE TITLE
Exclude a test from showing in the documentation

### ISSUE THREAD

**Issue by larnouch** [apiaryio/dredd#1128]
I'm always working with Dredd tests to generate the api documentation but sometimes I'm don't like to generate every test case into the documentation.

I would like to be able to exclude a specific test from being generated into the documentation.

**Comment by honzajavorek** [comment]
Hi @larnouch, Dredd does not generate documentation, it tests the API description document against the implementation of the API and tells you whether it fits the description. Unless I know what tool exactly you use to generate the documentation (is it [Apiary](https://apiary.io/)?), I can't help you.

I'll close this now, but feel free to continue commenting if you can provide more info. Thanks!

**Comment by larnouch** [comment]
Hi @honzajavorek , thanks for your feedback ! 
Well, I'm using api blueprint as the tool to generate the documentation.

**Comment by honzajavorek** [comment]
@larnouch API Blueprint is the underlying API description document format. Do you know which tool you use to generate documentation from it? Do you run a particular command or do you upload the API Blueprint document somewhere to get the documentation rendered as a HTML page?

**Comment by larnouch** [comment]
@honzajavorek I'm using fury for generating that HTML ! [Fury](https://github.com/apiaryio/fury.js)
Thanks for your help.

**Comment by honzajavorek** [comment]
@larnouch I'm afraid Fury also isn't the documentation renderer. Fury parses the API description document into something ([API Elements](https://apielements.org)) other tools (such as documentation renderers or Dredd) can consume.

Are you using [Apiary](https://apiary.io/) to render the documentation? Or maybe [Aglio](https://github.com/danielgtaylor/aglio)?

**Comment by larnouch** [comment]
@honzajavorek I was checking it now and it's indeed Apiary.
