### ISSUE TITLE
[docs] Installation

### ISSUE THREAD

**Issue by floggle** [apiaryio/dredd#1159]
The install docs are woefully inadequate.
A simple "npm install dredd" doesn't work.

It seems that the node install needs to be in the system PATH or one of the requirements fails (protagonist).
Haven't done that, it's giving a big page of error that seems to equate to requiring python installed and in the path.
```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```
Although looking closer at the end, it seems to have worked.

Could I suggest improving the "installation" docs to make these requirements clearer, or otherwise not provide error messages of this sort when an optional dependency fails?

edit: And if I do provide a Python path, it still fails, this time with a SyntaxError!

**Comment by honzajavorek** [comment]
@floggle Hi! Thanks for trying to use Dredd and thanks for the issue!

> The install docs are woefully inadequate.

Could you please be more specific which docs exactly you mean? I recently updated the [installation docs](http://dredd.org/en/latest/installation.html) to be as adequate and detailed as possible, but I might have miss something of course, or you may be referring to other docs (READMEs etc.). In that case I'd very much like to fill the gaps.

You are experiencing problems with the C++ dependencies, which have their [dedicated section](http://dredd.org/en/latest/installation.html#installing-c-dependencies).
