### ISSUE TITLE
Pattern Matching on Header values

### ISSUE THREAD

**Issue by bmironer** [apiaryio/dredd#116]
Pattern matching on header values would allow for **Location:** header validation on 201 Created responses after a POST. Or to validate the presence and format of a ETag, or Set-Cookie header.

At the least, I'd need to be able to test that a header is present, regardless of its value.

Might be more of a Gavel issue though.

**Comment by cw-peter** [comment]
Yes, this is vital for testing ie `set-cookie` where the expiry is a dynamic time for example.

**Comment by netmilk** [comment]
This is more a [Gavel](https://github.com/apiaryio/gavel.js) issue, but I think the right way is to validate value only of some specific headers e.g. `content-type` and company.

**Comment by cw-peter** [comment]
I think the library should support flexibility here. I want to test for a cookie on a header, but ignore the expires time.

**Comment by netmilk** [comment]
Just for clarification, presence of all headers given in the blueprint will be validated as it is validated now, but exact match of value will be validated only for some headers.

**Comment by honzajavorek** [comment]
@cw-peter @bmironer @netmilk This is now possible thanks to Dredd's hooks. Do you think we can close this now or that a built-in support would be still appreciated?

**Comment by netmilk** [comment]
@honzajavorek I agree. Would you mind providing some hooks code snippet and maybe add it to the documentation and provide link here?

**Comment by base698** [comment]
How do you ignore headers?  Or provide a regex to match dates?

**Comment by honzajavorek** [comment]
@base698 I still don't have the examples @netmilk mentioned prepared, but you have access to the [transaction object](http://dredd.readthedocs.io/en/latest/data-structures/#transaction-object) in the [hooks](http://dredd.readthedocs.io/en/latest/hooks-nodejs/). You can modify it in any way you want. You can affect both request or response headers. See e.g. [Node.js hooks examples](http://dredd.readthedocs.io/en/latest/hooks-nodejs/#modifying-transaction-request-body-prior-to-execution) or [sanitation examples](http://dredd.readthedocs.io/en/latest/how-to-guides/#sanitation-of-request-headers).

**Comment by ralucas** [comment]
Is it possible to do this in hooks without modifying anything, just overriding Gavel's expectations?

**Comment by honzajavorek** [comment]
I think you should be able to use `beforeValidation` and `transaction.test` for that - https://github.com/apiaryio/dredd/issues/253#issuecomment-258203400

**Comment by artem-zakharchenko** [comment]
To fully support such custom assertions on headers there should be a dedicated syntax in place for API Blueprint (MSON for headers?).

**As of now, it's recommended to perform custom assertions against headers, or any other HTTP message data using hooks:**

```js
const hooks = require('hooks')
const { expect } = require('chai')

// Target your resource in the API Blueprint document
hooks.beforeValidation('Project name > Resource name', (transaction) => {
  // Grab the header's actual value.
  const headerValue = transaction.real.headers['my-token']
  // Ensure it's in the 123-12 format
  expect(headerValue).to.match(/\d{3}-\d{2}/)
})
```

Read more about [Using chai assertions in hooks](http://dredd.org/en/latest/hooks/js.html#using-chai-assertions). These examples illustrate the JavaScript Hooks API, but you can use the same logic in any programming language supported by Dredd Hooks. Hope this helps.
