### ISSUE TITLE
Generating a (Negative Case) HTTP request which verifies the validations provided in Request.

### ISSUE THREAD

**Issue by khvr000** [apiaryio/dredd#1160]
**Not verifying the actual backend  validation layer is a problem** 
It seems Dredd generates a valid HTTP request  bound to conditions given in api description document .

 I would like to know if by any way  can we generate wrong HTTP request where in request validation should fail from backend,  there by achieving complete api-description document functional testing with  Dredd.

If not by dredd, and there are alternative ways to achieve the above , please throw some light for which I would be thankful.

Thank You.

@honzajavorek

**Comment by honzajavorek** [comment]
@khvr000 You can document a wrong HTTP request with an expected HTTP response. E.g. a request where the API consumer is sending invalid data in the request body, and the server responds with a 500. An example in the API Blueprint format:

```apib
## Customers [/customers]

### Create a new customer [POST]

+ Request (application/json)
    + Attributes
        + email: `hello@example.com` (string)

+ Response 201 (application/json)
    + Attributes
        + id: 123 (number)
        + email: `hello@example.com` (string)


+ Request Invalid e-mail address (application/json)
    + Attributes
        + email: `hell@.` (string)

+ Response 400 (application/json)
    + Attributes
        + message: `Invalid e-mail address` (string)
```

This leverages [multiple requests and responses](https://dredd.org/en/latest/how-to-guides.html#multiple-requests-and-responses).

The OpenAPI 2 (Swagger) format only supports multiple responses though. In that case, one option is to have multiple API descriptions (one for documentation of positive scenarios, another for some edge cases, ...) and test with all of them using [--path](https://dredd.org/en/latest/usage-cli.html#cmdoption-path). Another option would be to have [hooks](https://dredd.org/en/latest/hooks.html), which alter the requests, or which [modify the transactions list](https://github.com/apiaryio/dredd/issues/995).

**Comment by honzajavorek** [comment]
Let me know please if this answers your question.

**Comment by honzajavorek** [comment]
@khvr000 Did my answer solve your problem?

**Comment by khvr000** [comment]
Thanks a lot @honzajavorek ,
Your answer does solve my problem.
