### ISSUE TITLE
Sending Multiple Requests to increase the authenticity of Functional Testing

### ISSUE THREAD

**Issue by khvr000** [apiaryio/dredd#1161]
Dredd is making a single HTTP request by generating a single HTTP request and validating the expected response with actual response 

I would like to know if there is any way we could generate multiple HTTP request(for each method in each resource) covering all the possibilities by modifying the expectation generation logic , it would be great which  increases the testing scope for our REST Services by mega mile.

Also I understood dredd uses gavel js library for validation , can some please mention how dredd is able to generate expectations and making it into request , Thanks in advance .

**Comment by honzajavorek** [comment]
I think https://github.com/apiaryio/dredd/issues/1160#issuecomment-448145458 answers this issue as well, but please feel free to comment further if you don't think the same.

All Dredd's automatic expectations are [documented in the docs](https://dredd.org/en/latest/how-it-works.html#automatic-expectations). Regarding Gavel in particular, there's a whole [language-agnostic BDD spec](https://github.com/apiaryio/gavel-spec) documenting (and testing) its behavior.
