### ISSUE TITLE
Charset header comparisons should be case insensitive.

### ISSUE THREAD

**Issue by webmaven** [apiaryio/dredd#117]
I have a test on the correct charset being returned, but the test fails because the comparison is case sensitive (so 'UTF-8' is not equal to 'utf-8').

**Comment by kettanaito** [comment]
According to the #1086 this is not a Dredd's issue. Should this still be open?

**Comment by honzajavorek** [comment]
Transitively it is a Dredd issue as Dredd's behavior isn't correct, but I think it needs to be fixed in Gavel. (Also ideally, this would be a monorepo where Gavel lives as well since those two projects are very close to each other.)

**Comment by honzajavorek** [comment]
This has been fixed in recent versions of Gavel and propagated to Dredd.
