### ISSUE TITLE
Handling of `additionalProperties: false` and `required: [...]` not as expected

### ISSUE THREAD

**Issue by davidgengenbach** [apiaryio/dredd#1193]
**Describe the bug**
I want to test an API against the specification ensuring that
- all properties defined in an response schema are actually sent by the backend (`required: [...]`)
- no additional properties are sent by the backend (`additionalProperties: false`) on the response schema

(https://dredd.org/en/latest/how-to-guides.html#making-dredd-validation-stricter)

**To Reproduce**
https://gist.github.com/davidgengenbach/7f0a6e022acc35e47a44bb1a32f6a8d1

**Expected behavior**
Dredd should fail when
1) additionalProperties: false is defined in a response schema
2) the response does not contain elements defined in the "required" section of the response schema

**What is in your `dredd.yml`?**

```yaml
swagger: "2.0"
info:
  title: HttpBin
  description: Test
  version: 1.0.0
paths:
  /get:
    get:
      summary: Test 
      consumes:
        - application/json
      parameters:
        - in: body
          name: response
          schema:
            $ref: "#/definitions/HttpBinResponse"
      responses:
         200:
           description: OK
definitions:
  HttpBinResponse:
    type: object
    # This should fail for since there are several attributes in the response which are not under "properties"
    additionalProperties: false
    required:
      # This should also fail the test since this attribute is not in the response 
      - SomeWrongAttributeWhichIsNotInResponseButRequired
    properties:
      SomeWrongAttributeWhichIsNotInResponseButRequired:
        type: string
```

**What's your `dredd --version` output?**

```
dredd v5.4.4 (Linux 4.19.10-300.fc29.x86_64; x64)
```

**Does `dredd --level=debug` uncover something?**
No.
```
verbose: Loading configuration file: ./dredd.yml
debug: Dredd version: 5.4.4
debug: Node.js version: v8.11.3
debug: Node.js environment: http_parser=2.8.0, node=8.11.3, v8=6.2.414.54, uv=1.19.1, zlib=1.2.11, ares=1.10.1-DEV, modules=57, nghttp2=1.32.0, napi=3, openssl=1.0.2o, icu=60.1, unicode=10.0, cldr=32.0, tz=2017c
debug: System version: Linux 4.19.10-300.fc29.x86_64 x64
debug: npm version: 5.6.0
debug: Configuration: {"server":"https://httpbin.org","options":{"_":["swagger.2.yaml"],"level":"debug","l":"debug","dry-run":null,"y":null,"hookfiles":null,"f":null,"language":"nodejs","a":"nodejs","sandbox":false,"b":false,"server":null,"g":null,"server-wait":3,"init":false,"i":false,"custom":{},"j":[],"names":false,"n":false,"only":[],"x":[],"reporter":[],"r":[],"output":[],"o":[],"header":[],"h":[],"sorted":false,"s":false,"user":null,"u":null,"inline-errors":false,"e":false,"details":false,"d":false,"method":[],"m":[],"color":true,"c":true,"timestamp":false,"t":false,"silent":false,"q":false,"path":["swagger.2.yaml","swagger.2.yaml"],"p":["swagger.2.yaml","swagger.2.yaml"],"hooks-worker-timeout":5000,"hooks-worker-connect-timeout":1500,"hooks-worker-connect-retry":500,"hooks-worker-after-connect-wait":100,"hooks-worker-term-timeout":5000,"hooks-worker-term-retry":500,"hooks-worker-handler-host":"127.0.0.1","hooks-worker-handler-port":61321,"config":"./dredd.yml","$0":"dredd"},"custom":{"cwd":"/home/dgengenbach/tmp/tmp_dredd-test_2019_01_10__16_13_14","argv":["swagger.2.yaml","https://httpbin.org","--level","debug"]}}
verbose: Using 'base' reporter.
verbose: Configuring reporters: []
verbose: Using 'cli' reporter.
verbose: No backend server process specified, starting testing at once
verbose: Running Dredd instance.
verbose: Expanding glob patterns.
verbose: Reading API description files.
verbose: Parsing API description files and compiling a list of HTTP transactions to test.
verbose: Compiling HTTP transactions from API description file: swagger.2.yaml
verbose: Starting reporters and waiting until all of them are ready.
info: Beginning Dredd testing...
verbose: Starting transaction runner.
verbose: Sorting HTTP transactions
verbose: Configuring HTTP transactions
verbose: Reading hook files and registering hooks
verbose: Executing HTTP transactions
verbose: Running 'beforeAll' hooks
verbose: Processing transaction #1: /get > Test > 200
verbose: Running 'beforeEach' hooks
verbose: Running 'before' hooks
debug: Emitting to reporters: test start
debug: Performing HTTPS request to the server under test: GET https://httpbin.org/get
debug: Handling HTTPS response from the server under test
verbose: Running 'beforeEachValidation' hooks
verbose: Running 'beforeValidation' hooks
verbose: Validating HTTP transaction by Gavel.js
debug: Determining whether HTTP transaction is valid (getting boolean verdict)
debug: Validating HTTP transaction (getting verbose validation result)
verbose: Running 'afterEach' hooks
verbose: Running 'after' hooks
debug: Evaluating results of transaction execution #1: /get > Test > 200
debug: Emitting to reporters: test pass
pass: GET (200) /get duration: 600ms
verbose: Running 'afterAll' hooks
verbose: Wrapping up testing.
complete: 1 passing, 0 failing, 0 errors, 0 skipped, 1 total
complete: Tests took 602ms
verbose: Dredd instance run finished.
verbose: Exiting Dredd process with status '0'.
debug: Using native process.exit() method to terminate the Dredd process.
verbose: No backend server process to terminate.
```

**Can you send us failing test in a Pull Request?**
I would love to if you give me hints where to start.

**Comment by honzajavorek** [comment]
Hi @davidgengenbach, thanks for using Dredd! I've checked out the gist and I see you're using an OpenAPI 2 `in: body` parameter:

```yaml
      parameters:
        - in: body
          name: response
          schema:
            $ref: "#/definitions/HttpBinResponse"
```

Such parameter describes a request body though. Since we're talking about a GET request here, I believe you wanted to have this as a description of the response body. That can be achieved by providing a [schema property](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject) within the [Response Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject).

By the way, you could also provide an [example property](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#exampleObject) with a specific example with your own values, so Dredd doesn't make up the values and can follow the [specification by example](https://en.wikipedia.org/wiki/Specification_by_example) approach to testing.

Would that work for you?

**Comment by davidgengenbach** [comment]
Thanks a lot for your fast answer. Yes, the example I provided was flawed. My underlying problem (which is not reflected in this PR or gist) was that I had "$ref"s in schemas which where not correctly resolved - and in turn they weren't validated at all.
I fixed it by de-referencing the `$ref`s with the `swagger-cli` but will most likely create another issue for help - since I need `$ref` for recursive (cyclic) types!

**Comment by AlexDalusongiQ** [comment]
I am not sure if I should be creating for new issue for this, but I am facing a similar issue where I am in the same boat as issue reporter:

I am trying to validate my OAS spec against the API, and ran into trouble regarding this validation:

- test is passing even though:
  - `additionalProperties: false`
  - field 'Name' appears in actual/real response
  - field 'Name' is not in the schema that is referenced by the response body of the GET call

In the Apiary UI, it shows that the expected has no 'Name' field, but real has that field, yet the status shows as passed.

Let me know what pieces of information I would need to provide for this as this is my first time reporting an issue.

**Comment by davidgengenbach** [comment]
@AlexDalusongiQ I re-created this issue with more debug information and a better example: https://github.com/apiaryio/dredd/issues/1195
This seems to be - in essence - a problem with `$ref`!

> Let me know what pieces of information I would need to provide for this as this is my first time reporting an issue.

When creating an issue, you will see a template which asks you for the relevant information! Apart from that, a **minimal** (!!!) example which reproduces the error is always nice to pin-point the problem further.
If you troubleshot the issue and found something interesting, you can also put your findings in the issue as well!

**Comment by AlexDalusongiQ** [comment]
@davidgengenbach 

For some reason I was thinking that it is still 2019 when it's already 2020 *facepalm*

Thank you for the quick follow-up
