### ISSUE TITLE
Warning when installing Dredd 7.2.0 - deprecated nomnom@1.5.2

### ISSUE THREAD

**Issue by DFaiz** [apiaryio/dredd#1221]
**Describe the bug**
When running `npm install dredd@7.2.0` I encounter the following message:
 
> npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.

Is there an intention to update or replace the packages that use nomnom ?

**To Reproduce**
Simply run `npm install dredd@7.2.0`

**Expected behavior**
Finish installation without any issues.

**Comment by honzajavorek** [comment]
Thanks for filing this as an issue!

> Is there an intention to update or replace the packages that use nomnom ?

Definitely. Currently there's https://github.com/apiaryio/dredd/pull/1220 open, but it's failing, so I need to figure out upgrading the dependencies one by one. I don't recall from where exactly nomnom comes, but I remember we've been urging a maintainer of one project to replace it. If you feel like helping with investigation on which package exactly is the culprit and what exactly needs to be upgraded, it would be awesome.

**Comment by DFaiz** [comment]
Hey, isn't just going over package-lock and finding the packages that use `nomnom` and updating them?

**Comment by realityking** [comment]
Unfortunately this is not a matter of an outdated package but an unmaintained package. This PR would fix it: https://github.com/dchester/jsonpath/pull/94

**Comment by realityking** [comment]
dchester/jsonpath#94 got resolved and dredd no longer depends on nomnom :)

**Comment by honzajavorek** [comment]
I can confirm that installing Dredd doesn't print anything about nomnom anymore:

```
$ npm i dredd

> core-js@2.6.9 postinstall /Users/honza/Projects/deps/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> jsonpath@1.0.2 postinstall /Users/honza/Projects/deps/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN deps@1.0.0 No description
npm WARN deps@1.0.0 No repository field.

+ dredd@11.2.6
added 232 packages from 244 contributors and audited 314 packages in 13.283s
found 0 vulnerabilities
```

There is the call for support of core-js now, but we can't do much about that except of perhaps hiring @zloirock to the @apiaryio team. That would be a separate issue though 😄
