### ISSUE TITLE
Dredd 7.2 conflicts with drafter 1.2

### ISSUE THREAD

**Issue by realityking** [apiaryio/dredd#1223]
**Describe the bug**
Dredd 7.2 fails where 7.1 works.

The error I get is

```
/Users/rouven/PhpStormProjects/doc-app/node_modules/minim/lib/serialisers/json.js:56
      throw new Error('Given value is not an object containing an element name');
      ^

Error: Given value is not an object containing an element name
    at constructor.deserialise (/Users/rouven/PhpStormProjects/doc-app/node_modules/minim/lib/serialisers/json.js:56:13)
    at constructor.<anonymous> (/Users/rouven/PhpStormProjects/doc-app/node_modules/minim/lib/serialisers/json.js:144:24)
    at Array.forEach (<anonymous>)
    at constructor.deserialiseObject (/Users/rouven/PhpStormProjects/doc-app/node_modules/minim/lib/serialisers/json.js:143:23)
    at constructor.deserialise (/Users/rouven/PhpStormProjects/doc-app/node_modules/minim/lib/serialisers/json.js:67:12)
    at Array.map (<anonymous>)
    at constructor.deserialiseContent (/Users/rouven/PhpStormProjects/doc-app/node_modules/minim/lib/serialisers/json.js:121:24)
    at constructor.deserialise (/Users/rouven/PhpStormProjects/doc-app/node_modules/minim/lib/serialisers/json.js:74:24)
    at constructor.fromRefract (/Users/rouven/PhpStormProjects/doc-app/node_modules/minim/lib/namespace.js:175:28)
    at Fury.load (/Users/rouven/PhpStormProjects/doc-app/node_modules/fury/lib/fury.js:41:23)
```

**To Reproduce**
We invoke dredd through the JS API since we're using Hercule. This is how we invoke dredd:

```
const dredd = new Dredd({
  server: API_URLS[api],
  options: {
    hookfiles: [baseDir('test/dredd/test-hook.js')],
    header: [`X-Contentful-User-Agent:app dredd/${dreddVersion}`]
  },
  data: {source: blueprint}
});
```

**Expected behavior**

It should work the same as 7.1.
**What is in your `dredd.yml`?**

Not applicable.

**What's your `dredd --version` output?**

```
dredd v7.2.0 (Darwin 17.7.0; x64)
```

**Does `dredd --level=debug` uncover something?**

No change.

**Can you send us failing test in a Pull Request?**

Not sure yet. I just started looking into it - but this seems like a major regression.

**Comment by honzajavorek** [comment]
@realityking It would help to have a somewhat minimal example to reproduce this.

**Comment by kylef** [comment]
@realityking If you can share the underlying compiled API Blueprint that would really help debug, otherwise you could add some logging into `/Users/rouven/PhpStormProjects/doc-app/node_modules/minim/lib/serialisers/json.js`. If you added something like:

```json
console.log(JSON.stringify(value, null, 2));
```

Just above the if statement in line 56, like the following:

![screenshot 2019-01-31 at 12 00 48](https://user-images.githubusercontent.com/44164/52052942-e53af080-254f-11e9-911a-21cee7b053dd.png)

This should print every element before deserialisation and should print the couple of elements leading up to the exception being raised, the bug may be in Minim deserialiser or in Drafter 4 producing incorrect element structure.

**Comment by realityking** [comment]
Something interesting is going on here.

I use this minimal example:

```
const Dredd = require('dredd');

const dredd = new Dredd({
  server: 'https://cdn.contentful.com',
  data: {source: ''}
});

dredd.run((...args) => {
  console.log(args);
});
```

This fails in my setup however it does work fine when I try it within the dredd repo (with the first line changed to `const Dredd = require('.');`

Turns out, the problem is that we have a direct dependency of drafter 1.2 (we use the blueprint AST). Apparently dredd is picking that up and since the data formt changed things go wrong.

**Comment by honzajavorek** [comment]
Oh! Dredd now depends on Drafter v4, which drops the API Blueprint AST support. It only supports [API Elements](http://apielements.org/). The AST has been deprecated for a long time, and we're trying to remove it from all our products, newly integrating on top of the API Elements exclusively everywhere. Since Dredd is not using the AST since the moment we added support for Swagger (long, long time ago), I didn't realize this could be an issue. But it makes sense - you can have only one version of Drafter compiled in your node_modules.

I'm not sure what would be a workaround for this 🤔

**Comment by kylef** [comment]
@realityking As a wordaround, you could potentially depend directly on drafter.js (https://github.com/apiaryio/drafter.js/), as that's pure JavaScript it should be safe to have both drafter.js @ 2.6.7 and the one Dredd requires in its own tree (3.0.0-pre.2). Drafter.js should be a drop in component for Drafter providing you have similiar versions.

**Comment by realityking** [comment]
> But it makes sense - you can have only one version of Drafter compiled in your node_modules.

Why would that be the case?

This is the output I'm getting from `npm list drafter`

```
├── drafter@1.2.0
└─┬ dredd@7.2.0
  └─┬ dredd-transactions@6.4.0
    └─┬ fury-adapter-apib-parser@0.13.0-beta
      └── drafter@2.0.0-pre.1
```

Question is, why is dredd using the wrong drafter installation?

**Comment by honzajavorek** [comment]
I don't think npm supports having multiple versions of _compiled_ dependencies. I.e. you can have multiple versions of `drafter.js`, but not multiple versions of `protagonist`.

**Comment by realityking** [comment]
I think it does support that. The problem is the modification of drafter to remove protagonist. Drafter's JS code is still the following:

```
try {
  var protagonist = require('protagonist');

  module.exports = {
    parse: protagonist.parse,
    parseSync: protagonist.parseSync,

    validate: protagonist.validate,
    validateSync: protagonist.validateSync,
  };
} catch (error) {
  var drafterjs = require('drafter.js');

  module.exports = {
    parse: drafterjs.parse,
    parseSync: drafterjs.parseSync,

    validate: drafterjs.validate,
    validateSync: drafterjs.validateSync,
  };
}
```

This will load _any_ version of protagonist that happens to be in the node_modules. I believe this is causing my problems.

**Comment by kylef** [comment]
> I think it does support that.

You'll get undefined behaviour (depending on platform) where you have two dynamic libraries that have same symbol names. Which can cause odd behaviour such as https://github.com/apiaryio/protagonist/issues/136.

Here's some more details copied from an internal ticket back in 2016:

> Although https://github.com/apiaryio/protagonist/issues/136 says it's fixed, it's still not fixed. I was hit by this multiple times. Since it's normal for node modules they can be installed within one project with different versions (once as a dependency and second time as a dependency of a dependency) and they normally work.
>
> Imagine situation I depend on a library which I haven't created and I don't have it under control. The library uses protagonist of version A, e.g. as a devDependency for some tests, whilst I want to use version B as a regular dependency for my project. I'm screwed in that case, since the only thing I'm left with is "unknown visitor type" error for any blueprint I send to my protagonist.
>
> ---
>
> There isn't much we can do here, it's a limitation of NPM / how dynamic loading works.
>
> We recommend that users use the drafter NPM package, which would allow a user to work around these limitations by using the pure javascript parser. If you need to use multiple / different versions of the parser in the same code-base, you can use --no-optional when installing the dependencies to use the pure JS version only.

**Comment by realityking** [comment]
Ah that makes sense. It's not directly applicable to my case since drafter and dredd are dependencies of the same project but never loaded at the same time.

I guess the long term fix is something like https://github.com/apiaryio/fury-adapter-apib-parser/pull/37

**Comment by kylef** [comment]
@realityking Agreed, the wordaround I mentioned in https://github.com/apiaryio/dredd/issues/1223#issuecomment-459329181 should work for you for now, just change your own dependency to "drafter.js" and update the require statements and you should be good to go. Make sure you don't use any of the pre-releases though as they don't offer API Blueprint AST. (I would encourage you to move off of that at some point, it is deprecated for nearly 4 years https://github.com/apiaryio/api-blueprint-ast#deprecation-notice. Any new language features in API Blueprint won't be available to our older parsers).

We're just wrapping up with our OAS 3 parser, next up we will attempt to roll out Drafter 4 to our entire infrastructure and then once that's live we'll go ahead and try to solve https://github.com/apiaryio/fury-adapter-apib-parser/pull/37.

**Comment by honzajavorek** [comment]
I don't think this is anything Dredd maintainers in particular could solve 😞 This needs altering how the parsing toolchain works - dependency injection in place, perhaps. Apart from workarounds there's nothing I can offer at this moment, unfortunately.

Once the parsing toolchain allows for dependency injection or further configuration, Dredd is about to make sure it uses just the JS dependency, so that shouldn't conflict with anything else in the `node_modules`.
