### ISSUE TITLE
Flag to allow for dependent execution of tests

### ISSUE THREAD

**Issue by ghost** [apiaryio/dredd#123]
It would be great to have a flag that executed tests only until one failed. Often later tests (e.g. a GET) are dependent on the success of an earlier test (e.g. a POST), and will always fail if the earlier tests fail. Error messages in this case do not provide the user with any information.

**Comment by netmilk** [comment]
Could it be hooks driven? Something like:

```coffee
{before, after, dependsOn} = require 'hooks'

before "Machines > Machines collection > Get Machines", (transaction) ->
  dependsOn "Machines > Machines collection > Create Machine"
```

**Comment by honzajavorek** [comment]
I'm folding this under https://github.com/apiaryio/dredd/issues/995 and https://github.com/apiaryio/dredd/issues/358, I think those two cover the use case described here.
