### ISSUE TITLE
Incorrect Body for large responses

### ISSUE THREAD

**Issue by garyluu** [apiaryio/dredd#1254]
**Describe the bug**
When running against an endpoint with a fairly large response (roughly 131 kb worth when downloaded the response from swagger-ui), printing out transaction['real']['body'] yields something like:
```
mlvc3BoZXJlJTJGdG9wbWVkLXdvcmtmbG93cyUyRkZ1bmN0aW9uYWxfRXF1aXZhbGVuY2UvdmVyc
``` 

**To Reproduce**
dredd version 8.0.3
dredd_hooks version 0.2.0
`dredd <my-yaml> <my server> -l warning --no-color -a python -f <my hookfile>`

When running against the same endpoint with different query parameter which yields 110 kb worth of data in the response body, it looks fine.  Also, the last version that I used (dredd version 4.7.0) also works with the same size response.

My python hooks file looks something like:
```
@after('... > List all tools > 200 > application/json')
def add_value(transaction):
    try:
        body = transaction['real']['body']
        print body
        jdata = json.loads(body)
        print jdata
    except (KeyError, TypeError) as e:
        return
```

**Expected behavior**
transaction['real']['body'] to yield a json response or to throw some sort of error saying it's too large (if it is simply too large)

**What is in your `dredd.yml`?**

```yaml
( paste your dredd.yml contents here )
```

Don't have one I think

**What's your `dredd --version` output?**

```
dredd v8.0.3 (Linux 4.15.0-43-generic; x64)

```

**Does `dredd --loglevel=debug` uncover something?**
If you run Dredd with debugging output, do you see any interesting information relevant to the bug?
```
2019-02-27T21:55:47.849Z - debug: Running hooks...
2019-02-27T21:55:47.850Z - debug: Sending HTTP transaction data to hooks handler: 5b84a020-1a6c-4aa6-9b90-5b16f1737cc5
2019-02-27T21:55:47.906Z - debug: Hooks handler stdout: W3siYWxpYXNlcyI6W10sImF1dGhvciI6IkZyYW5jZXNjbyBGYXZlcm8iLCJjaGVja2VyX3VybCI6IiIsImNvbnRhaW5zIjpbXSwiZGVzY3JpcHRpb24iOiIhW10oaHR0cHM6Ly9ieXRlYnVja2V0
2019-02-27T21:55:47.911Z - debug: Hooks handler stderr: Connection closed, could not parse JSON
```

**Can you send us failing test in a Pull Request?**
We'll gladly help you to contribute; answering yes raises the chances the issue gets fixed.

**Comment by honzajavorek** [comment]
@garyluu In case the response is binary, Dredd sends it encoded as Base64. This is indicated in the [`bodyEncoding` property](http://dredd.org/en/latest/data-structures.html#transaction-object). I notice you're using Python, in that case you could use following to decode it:

```python
import base64

...

if transaction['real']['bodyEncoding'] == 'base64':
    data = base64.b64decode(transaction['real']['body'])
else:
    data = transaction['real']['body']
```

Let me know if that works.

**Comment by garyluu** [comment]
So that works for my hook, but I think the main issue for me right now is figuring out why it's base64.

I've simplied the process:

`dredd thing.yaml https://dockstore.org:8443 -l error --no-color`
where thing.yaml is:
```
basePath: /api/ga4gh/v2
definitions:
  Tool:
    description: A
    properties:
      aliases:
        description: "a"
        items: {type: string}
        type: array
    type: object
info: {description: 'Thing', title: Thing, version: 2.0.0}
parameters:
  limit: {default: 100, description: thing,
    format: int32, in: query, name: limit, type: integer}
  offset: {description: 'a',
    in: query, name: offset, type: string}
paths:
  /tools:
    get:
      description: "a"
      operationId: toolsGet
      parameters:
      - {description: 'A', in: query, name: id, type: string}
      - {description: "A", in: query, name: alias,
        type: string}
      - {description: A, in: query, name: registry,
        type: string}
      - {description: A,
        in: query, name: organization, type: string}
      - {description: A, in: query, name: name, type: string}
      - {description: A, in: query, name: toolname, type: string}
      - {description: A, in: query, name: description,
        type: string}
      - {description: 'A', in: query, name: author,
        type: string}
      - {description: A, in: query, name: checker, type: boolean}
      - {$ref: '#/parameters/offset'}
      - {$ref: '#/parameters/limit'}
      responses:
        '200':
          description: A
          headers:
            current_limit: {description: A, type: integer}
            last_page: {description: A, type: string}
            self_link: {description: A, type: string}
          schema:
            items: {$ref: '#/definitions/Tool'}
            type: array
      summary: List all tools
      produces: [application/json;charset-utf-8]
      tags: [GA4GH]
produces: [application/json, text/plain, application/json;charset=utf-8]
swagger: '2.0'
tags:
- {description: A,
  name: A}
```
And it returns it failing because of bodyEncoding: base64
Now if I:
```
npm i -g dredd@4.7.0 --unsafe-perm
dredd thing.yaml https://dockstore.org:8443 -l fail -c false
```
It passes as expected

**Comment by honzajavorek** [comment]
Since we're talking about `transaction['real']['body']` response, it is important to know what exactly your API server is returning to Dredd. I suppose `transaction['expected']['body']` will match what's in your OpenAPI document.

Are you able to use `curl` or `httpie` to see what exactly the server returns for the `GET /api/ga4gh/v2/tools` request?

**Comment by garyluu** [comment]
curl -X GET "https://dockstore.org/api/api/ga4gh/v2/tools?limit=35" -H  "accept: application/json"

**Comment by honzajavorek** [comment]
@garyluu Is it possible the response body contains the `\ufffd` UTF-8 character for some reason?

https://github.com/apiaryio/dredd/blob/8e9035b/lib/performRequest.js#L150

```js
/**
 * @param {Buffer} body
 */
function detectBodyEncoding(body) {
  // U+FFFD is a replacement character in UTF-8 and indicates there
  // are some bytes which could not been translated as UTF-8. Therefore
  // let's assume the body is in binary format. Dredd encodes binary as
  // Base64 to be able to transfer it wrapped in JSON over the TCP to non-JS
  // hooks implementations.
  return body.toString().includes('\ufffd') ? 'base64' : 'utf-8';
}
```

**Comment by garyluu** [comment]
Ok, that might actually be it.  This is the problematic part of the json:
https://staging.dockstore.org/api/api/ga4gh/v2/tools/quay.io%2Fcancercollaboratory%2Fdockstore-tool-samtools-view

There's replacement chars for the >= sign

I'm content with this answer.  Thanks for your help.

**Comment by honzajavorek** [comment]
Great! I'm glad we could figure it out 👍
