### ISSUE TITLE
Define test values outside of contract file

### ISSUE THREAD

**Issue by stojsavljevic** [apiaryio/dredd#1269]
Hi, 

first of all, thanks for this great project.
I've just started to play with it so I might be missing something obvious. 
I searched reported issue but I couldn't find anything related.

**Is your feature request related to a problem? Please describe.**
The problem is that test values might be different across different environments.  So I need to change my contract file (its example values) based on environments I execute tests on. I need to avoid that by all means.

**Describe the solution you'd like**
I would like to define my test values outside of contract file (I'm using OAS) in some kind of properties file, e.g. `env-dev.properties`.

**Describe alternatives you've considered**
I can define test values in actual spec file but I would like to avoid changing my contract because of tests.

**Additional context**
With external properties file it will be possible to switch environments easily.

Thanks again and sorry if this has already been discussed.

**Comment by honzajavorek** [comment]
First of all, it might be good to look at https://github.com/apiaryio/dredd/issues/1103 in case one of your testing environments is production.

What you probably want is to use [hooks](http://dredd.org/en/latest/hooks/index.html), which allow you to modify the request sent by Dredd in any way you like. Let me know if you think it would solve your problem.

**Comment by honzajavorek** [comment]
Closing this now. @stojsavljevic I hope hooks were able to help you. If you need more guidance, let us know here or in a new issue. Cheers 🙂
