### ISSUE TITLE
Multipart request don't work correctly

### ISSUE THREAD

**Issue by igzsergiofernandez** [apiaryio/dredd#129]
I can not modify the request of dredd to attach a file, do not find a way to add a multipart correctly, try to include directly in the documentation blueprint the postman call with a correct boundary and data, but don't work, also I tried to test this example:
 +info[http://stackoverflow.com/questions/24207495/how-do-i-document-a-multipart-request-with-apiary]

My example:

==============================================================================

Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="hash"

8690d6c5efd5bc9433f550ff9209b7ba
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test_with_correct_data.csv"
Content-Type: text/csv

----WebKitFormBoundary7MA4YWxkTrZu0gW

==============================================================================

I would like to know what the web client that you use to make requests, because supertest, 
+info[https://www.npmjs.com/package/supertest] , for example, allows create multipart simply, and I could modify the request of transaction to do as I want.

I would like to know the current state of dredd for this and an answer to whether such a solution would be possible.

Thanks

**Comment by netmilk** [comment]
Thanks for the report, can you please [this](https://github.com/rikardq/dredd/commits/master) fork of Dredd, if it works as you wish?

**Comment by netmilk** [comment]
This topic is also mentioned here #74 and also in API Blueprint project  https://github.com/apiaryio/api-blueprint/issues/100 and here

**Comment by netmilk** [comment]
@igzsergiofernandez This is solved in #148
