### ISSUE TITLE
JSON schema draft 04 support

### ISSUE THREAD

**Issue by hamczu** [apiaryio/dredd#132]
When I try to use my JSON schema (version: draft-04) in dredd I got plenty of errors, i.e.: 
JSON schema is not valid! invalid type: array (expected boolean) at path "/required" 

So my questions are:
1. Can you please add clear statement about currently supporting JSON schema version?
2. Is there any chance to add support for 04 version?

If you are not aware why it is confusing - 3 and 4 versions of JSON schema have a lot of differences http://stackoverflow.com/questions/17205260/json-schema-draft4-vs-json-schema-draft3

btw. RAML format supports 04 version ;)

**Comment by hamczu** [comment]
Dredd relies on gavel.js validation and there is only draft 03 support there. But still explicit definition would be nice to have in docs.

**Comment by netmilk** [comment]
Hi, this was discussed [here](https://github.com/apiaryio/dredd/issues/91). There is work in progress on support for JSON schema v4 in Dredd (resp. Gavel). If you want to use it now, you can try [this fork of Gavel](https://github.com/marcelogo/gavel) linked with Dredd. It should work.

**Comment by netmilk** [comment]
@hamczu It's supported now, please update your Dredd.
