### ISSUE TITLE
Oauth

### ISSUE THREAD

**Issue by m1n0** [apiaryio/dredd#133]
Hi, is there a preferred way to sign requests with oauth? If not, it would be a great addition to dredd.

**Comment by netmilk** [comment]
Thanks for question, I'll add some example how to use oAuth with hooks.

**Comment by netmilk** [comment]
So, if you have access token  for the service under test, the situation is pretty easy. All you need is to add this access token as a header to all requests. It can be done: 

1. From the CLI with `-h` argument. If is this token confidential and you don't want to spread it, you can use your CIs environment variable.

```
$ dredd blueprint.h http://localhost -h "Authorization: Bearer tOkEn"
```

2. Programatically in `hooks`:
  - Create hook file `hook.coffee` with following code:

    ```coffee
    hooks = require 'hooks'

    # work around function to run some stuff before each hook
    hooks.beforeEach = (hook) -> 
      hooks.beforeAll (done) ->
        transactionKeys = Object.keys hooks.transactions
        for key in transactionKeys
          hooked = hooks.beforeHooks[key] || []
          hooked.unshift (transaction, done) ->
            hook(transaction)
            done()
          hooks.beforeHooks[key] = hooked
        done()

    hooks.beforeEach (transaction) ->
      transaction.request.headers['Authorization'] = "Bearer tOkEn"
    ```

  - run Dredd with this hook:

  ```
  $ dredd blueprint.md http://localhost --hookfiles=hooks.coffee
  ```

Advantage of the `hooks` approach is that you can dynamically retrieve the token from somewhere with code before setting it to the request. If you want to OAuth authenticate only some API calls, just use only `before` hook for some specific transaction. 

Please, let me know it this works for you.

Disclaimer: this is based on my limited knowledge of OAuth

**Comment by MariMax** [comment]
It works for me thanks for idea!

**Comment by netmilk** [comment]
@MariMax Thanks for letting me know. :candy:

In the  latest Dredd, there is a direct support for `beforeEach` hooks, so you can omit declaration of the `beforeEach` function when you are using hooks:

```
hooks = require 'hooks'
hooks.beforeEach (transaction) ->
  transaction.request.headers['Authorization'] = "Bearer tOkEn"
```
