### ISSUE TITLE
Cannot assign to read only property 'parent' of object '#<MemberElement>'

### ISSUE THREAD

**Issue by MCMic** [apiaryio/dredd#1360]
**Describe the bug**
dredd fails with this message:
`error: Unable to compile HTTP transactions from API description document '/home/mcmic/dev/fusiondirectory-plugins/webservice/html/openapi-test.yaml': Cannot assign to read only property 'parent' of object '#<MemberElement>': Cannot assign to read only property 'parent' of object '#<MemberElement`>'
It seems related to using the same parameter reference in two operations of the same endpoint.

**To Reproduce**
Minimal file to reproduce the problem so far:
```
openapi: 3.0.0
info:
  description: This is a openapi file
  version: 1.0.0
  title: DreddTest
  contact:
    email: contact@example.com
servers:
  - url: 'http://localhost/test/rest.php'
tags:
  - name: objects
    description: 'List, get, create, delete objects'
paths:
  '/objects/{type}':
    get:
      summary: Search objects
      operationId: listObjects
      tags:
        - objects
      parameters:
        - $ref: '#/components/parameters/type'
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create an object
      operationId: createObject
      tags:
        - objects
      parameters:
        - $ref: '#/components/parameters/type'
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      required:
        - message
      properties:
        message:
          type: string
  parameters:
    type:
      name: type
      in: path
      example: "user"
      required: true
      description: An object type
      schema:
        type: string
```

**Expected behavior**
No error.

**What is in your `dredd.yml`?**

```yaml
<empty>
```

**What's your `dredd --version` output?**

```
dredd v11.1.0 (Linux 4.9.0-9-amd64; x64)
```

**Does `dredd --loglevel=debug` uncover something?**
No

**Can you send us failing test in a Pull Request?**

**Comment by honzajavorek** [comment]
@kylef is this expected?

**Comment by kylef** [comment]
This is definately a bug in the parser, I've created https://github.com/apiaryio/api-elements.js/pull/228 which will fix it.

**Comment by MCMic** [comment]
I still get the same error with the last release (11.1.4)

**Comment by honzajavorek** [comment]
While it's fixed by @kylef, I believe there hasn't been a release of the OAS3 adapter yet, so it didn't bubble up to Dredd yet.

**Comment by honzajavorek** [comment]
I believe this gets finally released by https://github.com/apiaryio/dredd/pull/1394, in a moment.

**Comment by MCMic** [comment]
I confirm this is fixed, thanks
