### ISSUE TITLE
Multiple responses OpenAPI 3

### ISSUE THREAD

**Issue by tyurroma** [apiaryio/dredd#1362]
Hi,

Is it possible to provide several examples with OpenAPI 3 for one HTTP-method (GET for example) to check multiple responses: 200, 400, 404, 500?

**Comment by honzajavorek** [comment]
Sure, it is possible even with OpenAPI 2.

```yaml
responses:
  200: ...
  400: ...
  500: ...
```

**Comment by honzajavorek** [comment]
The spec is here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responsesObject

I hope this helps. I’m closing this now, but feel free to ask further if this doesn’t answer your question.

**Comment by tyurroma** [comment]
> The spec is here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responsesObject
> 
> I hope this helps. I’m closing this now, but feel free to ask further if this doesn’t answer your question.

I meant the possibility of dredd to check multiple different responses for a single URI endpoint. How can I specify request for each single response with OpenAPI 3 specification.

Below is the example of API blueprint. I would like to do the same with OpenAPI 3.
```
# Resource [/]
## Do Someting [POST]

+ request A

        A

+ response 200

        200

+ request B

        B

+ response 200

        400
```

**Comment by honzajavorek** [comment]
Oh, I'm sorry I was too fast with the comments, not thinking through your intention. The thing is with OpenAPI 2, Dredd marks all non-2xx responses as skipped. You can specify them, but if you want to have them tested, you need to write hooks to unskip them first.

Whether the same applies for OpenAPI 3 is unknown so far. The implementation is now so experimental that we haven't verified nor specified nor fixed the behavior yet. There is an issue for that: https://github.com/apiaryio/dredd/issues/1257
