### ISSUE TITLE
"--debug-brk" is not available during "test:debug"

### ISSUE THREAD

**Issue by artem-zakharchenko** [apiaryio/dredd#1393]
**Describe the bug**
When running `npm run test:debug` in NodeJs 8+ there is a deprecation warning shown, and no tests execution happens. 

**To Reproduce**
Execute the following command on NodeJS v8+ env:

```
npm run test:debug
```

See the following output:

```
(node:67325) Warning: "--debug-brk" is not available in Node.js v8.11.4; use "--inspect-brk" instead.
```

**Expected behavior**
* No deprecation warning is shown when running `npm run test:debug`
* `npm run test:debug` executes the tests

I believe `--debug-brk` was there to support NodeJS 6. However, its support has been recently dropped.

**What's your `dredd --version` output?**

```
11.2.4
```

**Comment by honzajavorek** [comment]
@artem-zakharchenko Is this still relevant? I never used `npm run test:debug`. I see it has moved here:

https://github.com/apiaryio/dredd/blob/88aeb2e5cdc6ee141bae6f02340b71c09ecd1e63/packages/dredd/package.json#L19

Up to you. We can remove that line. When I need to add options to testing, I do it using `--`:

```shell
$ npm test -- --grep="sanitation"
$ npm test -- --inspect-brk
```

See [docs](https://docs.npmjs.com/cli/run-script):

> As of npm@2.0.0, you can use custom arguments when executing scripts. The special option -- is used by getopt to delimit the end of the options. npm will pass all the arguments after the -- directly to your script...

**Comment by artem-zakharchenko** [comment]
@honzajavorek, thanks for the explanation. I've issued a pull request that removes the `test:debug` script. Please take a look when you have time.

**Comment by honzajavorek** [comment]
👍
