### ISSUE TITLE
Proposal: change how general errors are handled in the validation result

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#1445]
Currently Dredd saves the Gavel validation result on the `test` and `transaction` objects. It also adds a field called `general`, into which certain errors can be saved. E.g. when user manually fails the transaction in hooks, the `general` section is ensured on the object and the error message is added there:

https://github.com/apiaryio/dredd/blob/d5c595a1de6fc46accb5d36bc49b329c6779748c/lib/TransactionRunner.js#L341-L342

There are many situations like that. Then the `apiary` reporter wraps it up and sends over to the Apiary Test Reporting API: (...the line with `result: test.results` is the important one)

https://github.com/apiaryio/dredd/blob/fdb5e69ffd13ae4632bd37ed093787f12944d310/lib/reporters/ApiaryReporter.js#L273-L287

The resulting object sent over to the API then **currently** looks like this:

```js
{
    general: [
        { severity: 'error', message: 'something went wrong' },
    ],
    statusCode: {
        valid: false,
        kind: 'text',
        values: { expected: '202', actual: '405' },
        errors: [{
            message: "Expected status code '202', but got '405'.",
            values: { expected: '202', actual: '405' },
        }],
    },
    headers: {
        ...
    },
    ...
}
```

I don't think this is a great outcome of our changes. If nothing, I'd say the nested property should be called `errors` and the error objects should drop the `severity` key. But I think we can do even better. What about saving (and sending) something like this, when we're at it already?

```js
{
  valid: false,
  errors: [
    { message: 'something went wrong' }
  ],
  fields: {
    statusCode: {
      valid: false,
      kind: 'text',
      values: {
        expected: '200',
        actual: '404'
      },
      errors: [
        {
          message: `Expected status code '200', but got '404'.`,
          values: {
            expected: '200',
            actual: '404'
          }
        }
      ]
    },
    headers: {
      ...
    },
    ...
  },
}
```

Seeing the proposal above, you can notice following:

- The whole Gavel validation result is kept "as is" and sent over the API, including the top-level `valid` property
- The only change is that a new top-level property is added, `errors`, where fieldless errors related to general Dredd validation can be put (replaces the current `general.results` field)

Cons:

-   We already need to coerce several formats of this structure on the apiary.io side:

    1.  the old gavel format
    2.  ~new gavel format with `isValid` property for each field~

         > This could have never happened as this was present in Gavel from v6 to v7, but Dredd skipped this, upgrading from v5 directly to v7.

    3.  new gavel format with `valid` property for each field

    This would add a ~fourth~ third format to coerce from/to.

Pros:

- The gavel format would be used "as is", only with a little addition accommodating Dredd's needs

**Comment by artem-zakharchenko** [comment]
I think we shouldn't mix Gavel validation result and additional properties produced by Dredd. The `general` key is not related to the validation result, so it doesn't belong there. By settig it on the Gavel's output we create a false expectation that it's something produced by Gavel. It also makes working with this object more difficult, since now there should be logic to merge gavel result and `general`, watch out for key names conflicts (in case we decide to change gavel result in the future), and treat that one special property from stored Gavel output differently.

Instead, I suggest we treat `general` as an additional information on the test result Object. For example:

```js
resultData: {
  request: {},
  realResponse: {},
  expectedResponse: {},

  // if we are touching this I would rename properties to be more descriptive.
  // imho "resultData.result" gives me no information what kind of result is stored.
  // also I feel that the word "result" is overused in this object.
  validationResult: GAVEL_OUTPUT,

  // list of errors produced by a test run, not the validation itself.
  // we may use this property to store information that affects
  // the test run separately from the validation (like failure in hooks).
  runErrors: [],
}
```

This way the consumer decides what to do based on `validationResult` and `runErrors`. At the same time it's assured that one comes from Gavel, and another from Dredd. Also by separating them we can have different structures of errors in Gavel and in `runErrors` (I doubt Dredd would produce something like `runErrors[i].location.pointer`, for instance).

---

Thumbs up for removing the `severity` key.

**Comment by honzajavorek** [comment]
Just for the record, we internally agreed that `runErrors` can be called `errors`. The final proposal is:

```js
resultData: {
  errors: [ /* test-step-related errors produced by Dredd */ ],
  validationResult: { /* Gavel output, as is */ },
  request: {},
  realResponse: {},
  expectedResponse: {},
}
```

**Comment by honzajavorek** [comment]
The change needs to be:

- [ ] implemented on the Test Reporting API side, apiary.io needs to be able to consume such objects seamlessly
- [ ] updated in the Test Reporting API descriptions in this repo (*.apib files in the root) as well as on apiary.io side
- [ ] implemented in Dredd's `apiary` reporter and released

**Comment by honzajavorek** [comment]
We've done this, but forgot to close this issue.
