### ISSUE TITLE
Can't install dredd globally using npm

### ISSUE THREAD

**Issue by Haider8** [apiaryio/dredd#1509]
**Describe the bug**
I can't npm install dredd globally

**To Reproduce**
Steps to reproduce the behavior. How do you call the dredd command? Which command line options?
Try installing dredd using the command given in the documentation ```npm install dredd --global``` or ```sudo npm install dredd --global```

**Expected behavior**
Should have installed it properly

**What is in your `dredd.yml`?**
No need of it. I am just installing dredd.

```yaml
Not present
```

**What's your `dredd --version` output?**
```
dredd: command not found
```

**Does `dredd --loglevel=debug` uncover something?**
If you run Dredd with debugging output, do you see any interesting information relevant to the bug?
No

**Can you send us failing test in a Pull Request?**
We'll gladly help you to contribute; answering yes raises the chances the issue gets fixed.
Yes I would like to contribute

**Comment by Haider8** [comment]
This was the output of the command that I ran.
```
$ sudo npm install dredd --global
/usr/bin/dredd -> /usr/lib/node_modules/dredd/bin/dredd

> core-js@3.2.1 postinstall /usr/lib/node_modules/dredd/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> jsonpath@1.0.2 postinstall /usr/lib/node_modules/dredd/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

sh: 1: cannot create generated/aesprim-browser.js: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jsonpath@1.0.2 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the jsonpath@1.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/haider/.npm/_logs/2019-09-19T18_07_21_275Z-debug.log
```

**Comment by artem-zakharchenko** [comment]
Hello, @Haider8. Thanks for reporting this. I've tried to reproduce the issue, yet `dredd` has successfully installed globally. 

Judging from the error you've attached, there's still some permission missing:

```
sh: 1: cannot create generated/aesprim-browser.js: Permission denied
```

Could you please share your NodeJS and NPM versions, and the detailed error from `/home/haider/.npm/_logs/2019-09-19T18_07_21_275Z-debug.log` or similar log file produced after the global installation fails? Thank you.

**Comment by honzajavorek** [comment]
Hi @Haider8, were you able to resolve the problem in the end?

**Comment by Haider8** [comment]
Yes, @honzajavorek. Thank you for asking.

I have used this command to install it globally
```
sudo npm install dredd --global --unsafe-perm=true --allow-root
```

**Comment by honzajavorek** [comment]
Okay, I'm glad you've been able to resolve it. Thanks for mentioning the solution here as well, it can help others! 👍
