### ISSUE TITLE
Add query parameters to all transactions (e.g. api key)

### ISSUE THREAD

**Issue by demianh** [apiaryio/dredd#152]
Hi, is there a way to test API's which use API-Keys to authenticate users? i could not find a way to automatically add a parameter (e.g url?apikey=xxx) to each request. 

Thanks for any hints :)

**Comment by netmilk** [comment]
Hi,
there is not direct support for adding any query parameters to all transactions. Dredd supports adding headers to all transactions with `-h` argument, so this is a reasonable enhancement in my opinion.

The only way how is this possible, at this moment, is with use of `before` hooks with workaround discussed in #63. Just define hook to be executed before each transaction:

```coffee
hooks = require 'hooks'

hooks.beforeEach = (hook) -> 
  hooks.beforeAll (done) ->
    transactionKeys = Object.keys hooks.transactions
    for key in transactionKeys
      hooked = hooks.beforeHooks[key] || []
      hooked.unshift (transaction, done) ->
        hook(transaction)
        done()
      hooks.beforeHooks[key] = hooked
    done()

hooks.beforeEach (transaction) ->
  # add query parameter to each transaction here
  paramToAdd = "api-key=23456"
  if transaction.fullPath.indexOf('?') > -1
    transaction.fullPath += "&" + paramToAdd
  else
    transaction.fullPath += "?" + paramToAdd
```

Disclaimer: not tested, just an example for possible approach, if will not work for you let me know

**Comment by demianh** [comment]
works perfectly! thanks a lot :)

**Comment by netmilk** [comment]
Nice! :thumbsup:

**Comment by demianh** [comment]
This solution does not work with 0.4.6 release anymore. I am now going with the following code, although i do not fully understand what id does.. ;)

```coffeescript
hooks = require 'hooks'

hooks.beforeEach = (hook) ->
  hooks.beforeAll (done) ->
    transactionKeys = Object.keys hooks.transactions
    for key in transactionKeys
      paramToAdd = "apikey=abc"
      if hooks.transactions[key].fullPath.indexOf('?') > -1
        hooks.transactions[key].fullPath += "&" + paramToAdd
      else
        hooks.transactions[key].fullPath += "?" + paramToAdd
    done()

hooks.beforeEach (transaction) ->
  # this is needed, no idea why...
```

**Comment by kuba-kubula** [comment]
@demianh I'm looking into this regression. It looks like there are problems when we're passing all the context (`hook` especially) around.

**Comment by kuba-kubula** [comment]
I've fixed one possible regression that was triggered by our last release, also I've added a regression test about this feature request... So it shouldn't (™) happen again.

The code to use __hooks__ `beforeEach` might look like e.g.:

```coffee-script
hooks = require 'hooks'

# New hooks helper function
hooks.beforeEach = (hookFn) ->
  hooks.beforeAll (done) ->
    for transactionKey, transaction of hooks.transactions or {}
      hooks.beforeHooks[transaction.name] ?= []
      hooks.beforeHooks[transaction.name].unshift hookFn
    done()

hooks.beforeEach (transaction) ->
  # add query parameter to each transaction here
  paramToAdd = "api-key=23456"
  if transaction.fullPath.indexOf('?') > -1
    transaction.fullPath += "&" + paramToAdd
  else
    transaction.fullPath += "?" + paramToAdd
```

cc. @demianh
