### ISSUE TITLE
[question] Returning list of http requests instead of running them

### ISSUE THREAD

**Issue by arvenil** [apiaryio/dredd#155]
Hi,

I was thinking about running some benchmarks against api with e.g. [ab](http://httpd.apache.org/docs/2.2/programs/ab.html). In order to do that I would like to be able to get list of all routes/http requests with parameters that dredd runs. It could be in form of curl or json (maybe json would be better). So in other words, I would dredd to return http requests instead of running them. Any idea how I could achieve that?

**Comment by netmilk** [comment]
It's no problem with use of `beforeAll` hook.

1. Create a hook file e.g. in `hooks.coffee`
```coffee
hooks = require 'hooks'

hooks.beforeAll (done) ->
  requests = {}
  for name, transaction of hooks.transactions
    requests[name] = transaction.request

  console.log JSON.stringify requests, null, 2
```

2. Then dry-run Dredd with `-y` argument and suppress its output with `-q` argument and the hookfile
```
$ dredd blueprint.md http://localhost:3000/ -q -y --hookfiles=hooks.coffee
```

Please notice that if you want to debug hooks code, you have to remove `-q` from the command to see some output.

**Comment by arvenil** [comment]
It works! Thank you! :)

As a bonus question: any way to produce `curl` command line? :)

**Comment by netmilk** [comment]
@arvenil I'm afraid that you have to create some template by yourself :)
