### ISSUE TITLE
Optional fields for json responses

### ISSUE THREAD

**Issue by andrerigon** [apiaryio/dredd#162]
Hi,

is there a way to deal with optional fields inside a response? 

thks,

Andre

**Comment by netmilk** [comment]
Hi,

I'm sorry, but all keys given in JSON example for the response body are considered as required, so at this moment there is no other way than write a [custom JSON schema for the response in the blueprint](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-schema-section).

Adam

**Comment by netmilk** [comment]
But don't panic! :) There is upcoming [support for MSON in API blueprint]() format for describing body attributes. This will allow to mark particular body attribute / property / field as optional.

**Comment by netmilk** [comment]
Hey @andrerigon! MSON is supported since Dredd 0.5.1. I think it closes this issue. Did it help you?
