### ISSUE TITLE
Support for io.js and node 0.12

### ISSUE THREAD

**Issue by ofrobots** [apiaryio/dredd#169]
protagonist-0.19.0 (released Mar 27, 2015) adds support for node 0.12 and io.js. It would great to get dredd to update the dependency.

**Comment by netmilk** [comment]
Hi,

protagonist is updated in pending PR #167. It will be merged and released this week. I'm more curious if whole Dredd will work with on node 0.12 and io.js :). Dredd is tested only on node 0.10 at this moment, so it's good point. 

I'm renaming this issue.

Cheers!
Adam

**Comment by ofrobots** [comment]
:+1:

FWIW, dredd tests pass on my machine (OS X Yosemite) with the latest io.js (1.6.3). I didn't run them in a Vagrant virtual development environment though.

**Comment by cades** [comment]
node 0.12 +1

**Comment by netmilk** [comment]
@cades You can expect it very soon. It's WIP right now.

**Comment by kuba-kubula** [comment]
iojs and node 0.12+ support has been added in https://github.com/apiaryio/dredd/pull/179
dredd release incoming soon in your npm install

**Comment by dmtrs** [comment]
Any update on this one?

**Comment by netmilk** [comment]
Hi, this is released for more then month when this issue was closed. Just update your Dredd installation. 

Have a look on build targets in `.travis.ylm`:
```
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
```
