### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by berislavlopac** [apiaryio/dredd#175]
Hi, I've been trying to install `dredd` on a Ubuntu64 Vagrant box, but when the installation finishes (apparently with no errors apart from some deprecation warnings) the `dredd` command is not recognised. Any suggestions? Thanks!

**Comment by berislavlopac** [comment]
Update: managed to install `dredd`, but getting no response from it whatsoever. :disappointed:

**Comment by gonzalo-bulnes** [comment]
Hi @berislavlopac,

Did you install it _globally_? That requires the `-g` flag and `sudo` and is necessary every time you want to be able to use a NPM package from anywhere:

```bash
sudo npm install -g dredd
```



`

**Comment by berislavlopac** [comment]
Yep, in that second instance. I also installed `node` and `npm` separately. Right now any `dredd` command returns nothing at all, not even an error.

**Comment by gonzalo-bulnes** [comment]
Can you check where Dredd got installed?

```bash
which dredd
# should print /usr/bin/dredd
```

**Comment by berislavlopac** [comment]
I've got `/usr/local/bin/dredd` -- perhaps I should install as root rather than via `sudo`?

**Comment by gonzalo-bulnes** [comment]
On Ubuntu 14.04 Dredd is indeed installed in `/usr/local/bin/dredd` (I had checked a 12.01 installation earlier). That's doesn't seem to be the issue.

Could there be any reason for your the error output being redirected somewhere in that terminal?
I mean: `dredd 2>/dev/null` doesn't print anything at all, it's doing its job however.
Since you are running Dredd in a Vagrant box, maybe one of the box setting could be interfering?

**Comment by berislavlopac** [comment]
I'm afraid not, I've just installed `dredd` on a virgin box, with no additional provisioning, with the same results.

**Comment by netmilk** [comment]
I'm sorry about late response. Which version node.js do you use? Dredd currently works only with node.js v0.10.x

```
$ node -v
```

Issue about update to node.js 0.12 is here https://github.com/apiaryio/dredd/issues/169

**Comment by berislavlopac** [comment]
I see, this might be the cause -- so is the update mentioned in that issue coming soon?

**Comment by netmilk** [comment]
@berislavlopac I recommend to use [Node Version Manager (NVM](https://github.com/creationix/nvm) and install node 10.x as a workaround. Support for 12.x and io.js depends mainly on adding this support to dependant modules.

**Comment by netmilk** [comment]
@berislavlopac I just released new version of Dredd which should fix this issue. Can you please update Dredd and let me know whether it works for you?

**Comment by berislavlopac** [comment]
Thanks, I'll take a look next week!

**Comment by berislavlopac** [comment]
Just wanted to let you know that it works great now, thanks! :smiley:

**Comment by netmilk** [comment]
@berislavlopac Thanks for the information! I'm glad it works.
