### ISSUE TITLE
Error in compiling on Win8 LNK1104 cannot open file kernel32.lib

### ISSUE THREAD

**Issue by mjbza** [apiaryio/dredd#182]
Dear all,

I want to use drafter on win 8 but it has lots of problem when I want to compile it on windows.

1- First of all with VS Express you don't have Command line compiler. Then I needed to install the full version. See the error below:

    
    C:\Users\xxx\Documents\GitHub\drafter>vcbuild.bat
    creating config.gypi
    creating config.mk
    creating makefiles
    Warning: Missing input files:
    ./build\ext\snowcrash\..\..\..\ext\snowcrash\src\Version.h
    All OK.
    Project files generated.
    ERROR: Cannot determine the location of the VS Common Tools folder.
    Build skipped. To build, this file needs to run from VS cmd prompt.

After that I installed the Visual studio full version. And when I wanted to compile it by running vcbuild.bat in the step "8>InitializeBuildStatus: ClCompile" I got the following error:

    ---------------------------
    cl.exe - Systemfehler
    ---------------------------
    Das Programm kann nicht gestartet werden, da mspdb110.dll auf dem Computer fehlt. Installieren Sie das Programm erneut, um das Problem zu beheben. 
    ---------------------------
 It is in German but means can not find mspdb110.dll file. I found the file in the following location and add it to the system path to solve this problem:

    C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE

But at the moment there are 2 new problem that I couldn't solve them by adding anymore address to the path:

The first problem:
          
     10>c:\users\xxxi\documents\github\drafter\test\vendor\catch\include
    \internal\catch_console_colour_impl.hpp(29): fatal error C1083: Cannot o
    pen include file: 'windows.h': No such file or directory (..\test\test-m
    ain.cc) [C:\Users\xxx\Documents\GitHub\drafter\build\test-libdr
    after.vcxproj]

And the second one:

     9>LINK : fatal error LNK1104: cannot open file 'kernel32.lib'     [C:\Users\xxx\Documents\GitHub\drafter\build\drafter.vcxproj]

Please help me. I also asked this question with some pictures here:

http://stackoverflow.com/questions/29878710/how-to-install-apiaryio-drafter-on-windows-8

But no any useful answer come up!

Thanks in advance.

**Comment by netmilk** [comment]
Thanks for opening this issue. I would love to help you, but I'm little bit confused, because you're mentioning Drafter in the attached stackoverflow question, but this is a Dredd repository. Is your problem Dredd or Drafter related? If it's Drafter related, please refer to its [issues](https://github.com/apiaryio/drafter/issues).

**Comment by netmilk** [comment]
And just for information, Windows support for Dredd is WIP and it can be expected soon. It will include using [Appveyor](http://www.appveyor.com/) Ci for builds on Windows.

**Comment by mjza** [comment]
@netmilk 

Yes you are true.

Actually I mentioned this error in the following link at first:
    
    http://stackoverflow.com/questions/29878710/how-to-install-apiaryio-drafter-on-windows-8/29878878?noredirect=1#comment47905350_29878878
    
But someone with username @Almad asked me to write here as an issue, and unfortunately I didn't noticed that he suggested a wrong page to me.

@netmilk thanks for your reply.

**Comment by zdne** [comment]
@mjza please see my comment on SO – http://stackoverflow.com/a/29878878/634940
