### ISSUE TITLE
Unclear how to use an API token from Apiary

### ISSUE THREAD

**Issue by itsthatguy** [apiaryio/dredd#183]
Using a token generated at https://login.apiary.io/tokens the documentation is not clear in how to use this key.

I've followed the instructions via http://dredd.readthedocs.org/en/latest/usage/ for using the token, with no luck.

**Comment by netmilk** [comment]
Hi @itsthatguy,

thank you very much for the feedback. This feature you want to use is still in private beta in Apiary, and I agree that it can be confusing, so I removed it from the interactive setup in the latest release. If you want to use it just ping me at testing@apiary.io, I'll enable it to you and I'll be happy to give you further support.

Adam
