### ISSUE TITLE
Failed to modify transaction request body in hooks#before

### ISSUE THREAD

**Issue by ansonliao** [apiaryio/dredd#1846]
**Describe the bug**
In hooks.js, modify the request body failed

**To Reproduce**

**Expected behavior**

**What is in your `dredd.yml`?**
```yaml
color: true
dry-run: null
hookfiles: null
language: nodejs
require: null
server: npm start
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: api-description.yml
endpoint: 'http://127.0.0.1:3000'
```

**What's your `dredd --version` output?**
dredd v12.1.0 (Darwin 19.6.0; x64)

**Does `dredd --loglevel=debug` uncover something?**
The test passed, but the request body of JSON is out of expectation that not the modification version in hooks.js

**Can you send us failing test in a Pull Request?**
No.

**My `api-description.yml`**
```yaml
swagger: '2.0'
info:
  version: '1.0'
  title: Example API
  license:
    name: MIT
host: www.example.com
basePath: /
schemes:
  - http
consumes:
  - application/json; charset=utf-8
produces:
  - application/json; charset=utf-8
paths:
  /users:
    post:
      description: List all users
      produces:
        - application/json; charset=UTF-8
      consumes:
        - application/json; charset=UTF-8
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              userName:
                type: string
              firstName:
                type: string
              lastName: 
                type: string
            required:
              - userName
              - firstName
              - lastName
            example: {userName: 'Anson Liao', firstName: 'Anson', lastName: 'Liao'}
      responses:
        200:
          description: ''
          schema: 
            type: object
            properties:
              userName: 
                type: string
              firstName:
                type: string
              lastName: 
                type: string
            required:
              - userName
              - firstName
              - lastName
```

The `hooks.js` is according to the tutorial: https://dredd.org/en/latest/hooks/js.html#modifying-transaction-request-body-prior-to-execution
```javascript
var hooks = require('hooks')

hooks.before('/users > post > 200', (transaction, done) => {
  var requestBody = JSON.parse(transaction.request.body)
  requestBody['userName'] = 'Hello World!'
  requestBody['firstName'] = 'Hello'
  requestBody['lastName'] = 'World!'
  transaction.request.body = JSON.stringify(requestBody)
  done()
})
```

The API implementation in `NodeJS` is:
```javascript
app.post('/users', (req, res) => {
  let userName = req.body.userName
  let firstName = req.body.firstName
  let lastName = req.body.lastName
  res.sendStatus = 200
  res.send({
    userName: userName,
    firstName: firstName,
    lastName: lastName
  })
})
```

The test output in the request body and the response body:
![image](https://user-images.githubusercontent.com/6060224/99320368-649fce00-2863-11eb-94b8-7e5fb06f740e.png)

expects request body after modified in `hooks.js`:
```json
{
  "userName": "Hello World!",
  "firstName": "Hello",
  "lastName": "World!"
}
```

Could you help to advise how can I modify the request body in hooks?

Thanks very much!

**Comment by kylef** [comment]
I don't think the hook file is being used, check the line in the dredd configuration `hookfiles: null`, you'll want to replace that with the path to the hook file, such as:

```yaml
hookfiles: [hooks.js]
```

**Comment by ansonliao** [comment]
@kylef 
Thanks for your reply.
I execute the test command is: `dredd api-description.yml --hookfiles=./hooks.js`

Even I added the `hookfiles: hooks.js`, also the hooks.js doesn't work.
![image](https://user-images.githubusercontent.com/6060224/99322785-a1ba8f00-2868-11eb-9c81-e514a0d6b226.png)

**Comment by ansonliao** [comment]
@kylef 

I found a strange problem when executing the command: `dredd --names`.

My project is very simple, only one API: `/`.
app.js:
```javascript
var app = require('express')();

app.get('/', function(req, res) {
  res.json({message: 'Hello World!'});
})

app.listen(3000, () => {
    console.log('Server running on port 3000')
});
```

api-description.yml
```yml
swagger: '2.0'
info:
  version: '1.0'
  title: Example API
  license:
    name: MIT
host: www.example.com
basePath: /
schemes:
  - http
paths:
  /:
    get:
      produces:
        - application/json; charset=utf-8
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
```

dredd.yml:
```color: true
dry-run: null
hookfiles: ./hooks.js
language: nodejs
require: null
server: npm start
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: ./api-description.yml
endpoint: 'http://127.0.0.1:3000'
```

hooks.js
```javascript
const hooks = require('hooks');
const log = hooks.log

hooks.beforeAll((transaction, done) => {
  log('before all')
  done()
})

hooks.before('/url', (transaction, done) => {
  hooks.log('hooks before')
  done()
})
```

when executing the command: `dredd`, then the path `\' executed the test:
![image](https://user-images.githubusercontent.com/6060224/99758175-f7728e00-2b2b-11eb-879e-7d5c4be3e695.png)


when executing the command: `dredd --names`, then the path `\` is skipped:
![image](https://user-images.githubusercontent.com/6060224/99758274-2d177700-2b2c-11eb-958d-c5747c9f16b8.png)


and the before hook for the path `\' of `hooks.js` can't be executed in both commands.

could you kindly advise how to make the before hook works?

thanks.

**Comment by ansonliao** [comment]
@kylef 
I found the root cause of why the `before` of my `hooks.js` doesn't work, the problem is the transaction name is incorrect, as below.
![image](https://user-images.githubusercontent.com/6060224/99902663-6f8eae80-2cfa-11eb-831c-b773aec3f0e1.png)

the API path `\` with method `get` and response `200`, the transaction name in `before` of  `hooks.js` have to be `/ > GET > 200 > application/json; charset=utf-8`, otherwise the hook `before` will can be loaded for API path `\` with method `get` and response `200`.

So far I can't find the transaction name's rule/pattern document to reflect the paths of the OpenAPI 2 document, so if you have this guideline/document, please kindly help to share to me.
Thanks.
