### ISSUE TITLE
How to implement message signing?

### ISSUE THREAD

**Issue by LinusU** [apiaryio/dredd#189]
The api I'm currently developing requires that every api call be signed with a preshared secret. The signature looks a bit like this `HMAC(user ":" time ":" body, secret)`, it will be sent as a header `X-API-Sign`.

I also send over `X-API-Key` and `X-API-Time`. The time can only skew 5 seconds in either direction.

Including pre-calculated headers in the request would thus only be valid for 5 seconds. It would also be a pain to add it in for every request in the documentation.

I'm thinking that some kind of hook to let me sign the entire message would be the best option...

Do you guys have any thoughts on how I should do this?

-----

The problem that I have is that I can't find any way to add hooks from the javascript api. Since I have my own code that spins up a new server and database + populates it with data that script needs to pass the apiKey and apiSecret to the tests.

**Comment by netmilk** [comment]
@LinusU I think that you can solve this with `beforeEach` [hooks](https://dredd.readthedocs.org/en/latest/hooks/). 

Let's try something like this:

```javascript
var hooks = require('hooks');

hooks.beforeEach(function(transaction){
  var user = 'john.doe';
  var secret  = 'youS3cret';
  var time = new Date().getTime();
  transaction.request.headers['X-API-Sign'] = HMAC(user ":" time ":" transaction.request.body, secret)
  transaction.request.headers['X-API-Key'] = 'someTokenProbably';
  transcation.request.headers['X-API-Time'] = time;
})
```

If is the `X-API-Key` common for all API calls, you can pass it via CLI or JS API `header` option.

Unfortunately, there is no way how to add hooks code (or string with code) via JS API. Dredd uses `proxyquire` module for hooks loading which does not support loading from string. 

You will probably have to create separate hook file and it make part of the test suite and use JS API option `hookfiles` to point Dredd to its location.

> Disclaimer: Code is not tested, it's just a draft of possible solution.

**Comment by netmilk** [comment]
Please, if you can let me know whether it worked for you, I would appreciate it.

**Comment by LinusU** [comment]
Hmm, this is starting to look very much as a hack but here goes :)

It seems like the hook is never called, this is what I did:

1. Create a function to generate the contents of the hook file:
    ```javascript
    function generateSignFunction (env, apiKey) {
      function hook () {
        var hooks = require('hooks')
        var crypto = require('crypto')

        hooks.beforeEach(function (transaction) {
          var date = new Date()
          var userId = $$$USERID$$$
          var apiKey = $$$APIKEY$$$
          var apiSecret = $$$APISECRET$$$

          var hmac = crypto.createHmac('sha256', apiSecret)

          hmac.update(userId + ':' + date.toISOString() + ':' + transaction.request.body)

          transaction.request.headers['X-API-Key'] = apiKey
          transaction.request.headers['X-API-Sign'] = hmac.digest('hex')
          transaction.request.headers['X-API-Time'] = date.toISOString()
          transaction.request.headers['X-API-User'] = userId
        })
      }

      var str = hook.toString()
      var body = str.substring(17, str.length - 1)
      var result = body.replace(/\$\$\$([A-Z]+)\$\$\$/g, function (m, field) {
        switch (field) {
          case 'USERID': return JSON.stringify(env.userId)
          case 'APIKEY': return JSON.stringify(apiKey.key)
          case 'APISECRET': return JSON.stringify(apiKey.secret)
        }
      })

      return result
    }
    ```

2. Use that hook when instantiating Dredd.
    ```javascript
    var dredd = new Dredd({
      server: res.host,
      options: {
        path: ['Spec.apib'],
        hookfiles: ['sign.js']
      },
      hooksData: {
        'sign.js': generateSignFunction(res.env, res.apiKey)
      }
    })
    ```

3. Run it
    ```javascript
    dredd.run(done)
    ```

The output dosen't show the headers and the server responds that the api-key is missing.

**Comment by LinusU** [comment]
As a simple test I changed the hook file data to `throw new Error('TEST')`, this didn't trigger any error so I don't think that it's loading the hooks-file at all...

**Comment by netmilk** [comment]
This part of configuration is used only for [sandboxed hooks]() and it accepts a string, not a function. I'm sorry, it's not particularly mentioned in the documentation. I'll fix it.
```
  hooksData: {
    'sign.js': generateSignFunction(res.env, res.apiKey)
  }
```

You have to create a file on the filesystem and this `hookfiles: ['sign.js']` should point to that file relatively.

**Comment by LinusU** [comment]
It might not be all to clear but `generateSignFunction` returns a string, so I think that it should work.

**Comment by netmilk** [comment]
`hoksData` are not evaluated when the [sandbox](http://dredd.readthedocs.org/en/latest/hooks/#sandbox-mode) mode is not on.

**Comment by LinusU** [comment]
Hmm, ~~maybe that should be reflected better in the documentation~~ found it. I'm also looking at `Advanced Hook Examples > Modifying Transactions Prior to Execution` and it clearly has a bug.

> 
    var hooks = require('hooks');
    var before = hooks.before;
>
     before("Machines > Machines collection > Get Machines", function (transaction) {
      // parse request body from blueprint
      requestBody = JSON.parse(transasction.request.body);
>
      // modify request body here
      requestBody['someKey'] = 'someNewValue';
    });

`requestBody` is a newly created value so modifying that won't affect anything at all...

Back to the issue, `sandbox` isn't documented under `Configuration Object for Dredd Class` and setting `sandbox: true` inside of `options` dosen't seem to affect anything at all...

**Comment by netmilk** [comment]
Thanks a lot for this one. :) It's definitely an error in the documentation. I'll fix it. It should be:

```
var hooks = require('hooks');
var before = hooks.before;

 before("Machines > Machines collection > Get Machines", function (transaction) {
  // parse request body from blueprint
  requestBody = JSON.parse(transasction.request.body);

  // modify request body here
  requestBody['someKey'] = 'someNewValue';
  transaction.request.body = request.body;
});
```

**Comment by LinusU** [comment]
Actually, shouldn't the last line be:

    transaction.request.body = JSON.stringify(requestBody)

**Comment by netmilk** [comment]
You're right, It should. :smile:  As I said, I only drafted a possible solution. I apologise, I didn't test it at all.
