### ISSUE TITLE
Broken link for apiary reporter

### ISSUE THREAD

**Issue by jolleon** [apiaryio/dredd#190]
So far I was using the "public" reporter but I am now trying to make the test results private. I found my API key on the apiary site, and set both the `APIARY_API_KEY` and `APIARY_API_NAME` env variables. Dredd runs fine but the link it prints at the end doesn't work:

```
complete: Tests took 1768ms
complete: See results in Apiary at: https://app.apiary.io/fountain/tests/run/undefined
```

The link just goes to a page saying:

```
{
    error: true,
    message: "You can't add/view test report run for this suite."
}
```

I couldn't find any setting on the apiary site to enable or view test results. Is there something else I need to do on the dredd side to make this work?

If that helps, I tried to change the `APIARY_API_KEY` and got an error so looks like dredd is correctly calling apiary. But I tried to change the `APIARY_API_NAME` and dredd still ran fine (is that normal?) and the link at the end included the new (incorrect) api name.

**Comment by netmilk** [comment]
Hi @jolleon, it's awesome and I'm glad to hear that you're using Apiary reporter! Saving reports under a suite in Apiary is a feature in private beta at the moment in. Please send me your Apiary sign-up email address to adam@apiary.io and I can let you in.

**Comment by obihann** [comment]
@netmilk I'm also looking for this feature, could I possible be added to the beta?

**Comment by honzajavorek** [comment]
I think we don't have this bug anymore. The feature is not in beta anymore and for most people works as expected: http://dredd.readthedocs.io/en/latest/how-to-guides/#using-apiary-reporter-and-apiary-tests
