### ISSUE TITLE
Dredd fails when there is a space in the path (socket hang up)

### ISSUE THREAD

**Issue by milch** [apiaryio/dredd#201]
Hi,

I am currently using `dredd` to test an API that is written in `rails`. So far it was working very well, and I got everything working on my local machine. However, as soon as I ran it in our Jenkins job, I got this error: 

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: socket hang up
  at createHangUpError (_http_client.js:215:15)
  at Socket.socketOnEnd (_http_client.js:300:23)
  at Socket.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

I drilled it down to one API call, where I am using `multipart/form-data` to upload a 'file' to the server. 
Here is the relevant log from `rails`, although everything seems fine here:

```
Started POST "/users/me/profile_pic" for 127.0.0.1 at 2015-05-26 19:27:57 +0200
Processing by UsersController#upload_profile_picture as JSON
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x007fe97943fea8 @tempfile=#<Tempfile:/var/folders/8g/cwkjrryd04d9cgc4qmb7cj8c0000gn/T/RackMultipart20150526-85280-6r5qae>, @original_filename="profile_pic", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"users/me/profile_pic\"\r\nContent-Transfer-Encoding: binary\r\nContent-Type: image/jpeg\r\n">}
  Doorkeeper::AccessToken Load (0.2ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = ? LIMIT 1  [["token", "8af821042c679c0f8e62d3585ad95a28c0f178b3218276af8eb9dd63a4080a45"]]
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
   (0.1ms)  begin transaction
  SQL (0.8ms)  UPDATE "users" SET "profile_picture_path" = ?, "updated_at" = ? WHERE "users"."id" = 1  [["profile_picture_path", "profile_images/HCoR8Vy1aJhh7g.jpg"], ["updated_at", "2015-05-26 17:27:57.417906"]]
   (0.8ms)  commit transaction
Completed 201 Created in 30ms (Views: 0.5ms | ActiveRecord: 2.1ms)
```

And the corresponding portion of the `apiary.apib` file: 

`````` apib
### Change the profile picture [POST /users/me/profile_pic]

+ Request (multipart/form-data;boundary=------------nx-oauth2101027544)
    + Header

            Authorization: Bearer $myToken
    + Body

            --------------nx-oauth2101027544
            Content-Disposition: form-data; name="file"; filename="users/me/profile_pic"
            Content-Transfer-Encoding: binary
            Content-Type: image/jpeg

            data
            --------------nx-oauth2101027544--

+ Response 201 (application/json; charset=utf-8)
    + Body

        ```
            [true]
        ```

``````

I don't know if this is an issue with `dredd` or with my configuration, but the same data works on my local machine. Also, the output of the `jUnit` reporter stops after that error message and the closing `</testsuite>` is not inserted anymore. Is there maybe any way I can show the requests/responses or anything? I tried setting the log level to "silly", but that just adds `debug: Running hooks...` statements everywhere.

**Comment by netmilk** [comment]
HI @milch, thanks a lot for the report! I'm excited to see you using Dredd! 

It's interesting, that it's working on your local compute and it doesn't work in Jenkins. Does your Jenkins have an access to the internet? Can you please send me output from `dredd --version;  node -v` from both environments? Which version of rails do you use? I would love to replicate it. It would  be super awesome if you could create a stupid simple rails app with isolated controller for this specific problem, verify that it fails in Jenkins and send it to me.

**Comment by milch** [comment]
Yes, my Jenkins instance has internet access. Here's the output from your commands, it's the same on both machines (which are running OS X by the way):

```
$ dredd --version
dredd v0.5.4
$ node -v
v0.12.4
```

The `rails` version is `4.2.1` on both machines as well. 

I'm trying to isolate the issue right now, I'll report back again if I manage to create a working sample.

**Comment by netmilk** [comment]
Thanks a lot @milch for all the info and for you effort with isolating it! I'm looking forward to it!

**Comment by milch** [comment]
Alright, I found the issue! I still don't know if it has to do with dredd, however. It happens if there is a space somewhere in the directory name. I've already set up the repo at [milch/dredd-demonstration](https://github.com/milch/dredd-demonstration), so if you want to use that to check it out, run this: 

```
git clone https://github.com/milch/dredd-demonstration.git dredd\ demo
cd dredd\ demo
./run-dredd.sh
```

After that, `dredd` should crash with the same message I posted above.

**Comment by netmilk** [comment]
Hey @milch!  I'm sorry for responding this late. Thank you very much for all your time spent on this. You did an extra good job! It's incredible how you manage to debug this super obscure causation. I confirm it does the same for me. It's a valid bug.

**Comment by honzajavorek** [comment]
I was unable to to reproduce this with the latest version of Dredd. @milch Would you be able to try it out? I think this might be fixed already.

**Comment by milch** [comment]
@honzajavorek I think you're right, it seems like it's been fixed.

**Comment by honzajavorek** [comment]
Great! 🎉
