### ISSUE TITLE
Run Dredd's test suite on Windows

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#204]
Support for Windows with [AppVeyor](http://www.appveyor.com/) CI as mentioned in #126

**Comment by netmilk** [comment]
Interesting feedback is here: https://github.com/apiaryio/dredd/issues/126#issuecomment-125994574

**Comment by honzajavorek** [comment]
I created [Windows label](https://github.com/apiaryio/dredd/issues?utf8=%E2%9C%93&q=label%3AWindows+) which lists all related issues.

**Comment by honzajavorek** [comment]
Status:

### Open PRs

- [ ] https://github.com/apiaryio/dredd/pull/732 needs to be merged
- [ ] https://github.com/apiaryio/dredd/pull/730 needs to be merged

### Open, but failing PRs

- [ ] https://github.com/apiaryio/dredd/pull/734 needs to be polished and merged
- [ ] https://github.com/apiaryio/dredd/pull/733 needs to be polished and merged

### Subsequent works

- New branch `honzajavorek/consolidate-cli-tests-and-helpers` should be created with
    - 97ce68b
    - fea595d
    - 46c81b6
    - 150a4cc
    - bf7cbbd
    - 474d0a4
    - possibly also c91f70c8b76949105e3aacb9c1796443043f01c5

- New branch for scripts:
    - 80d371591676c6a4b84b9e9d932fd018b2b85597
    - 10af1dbd713ad54b01a43b4dd69ee108eedfe4a9

- New branch to introduce AppVeyor:
    - 2253019
    - b433f04fc162289e7a5f0a61e4e6f57ff207732d
    - e102c1b2c6d71f09dd1b73d7570ec2efdc55d98a
    - merge 03428ac527e993a41d9cbb7bea8b120587e9fdfe and 03428ac527e993a41d9cbb7bea8b120587e9fdfe somehow (mostly parts skipping some tests on Windows should be missing) and incorporate the missing changes

- Delete branches `honzajavorek/appveyor` and `honzajavorek/appveyor-badge`
