### ISSUE TITLE
Dredd Test Failed After Upgrade Version

### ISSUE THREAD

**Issue by muthuegrove** [apiaryio/dredd#206]
We have used the Dredd tool for our test case, After upgrade the version a96ac2abd25175aebe32353e163ac0a081d7a165 My test case is always returning the below response,

`fail: undefined duration: 1ms`

`fail: undefined duration: 2ms`

`info: Displaying failed tests...`

`fail: undefined duration: 13ms`

`fail: statusCode: Status code is not 'undefined'`

Please check the below link also,

Ref Link : https://app.apiary.io/public/tests/run/e7c457ed-f1f5-4ccf-ac9e-e7c13acdbe62

And also it is not connecting in my local server(127.0.0.1:8010) 
I have changed the configuration in dredd.yml,
My End Point is : 'http://127.0.0.1:8010'

**Comment by LinusU** [comment]
Are you sure that you upgraded from `0.5.4` to `0.5.5`? The only change between those versions was just some typos, I doubt that it affected your test results.

**Comment by muthuegrove** [comment]
Not only the upgrade the version, we tried to the dredd@0.5.4 but we got the same error. Exactly after jun1 only we got this error, Before that it's working fine. Also we have used the Travis CI, In that Travis CI Log Failed after Jun1.

**Comment by netmilk** [comment]
Hi @muthuegrove,

can you please upgrade to `0.6.0`? We froze some dependencies in last version. Can you please try it and let me know whether it works for you?

**Comment by muthuegrove** [comment]
Hi @netmilk ,
Thanks for your suggestion.
I have upgraded dredd@0.6.0 and the dredd tool is working fine.

**Comment by netmilk** [comment]
Hi, it's was a problem in the [async](https://github.com/caolan/async) library. It changed behavior in minor release and it wasn't limited in `package.json` to patchlavel updates only.
