### ISSUE TITLE
Broken markdown links in docs

### ISSUE THREAD

**Issue by philsturgeon** [apiaryio/dredd#208]
Not sure where to fix these or I'd do it myself. 

![screen shot 2015-06-02 at 12 16 08 pm](https://cloud.githubusercontent.com/assets/67381/7940797/21247e12-0921-11e5-8ee2-61ddbe3664e6.png)

**Comment by kuba-kubula** [comment]
@philsturgeon Thanks for finding this missing link. I'll fix that soon. It's in Dredds' docs folder.
