### ISSUE TITLE
creating dynamic variabls in postman while testing api

### ISSUE THREAD

**Issue by Abhinay12** [apiaryio/dredd#211]
i am currently testing Api in postman  i have one api 
/app/getHomework/student/$studentId/$dateAssigned
and these two variables $studentId and $dateAssigned  this will take values like

/app/getHomework/student/1/04-06-2015
/app/getHomework/student/2/06-06-2015
at one time we r sending only for student having id 1
at a time it is possible that lots of user can hit this api so i want to make it dynamically so that every user while hitting this url will get corresponding data

**Comment by netmilk** [comment]
HI @Abhinay12,

this is repository and issues tracker for Dredd - testing tool for API Blueprint, can you please be more specifc about how Dredd and Postman are connected?

**Comment by Abhinay12** [comment]
sorry sir ...........................

**Comment by netmilk** [comment]
@Abhinay12, btw did you find out how to do it in Postman? Is it possible?

**Comment by Abhinay12** [comment]
no sir i have not found it i am just finding solution for
this.........................

**Comment by netmilk** [comment]
@Abhinay12 Just for you information, this is exactly possible with use of Dredd [hooks](https://dredd.readthedocs.org/en/latest/hooks/) Please let me know in case of any questions. I'm happy to help.

**Comment by Abhinay12** [comment]
thanx sir but i have to do in postman if u have any solution then just
inform me................
