### ISSUE TITLE
Unwanted newline character in text/plain expected body.

### ISSUE THREAD

**Issue by chrislondon** [apiaryio/dredd#217]
I'm not sure if there's a way to avoid this but it looks like every time it compares a plain text response the expected body contains a newline character. I tried removing the line between the expected body and the next resource but it still had it.

Not a big deal, I wrote a little hook so I'm fine, but maybe there's a better solution?

```
/**
 * Remove trailing slash for text/plain responses
 */
hooks.beforeEach(function(transaction) {
    if (transaction.expected.headers['Content-Type'] === 'text/plain') {
        transaction.expected.body = transaction.expected.body.replace(/^\s+|\s+$/g, "");
    }
});
```

**Comment by netmilk** [comment]
Hi @chrislondon! 

This newline comes from the API Blueprint parser and I sill don't know if automatically strip it in Dredd or not. 

Thanks a lot for your code snippet I made it [part](http://dredd.readthedocs.org/en/latest/hooks/#remove-traling-newline-character-for-in-expected-plain-text-bodies) of Dredd's documentation.

**Comment by honzajavorek** [comment]
I guess this is related to #343 and https://github.com/apiaryio/dredd/issues/67. @netmilk I think we should decide whether this is a feature or bug and deal with it. To me, it looks like bug and should be either propagated to the parser or worked around in Dredd. It's very, very intuitive behavior and it even bitten myself in the past.

> **Note:** The docs @netmilk mentions above [moved here](http://dredd.readthedocs.org/en/latest/hooks-nodejs/#remove-trailing-newline-character-in-expected-plain-text-bodies).

**Comment by honzajavorek** [comment]
This is still an issue, but I decided to close duplicates.

- The main issue to track this problem is now: https://github.com/apiaryio/dredd/issues/67
- Workaround can be done by hooks: http://dredd.readthedocs.io/en/latest/hooks-nodejs/#remove-trailing-newline-character-in-expected-plain-text-bodies

**Comment by honzajavorek** [comment]
I'd like to address the problem. I added a comment explaining the situation: https://github.com/apiaryio/dredd/issues/67#issuecomment-287759448 If you have any ideas, I'd be very glad to discuss possible solutions.
