### ISSUE TITLE
Issue with an optional type (failing when the body does not include an object of the type)

### ISSUE THREAD

**Issue by yzaslavsky** [apiaryio/dredd#220]
Hi,
In my schema I have a type defined in the "definitions" section: 

```
...
"AnimalType": {
  "type": "object",
  "required": ["age", "name" ],
  "properties": {
    "age": {"type": "integer"},
    "name": {"type": "string"}
  }
}
...
```

I later on have a field at the "properties" section:

```
...
"animal":{ "$ref": "#/definitions/AnimalType" },
...
```

This field is not defined in the "required" part.

In the body I have payload that does not include objects of Animal and dredd fails,
with some indication that the Animal object is null.
Can you please elaborate on the issue and how can I resolve it?

**Comment by netmilk** [comment]
Hi @yzaslavsky!\

Thanks a lot for opening an issue here! It's super awesome you're using Dredd and you can provide this valuable feedback.

I'd love to help you, but I may need more information. Are you mentioning JSON schema generated from MSON or it's a schema authored by you? If you could send me the blueprint and the response body which is not passing the validation it would be very helpful.

**Comment by honzajavorek** [comment]
@yzaslavsky I'd love to solve this issue, but as @netmilk mentioned, we need more info here. Would you mind getting back to this and sharing something we could easily reproduce? Thanks!

**Comment by honzajavorek** [comment]
I'm sorry, it's been a long time and we haven't hear from you @yzaslavsky. I'm closing this, but still, if you feel like getting back, please do so and comment here.
