### ISSUE TITLE
Support for before validation hooks

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#221]
Some [workarounds and tricks](https://github.com/apiaryio/dredd/issues/194#issuecomment-112436147) needs the server response to be modified before the validation. It would be nice to extend the hooks interface with `beforeValidation` and `beforeEachValidation` methods and these hooks should be performed after "Receive HTTP response" and before "Run Gavel validation" steps of the [Dredd execution lifecycle](https://dredd.readthedocs.org/en/latest/usage/#dredd-execution-lifecycle).

**Comment by nevir** [comment]
Yes please! :)

**Comment by nevir** [comment]
Actually, not too bad! PR incoming once I write a few tests
