### ISSUE TITLE
Running dredd with --name flag on large .apib files causes RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by carrollgt91** [apiaryio/dredd#225]
Steps to reproduce:
- Download the following gist as an .apib file: https://gist.github.com/carrollgt91/11c2447410002be8d5b3
- Run `$ dredd /path/to/480_endpoints.apib api.datafi.local --names`

I think this happens because each step in iterating over the endpoints in that file is actually synchronous, which blows up the call stack when you hit the `async.mapSeries` call in the `run` method of [transaction_runner.coffee](https://github.com/apiaryio/dredd/blob/master/src/transaction-runner.coffee). That being said, I'm not sure that's the case; that's just what the stack trace leads me to believe.

Here's the [stack trace](https://gist.github.com/carrollgt91/b292db16a80b56248190) if you're interested.

**Comment by netmilk** [comment]
Hey @carrollgt91! Thank you very much for perfect report. I confirm I can replicate it and it's doing the same.

**Comment by petebrowne** [comment]
I've run into similar performance issues on large apib files. If I use a glob, performance is fine

``` bash
$ dredd apibfiles/**/* test.local --names
# ...
complete: 0 passing, 0 failing, 0 errors, 0 skipped, 269 total
complete: Tests took 86ms

# compiled.apib is the same set of apib files, concatenated into a single large file
$ dredd compiled.apib test.local --names
# never finishes...
```
