### ISSUE TITLE
Extract HTTP transaction compiling and canonical name matching to dedicated package

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#226]
As mentioned in #210 and #188 I porpose to extract following to npm package called `dredd-engine`:

1. Elaborate documentation and specification how [Canonical path convention](https://github.com/apiaryio/dredd/blob/master/docs/canonical-paths.md) workds

2. Extract logic compiling API Blueprint AST to HTTP transactions and logic for assiging Canonical paths
  - `blueprintAstToRuntime`
  - `TransactionRunner#getTransactionName`

3. Create method matching the canonical path back to the specific HTP Transaction

4. Crate a layer for backward compatibility matching paths without API Name or filename

**Comment by LinusU** [comment]
Cool! I'd be happy to help any way I can!

**Comment by netmilk** [comment]
Will be probably coupled with #227
