### ISSUE TITLE
Hooks language bridge codebase cleanup

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#235]
### todo
- refactor hooks running from "`sync`" into `"async"` callers (without `proxyquire`)
- `process.exit` (used at Hooks) should be some `runner` callback to bubble up through all the flow back to `dredd.run` callback
- DRY `hooks-worker` (factory for `...All` and `...Each`)
- Get rid with hard sleeps with `while true` with refactoring to async callbacks
- rename everywhere `worker` to `handler-client`
- add version to the interface
- configurable timeouts for connecting to the worker
- configurable HOOKS_TIMEOUT

**Comment by honzajavorek** [comment]
Resolved by #332.
