### ISSUE TITLE
Gracefully handle Ruby or Python hook handler crashes

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#238]
When hook handler crashes and Dredd started API server under test with `--server` switch this server keeps running in background after Dredd exit. This causes `EADDRINUSE` error in next Dredd run. As a workaround API server has to be killed by pid with `kill -9`.

**Comment by netmilk** [comment]
Adressed in #332

**Comment by honzajavorek** [comment]
#332 was merged :tada:
