### ISSUE TITLE
[discussion] [feature request] [help needed] generate JSON file with requests based on your own schema

### ISSUE THREAD

**Issue by hellboy81** [apiaryio/dredd#240]
I need to produce JSON output from API Blueprint with following schema:

```js
"ping": {
   "url": "/ping",
   "method": "GET",
},
"myEndpoint": {
   "url"; "/my/endpoint/{param0}"
   "method": "GET".
   "params": {
          "param0": 2
    }
}
```

Only request parameters are important.
What is the best way to implement this feature?

**Comment by netmilk** [comment]
Hi, can you please be more specific? What do you mean with implement? Write a API Blueprint?

**Comment by hellboy81** [comment]
- I have well-formed Apiary documentation in Markdown
- I have 3rd party test REST client that can loads requests from JSON settings file
- The `requests` object in JSON has following fomrat:

````json
"requests": {
   "endpointName": {
        "url": "/endpoint/{param0}/{param1}",
        "method": "GET" // Or POST, DELETE PUT, HEAD
        "params": { // Parameter values
             "param0": "param0value",
             "param1": "param1value"
         }
   }
}
```

- I should every time for each new service add requests by hand 
- As I mentioned  this job can be scripted
- As I mentioned this script can be/should be written in  `JavaScript`.
- As I mentioned  I should use  modules which can parse Apiary description? In need suggestions how can I implement this in best way.

**Comment by w-vi** [comment]
If I undrestand you correctly, you need to parse the Blueprint and get some json output describing the endpoints defined in the Blueprint, am I corect? If so than have look at https://github.com/apiaryio/protagonist

**Comment by honzajavorek** [comment]
@hellboy81 To implement what you described, you should use Protagonist or a different Drafter binding (depends on your programming language), parse your API Blueprint file and generate the JSON file. @w-vi pointed you to the right place. Feel free to [ask more on this topic on our Slack](https://apiblueprint-slack.herokuapp.com/).
