### ISSUE TITLE
Improve python support to take a WSGI handler

### ISSUE THREAD

**Issue by kylef** [apiaryio/dredd#245]
This is a small idea I had: I think it would be real nice to take the Python support/hooks one step further, and be able to define a WSGI handler either in the hook file or as an argument.

Perhaps here's an example of how this could work. You invoke dredd using `wsgi` as a URL scheme passing it the Python module which is a WSGI compliant application:

```shell
$ dredd apiary.apib wsgi://polls.wsgi --language python --hookfiles=./hooks*.py
```

Note, the user doesn't need to start their server and stop it after, instead this is handled by dredd since the server is [WSGI](http://wsgi.readthedocs.org/en/latest/) compatible. You don't have to build your own script or manage this yourself:

```shell
# Run the WSGI server (gunicorn)
$ PORT=8120 gunicorn polls.wsgi &
$ sleep 1  # wait for it to come online...
$ PID=$!

# Run dredd
$ dredd apiary.apib http://localhost:8120
$ RESULT=$?

$ kill -9 $PID
$ exit $RESULT
```

The same logic could be used for Ruby too, with Rack.

**Comment by w-vi** [comment]
@kylef sounds good we can discuss it next week in person as we've got some more plans with it.

**Comment by kylef** [comment]
Second though, although this would simplify the usage. It will no longer be testing using the real production HTTP server. The WSGI implementation may slightly differ against the production WSGI server used for the application in some way.

I think it's best to use the real production server in tests, therefore I'm going to close.
