### ISSUE TITLE
Fully working dredd-hooks-php implementation and running tests

### ISSUE THREAD

**Issue by ddelnano** [apiaryio/dredd#249]
So I have finally finished the working dredd-hooks-php implementation.  However, I have some issues with running the cucumber tests with the `bundle exec cucumber` command.  

The cucumber tests pass when running cucumber globally.
![screen shot 2015-07-20 at 1 59 15 pm](https://cloud.githubusercontent.com/assets/5855593/8783091/a6d8ed9a-2ee7-11e5-8b17-a8ce6d64eaf6.png)

However running `bundle exec cucumber` is killed before the test suite even begins running
![screen shot 2015-07-20 at 1 57 55 pm](https://cloud.githubusercontent.com/assets/5855593/8783107/bae79502-2ee7-11e5-8008-44296dde4d79.png)

I am not very familiar with cucumber or bundler (this is my first experience with both) so I am not sure what the issue is.  

Also when I the tests in Travis CI my tests pass except for the assertions that deal with output.  I am not sure what the issue is there either.

I know this is not a dredd issue but if anyone could offer some insight so I can get these tests passing on Travis (since they run great locally on my machine) I would greatly appreciate it so that others can have confidence that it works and can start using it.

**Comment by w-vi** [comment]
The output needs to be unbuffered, so maybe locally you have set it but on Travis it probably is buffered. Regarding the cucumber I don't know as I'm not familiar with it.

**Comment by ddelnano** [comment]
Yea in my php I use 

```php
fprintf(STDOUT, "text to output");
flush();
```

That worked for me locally but it does not on Travis.

**Comment by w-vi** [comment]
And what about using the `ini_set` as in:

``` php
ini_set('implicit_flush', 'on');
ini_set('output_buffering', 'off');
```

**Comment by ddelnano** [comment]
Just made that change and it still is failing.  I don't think its just related to the php buffer output.  For the features/execution_order.feature test the output actually comes from the javascript in dredd and not the php.  There are 3 tests where the output is dependent from my php code and one where it comes from dredd.

**Comment by ddelnano** [comment]
I realized I did not post a link to the repository.  It is [here](https://github.com/ddelnano/dredd-hooks-php)

**Comment by netmilk** [comment]
Hi @ddelnano, first of all, this all is absolutely awesome and it's definitely a Dredd issue! Huge respect! I'm super excited about it! I'll do my best to give you the best possible support. Just give me a while, I have to learn PHP a bit and make it work locally :)

Thank you very much for your excellent work!

**Comment by ddelnano** [comment]
I appreciate the help!  I came across dredd from using apiaryio at the new startup I am working at and once I saw how awesome it was I had to write php hooks.  Let me know if I can be of any help.  Some of my code is not as readable as I would like it to be which I definitely plan on making cleaner once these tests can pass on Travis.

**Comment by ddelnano** [comment]
I also opened an issue on [aruba's repository](https://github.com/cucumber/aruba/issues/296).  So far all the suggestions there have not worked but just wanted to post it here.

**Comment by ddelnano** [comment]
Finally have my tests passing!!!  Check out the issue I linked to above but it was due to the fact that the cucumber tests had the `@debug` on my `Scenario:` blocks and I was instructed by an aruba contributor to use `@announce` instead so that all the output would be flushed properly.  I will be improving the documentation of my repo and will be adding some runnable examples for people wanting to use it and then I will setup a pull request for the Dredd documentation to include my hooks handler.

**Comment by w-vi** [comment]
@ddelnano Wicked job man! We'll improve our test suite, thanks for all the work and feedback. I'm really happy that you've made it work!

**Comment by netmilk** [comment]
note: It was discussed here: https://github.com/cucumber/aruba/issues/296

Solution: use @announce instead of @debug tag in Aruba/Cucumber tests...
