### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by sdepold** [apiaryio/dredd#250]
Is there a way to limit the max amount of requests per seconds?

Edit: Our API implements rate limits and if the requests are coming in too fast, it will make dredd (correctly) complain about the status code not matching the expected value but 429.

**Comment by w-vi** [comment]
Hi @sdepold you can easily do the throttling for yourself using the `before_each` hook and pause the progress there for a bit to achieve the needed rate.

**Comment by sdepold** [comment]
:clap: got it working like this (not very smart but works):

```js
'use strict';

var hooks = require('hooks');
var delay = 1000/6.0; // Allow 6 reqs/sec

hooks.afterEach(function (transaction, done) {
  setTimeout(done, delay);
});
```

Ideally one would calculate the time that the tests were taking in the current second but this is quick and dirty solution which works good enough for me :dancer:
