### ISSUE TITLE
Support pending for not implemented methods

### ISSUE THREAD

**Issue by yniche** [apiaryio/dredd#252]
We have an API spec which we want a freelancer to implement. It'd be very handy if there would be a(n easy) way to mark tests as pending. Say like:

``` ruby
NOT_IMPLEMENTED_APIS = {'post' => ['/me', '/sth', '/sth-else'], 'put' => [...]}
NOT_IMPLEMENTED_APIS.each do |method, paths|
  paths.each do |path|
    send(method) do
      status 404 # Send 404 and a custom header to make Dredd skip it.
      header 'X-Not-Implemented' => true
    end
  end
end
```

Referring to https://twitter.com/ntmlk/status/623935271541866496

Cheers!

**Comment by honzajavorek** [comment]
@netmilk I'd personally like to see "not implemented yet" flag right in the API Blueprint syntax, but making it happen in Dredd would allow us to support it immediately and in all formats (thinking about Swagger).

**Comment by RobbieMcKinstry** [comment]
Any update on this?

**Comment by honzajavorek** [comment]
I'd say the best way to achieve this at the moment is to use [Dredd's hooks](http://dredd.readthedocs.io/en/latest/hooks/) and to mark transactions for not implemented endpoints as skipped.

```js
hooks.before('Machines > Machines collection > Get Machines', function (transaction, done) {
  transaction.skip = true;
  done();
});
```

Feel free to comment here if this won't solve your particular problem.
