### ISSUE TITLE
[feature request]  Allow Hooks to Be Configured For Database Transactions

### ISSUE THREAD

**Issue by ddelnano** [apiaryio/dredd#257]
As it currently stands, I need to configure a `beforeEach` and `afterEach` hook in order to run everything in a transaction and roll it back so I have a clean database for each run.  I think it would be useful to have the Hooks be able to accept a database connection that implements an interface for running or rolling back a migration (That is how it would work in PHP anyway).  

So essentially you would set the `Hooks::$databaseConnection` property in the hooksfile like so:

```php
<?php

use Dredd\Hooks;

$db = new DatabaseConnection(.....);
Hooks::setDatabaseConnection($db);

// Hook declarations come after
```

And the Hooks.php

```php
public static function setDatabaseConnection(DatabaseInterface $db)
{
   // set property
}
```

This `DatabaseConnection` class would implement an interface that would expose a `startTransaction` and `rollback` method and from the `Dredd\Runner` side of things make a check on the `beforeEach` and `afterEach` hook to see if it is configured and if so start and rollback the transactions as necessary.

This way for each project I am on I don't need to configure this `beforeEach` and `afterEach` hook boiler plate.

I have done very little Python and Ruby programming, however, I do know that they don't have interfaces but from the PHP side thats a basic overview.  Not exactly sure what the Ruby or Python way of dealing with this is, but if people like this idea I would like to give the implementation a try in the Python or Ruby as well as the PHP side of things.

**Comment by ddelnano** [comment]
Ah forgot about the nodejs hooks but same holds true.

**Comment by netmilk** [comment]
Hi @ddelnano,

may I know why did you close this? It's not valid any more?

**Comment by ddelnano** [comment]
I was assuming when I opened this that there was going to be some discussion about the request.  The reason I say that is cause I didn't want to incorporate something into the PHP hooks unless the others all had the same feature set.

**Comment by ddelnano** [comment]
Do you agree with my thinking on that the hooks should have the same feature set???  I also closed it because to allow transactions would be hard cause it would require the user to provide the same database connection that their application is using and so it causes potential issues where users would be seeding the database in one connection and the web app would be accessing the database in another.  Allowing an interface to run migrations before and after tests would be a much better option since it wouldn't require the same connection and still allow the database to be clean between tests.

**Comment by luizs81** [comment]
I'm facing the same situation in Python side. 
Yeah, it's 2016 now but still waiting for this feature.

**Comment by honzajavorek** [comment]
> the hooks should have the same feature set

My opinion would be that all hooks implementations should conform to the same base feature set and it's up to their authors to try out innovations. If those innovations prove to be useful, they can get incorporated back as a standard feature in Dredd (one thing which pops in my head would be `*` operator in transaction names to pattern-match them in hooks, which I think is a great idea and should be part of the transition to https://github.com/apiaryio/dredd/issues/227).
