### ISSUE TITLE
Test only status codes

### ISSUE THREAD

**Issue by Mkax** [apiaryio/dredd#259]
Hello,
I would like to test only status codes on some resources, is it possible? If not, could it be possible in future? I didnt find any information about it.

For example: I have some image and I dont want to check its content, I need compare only status code.

Thank You

**Comment by honzajavorek** [comment]
@Mkax I think it should be possible to achieve that with Dredd Hooks: http://dredd.readthedocs.org/en/latest/hooks/ Do hooks solve your issue or do you think this would make more sense as a built-in Dredd feature?

**Comment by honzajavorek** [comment]
I'm sorry, actually, I'm not completely sure this can be implemented with hooks :confused: This is, I believe, related to https://github.com/apiaryio/dredd/issues/253.

**Comment by honzajavorek** [comment]
@Mkax You can achieve this now thanks to https://github.com/apiaryio/dredd/pull/648. You can use Dredd for testing as usual, but then have an `afterEach` hook, which will remove all test results from the [transaction.test](http://dredd.readthedocs.io/en/latest/data-structures/#transaction-test) object, except of those related to status codes.

Closing this, but if you have any questions or if you bump into any problems when implementing the hooks, let us know, please!
