### ISSUE TITLE
Dredd fails silently when blueprint is malformed

### ISSUE THREAD

**Issue by icambridge** [apiaryio/dredd#261]
```
# User Authentication [GET v6/auth]

Logins an a user and gives them an accesss token

+ Request (application/json)

        {
            "username": "test.user@foodpanda.com",
            "password": "test"
        }

+ Response 200 (application/json)

        {
            "access_token": "RandomStringForAuth"
        }
```

Will not get parsed as a test and this fails silently so you don't know why. Where it's clearly the lack of a in the URL. Took me a while to find out the issue.

**Comment by w-vi** [comment]
Hi @icambridge thanks for the report, we'll have a look into this. Cheers.

**Comment by honzajavorek** [comment]
@icambridge Could you please try this again with the latest version of Dredd? Thanks!

**Comment by honzajavorek** [comment]
Thanks for the report! I think this should be handled by the API Blueprint parser, [Drafter](https://github.com/apiaryio/drafter/). IMHO similar issue to https://github.com/apiaryio/drafter/issues/350. I'll file a corresponding issue there.

**Comment by honzajavorek** [comment]
I'd say this has been resolved - https://github.com/apiaryio/drafter/issues/350#issuecomment-253344849 Please report back if it's not the case.
