### ISSUE TITLE
HTTP `LINK` and `UNLINK` is not sorted

### ISSUE THREAD

**Issue by obihann** [apiaryio/dredd#267]
According to the dredd documentation sorted is missing support for `LINK` and `UNLINK`:

```
 --sorted, -s         Sorts requests in a sensible way so that objects are not
                       modified before they are created. Order: CONNECT,
                       OPTIONS, POST, GET, HEAD, PUT, PATCH, DELETE, TRACE.
```

I suggest the following, and I would be willing to help implement it:

```
 --sorted, -s         Sorts requests in a sensible way so that objects are not
                       modified before they are created. Order: CONNECT,
                       OPTIONS, POST, GET, HEAD, PUT, PATCH, LINK, UNLINK, DELETE, TRACE.
```

**Comment by w-vi** [comment]
@obihann good suggestion I'll leave the decision on @netmilk how to approach this including the #268 issue as they are related and may be solved in one go.

**Comment by obihann** [comment]
@w-vi @netmilk thanks for the reply, glad you agree its a useful idea. Honestly this is causing me a bit of trouble on a current project and I'm more than likely going to have to fork dredd and implement my own solution, so if you would like we can discuss the best way to handle this and then when I make the change I can submit a pull request.

**Comment by w-vi** [comment]
@obihann Can we postpone the discussion to the next week when @netmilk is around?

**Comment by obihann** [comment]
That works for me. I'm currently skipping my tests that relate to LINk and UNLINK, however they can stay in that state for a few more days haha.

**Comment by obihann** [comment]
Just a poke to bring this back on the table. @w-vi @netmilk
