### ISSUE TITLE
hooks-worker-client should sent all events.

### ISSUE THREAD

**Issue by snikch** [apiaryio/dredd#271]
Making this a separate issue, split from #269.

> The before, beforeValidation and after hooks aren't submitted when using the hooks-worker-client . Since the internal hook handlers are just like the ones required in the end handler, you can't even add a hooks.before(fn()) callback, because it expects a name (whereas the names are defined in the compiled binary logic). To get around this, and send the events, I've duplicated the beforeEach, beforeEachValidation and afterEach callbacks, but changed the event name in each. This way it's up to the hook handler to decide whether the event is relevant (i.e. there is a named callback available). Another approach to this would be to advise the hook handlers to consume the beforeEach event twice, once for everything, and then consider it the same event for before - except the documentation clearly states it should expect a separate before event.

If you check out where the worker client adds the callbacks to the `hooks` value, you'll see that no callbacks are supplied for `before`, `beforeValidation` or `after`.

https://github.com/apiaryio/dredd/blob/master/src/hooks-worker-client.coffee#L117

This is because those callbacks need a name to match against, however those `events` still need to be sent to a hook handler to determine if it has its own matching callback for the specific event name.

In my code, I added a `before` event, by duplicating `beforeEach` and changing the event name. It then became the responsibility of my hook handler to determine if the event `name` matches the callback registered for the `before` event.

``` coffee
hooks.beforeEach (transaction, callback) ->
  # avoiding dependency on external module here.
  uuid = Date.now().toString() + '-' + Math. random().toString(36).substring(7)

  # send transaction to the handler
  message =
    event: 'before' # Note this is `before` not `beforeEach` now
    uuid: uuid
    data: transaction

  …

  emitter.on uuid, messageHandler
```

**Comment by w-vi** [comment]
I see, well currently there is a `beforeEach` event only and the handlers, looking at `ruby`, `python` and `PHP` are handling this event twice, basically run all `beforeEach` hooks and then the `before` hooks for given transaction name. It is confusing and should be properly documented. if you look at the ruby  hook handler or python it is clear. The information that each event is fired it is directed to end users, that is for those writing the hooks not the handlers. Thanks a lot for pointing this out.

**Comment by snikch** [comment]
Will dredd handle two responses to an event with the same UUID?

**Comment by w-vi** [comment]
Not at the moment, in case of the `beforeEach` and `before` they will do their thing on the `transaction object` and then  the handler returns that object to dredd. Is there a use case where this is a big issue?

**Comment by snikch** [comment]
Oh, I misinterpreted how you described  the Ruby client handling the request. So they run both callbacks and then return the single response - got it. I can do this in the Go handler too.

Cheers

**Comment by honzajavorek** [comment]
@w-vi @snikch I'm not sure what's the action point here. Is there anything for Dredd to fix or change?

**Comment by w-vi** [comment]
@honzajavorek Actually it was a question how handlers should handle `before` and  `beforeEach` there is no actionable item here or if any then  better docs :)

**Comment by honzajavorek** [comment]
OK, good! 👍

**Comment by honzajavorek** [comment]
Reopening this. This backfired with Rust hooks and it needs to be properly documented and explained.
