### ISSUE TITLE
Any way of being able to set the HOOK_TIMEOUT value?

### ISSUE THREAD

**Issue by earnaway** [apiaryio/dredd#272]
Is there any chance that the HOOK_TIMEOUT constant in hooks-worker-client could be part of a config, as some tests may take more than 5 seconds and therefore fail. I'd like a param to be optional that the HOOK_TIMEOUT could be set.

**Comment by w-vi** [comment]
As you can see itis fixed now, but definitely should be part of user input. Are your hooks doing so much that 5 sec is blocking you now? Sorry fort he inconvenice it is still a beta feature which needs polishing but thanks for your input, we really appreciate it. Just out of curiosity which hook handler are you using?

**Comment by earnaway** [comment]
Thanks for your reply. Even though it's a beta feature, it's still very useful and happy to use and test it out. Do you say it's fixed now? Not sure if I can see the changes? I'm using php hook handler, but my slow test is one which registers a user on facebook, processes it and then deletes the user. Sometimes that takes a bit more than 5 seconds and fails. All other hooks are super quick. For us, the abilty to set the timeout would be excellent.

**Comment by w-vi** [comment]
I meant fixed as in it is a constant now but will be made as part of user input. Quick hack to as workaround is to fork dredd and use your fork until it is fixed, which i suppose will be quite soon as we are going to improve the hook handlers within next month. I'll let you know.

**Comment by earnaway** [comment]
Sounds great, thanks. Will fork it for now until the update is pushed. Appreciate it.

**Comment by netmilk** [comment]
Hi @earnaway,

I made it part of requirements for hooks handler client in Dredd refactoring in #235.

**Comment by hobofan** [comment]
+1 I am also currently using a fork with an increased timeout. My ruby hooks have to load a whole Rails environment to correctly do database cleaning between tests.

**Comment by netmilk** [comment]
Big move forward - addressed in #332, implementation in CLI will come in one of next releases.

**Comment by honzajavorek** [comment]
This issue is going to be addressed in #382.
