### ISSUE TITLE
Empty value not valid for optional number

### ISSUE THREAD

**Issue by tomec-martin** [apiaryio/dredd#276]
When I define in blueprint empty optional parameter, e.g.:

    + nextId (number, optional)

blueprint compilation fails on error:

    error: Runtime compilation error: URI parameter 'nextId' is declared as 'number' but it is a string.

I suppose that empty value should be considered as valid for optional number.

**Comment by w-vi** [comment]
In `dredd` it is expected to have some sample value, otherwise the value is `null` and that's not a number.
