### ISSUE TITLE
'rerun' flag for transaction in hooks

### ISSUE THREAD

**Issue by hobofan** [apiaryio/dredd#277]
Sometimes it is desireable to test the exact same transaction (same request) under different circumstances (the first time the requested resource exists in the database, the second time it doesn't).

I think the easiest way to achieve this would be a `rerun` flag similar to the existing `fail` and `skip` flags, which when set to `true` will result in the transaction being sent once more. This flag in combination with a request stash would make rerunning tests under different circumstances trivial.

P.S: I feel like I've already seen this feature request before but I wasn't able to find it after a long search.

**Comment by honzajavorek** [comment]
@hobofan With the same request and different state of the server, shouldn't your API return different responses for each of the transactions? I struggle to find a good use case for this.

E.g. when I request a user representation while user with given ID doesn't exist, I expect the response to be 404. When I request a user representation while user with given ID does exist, I expect the response to be 200. For that you'd need to have two different transactions specified in your API description and no `rerun` would help.

**Comment by honzajavorek** [comment]
I think I understand better now. Workaround: In the `beforeAll` hooks, one should be able to re-order the transactions array / duplicate transactions in the array. I don't think the re-run is worth a separate feature if we keep the possibility to modify the transactions array according to one's needs in before hooks. @hobofan What do you think?

**Comment by honzajavorek** [comment]
Closing in favor of https://github.com/apiaryio/dredd/issues/995
