### ISSUE TITLE
Dredd support for ajv JSON Schema Validator

### ISSUE THREAD

**Issue by abtris** [apiaryio/dredd#278]
ajv implements full JSON Schema draft 4 standard:

all validation keywords
full support of remote refs (remote schemas have to be added with addSchema or compiled to be available)
support of circular dependencies between schemas
correct string lengths for strings with unicode pairs (can be turned off)
formats defined by JSON Schema draft 4 standard and custom formats (can be turned off)
ajv passes all the tests from JSON Schema Test Suite (apart from the one that requires that 1.0 is not an integer).

https://github.com/epoberezkin/ajv

**Comment by honzajavorek** [comment]
Closing in favor of https://github.com/apiaryio/gavel.js/issues/90. It's Gavel.js improvement request rather then something Dredd should care about.
