### ISSUE TITLE
--server-wait is needed if running dredd multiple times

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#279]
### Steps to reproduce

1. Run dredd. Everything works properly.
2. When first run finishes, press arrow up in your terminal and run dredd again.
3. Tests will not fail, but they start with strange error message.

```
$ dredd --hookfiles *-hook.*
Configuration dredd.yml found, ignoring other arguments.
Starting server with command: npm start
Waiting 3 seconds for server command to start...

> plutonium@0.0.1 start /Users/honzajavorek/Workspace/plutonium
> node ./bin/server


Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Server.listen (/Users/honzajavorek/Workspace/plutonium/node_modules/restify/lib/server.js:398:32)
    at Object.<anonymous> (/Users/honzajavorek/Workspace/plutonium/bin/server:6:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/honzajavorek/.nvm/v0.10.39/bin/npm" "start"
npm ERR! node v0.10.39
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! plutonium@0.0.1 start: `node ./bin/server`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the plutonium@0.0.1 start script 'node ./bin/server'.
npm ERR! This is most likely a problem with the plutonium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/server
npm ERR! You can get their info via:
npm ERR!     npm owner ls plutonium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/honzajavorek/Workspace/plutonium/npm-debug.log
info: Beginning Dredd testing...
...
```

### Expected behavior

There should be no error messages during start of tests.

### Workaround

If `--server-wait` without value is added, it gives no errors. I do not understand why.

```
$ dredd --hookfiles *-hook.* --server-wait
Configuration dredd.yml found, ignoring other arguments.
Starting server with command: npm start
Waiting NaN seconds for server command to start...
info: Beginning Dredd testing...
...
```

------

The same behavior was reported also by @JackuB.

**Comment by w-vi** [comment]
Strange, obviously the system still has the port taken so it looks like it is not cleaned up properly when dredd finishes, I'll have a look how the server is terminated.

**Comment by honzajavorek** [comment]
I reported this as Dredd user. Now I've became Dredd maintainer, so I can fix it for myself :smile: However, haven't seen this for a while and I have no clue now how to reproduce this. If @JackuB doesn't have any idea and also doesn't experience this problem anymore, then this was probably fixed as side-effect of some other work on Dredd (most likely #332) and I'm closing this.

(Yeah, I copied this text from https://github.com/apiaryio/dredd/issues/280, but I really mean it!)

**Comment by w-vi** [comment]
Yes, I guess it was fixed by #332 as it has cleaned up the shutdown

**Comment by adriano-di-giovanni** [comment]
I'm not sure it's related but when you start a Node.js server using something like `npm start`, the process being shutdown is not the real Node.js process but the one that spawned it. That's why, in my case, the EADDRINUSE error occurs during any subsequent run of Dredd

**Comment by honzajavorek** [comment]
Might be related. That would point to a bug in Dredd's process-killing mechanics, because as far as I remember, Dredd should aim for killing the whole subprocess tree and making sure nothing survives.

(Hmm, that sentence sounds a lot like something from the [Dredd universe](https://en.wikipedia.org/wiki/Judge_Dredd_(character)) 🤔 😅 💥 )

**Comment by adriano-di-giovanni** [comment]
@honzajavorek need more details?

**Comment by honzajavorek** [comment]
I don't work on Dredd anymore, unfortunately, but the code responsible for terminating children starts on this line:

https://github.com/apiaryio/dredd/blob/b191dc0d665db441c216b84042b3b3677aba6d3e/packages/dredd/lib/childProcess.js#L60

To solve this problem, one would need to reproduce the issue locally and then go through this code and find flaws in tracking down and killing all related processes. The tests are here:

https://github.com/apiaryio/dredd/blob/b191dc0d665db441c216b84042b3b3677aba6d3e/packages/dredd/test/integration/childProcess-test.js#L61
