### ISSUE TITLE
Dredd works for an API, but then hangs on a different blueprint

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#280]
### Steps to reproduce

1. I have a working test suite with Dredd. It uses `dredd.yml` and is ran simply as `dredd` from command line. The build finishes correctly. The blueprint describes API as it's implemented. Mistakes in implementation are reported by Dredd.
2. I change the blueprint for a completely different one, which describes different API, thus many of endpoints are not implemented in the tested application. They should return 404 though.
3. I run `dredd` again.
4. It successfully tests the root of the app, but then hangs for very long time when trying to test the other endpoints. It timeouts with message that it was not able to connect to the server.

```
fail: GET / duration: 47ms
error: POST /parser duration: 120053ms
error: Error connecting to server under test!
error: POST /parser duration: 120098ms
error: Error connecting to server under test!
error: POST /parser duration: 120102ms
error: Error connecting to server under test!
error: POST /parser duration: 120096ms
error: Error connecting to server under test!
error: POST /parser duration: 120091ms
error: Error connecting to server under test!
error: POST /parser duration: 120101ms
error: Error connecting to server under test!
error: POST /parser duration: 120073ms
error: Error connecting to server under test!
error: POST /parser duration: 120084ms
error: Error connecting to server under test!
fail: POST /composer duration: 20ms
```

### Expected behavior

Dredd should not fail to connect to the server. It should just say the response does not comply to the API description, but it should normally continue, without any long waiting. The tested app is apparently running (note that the first and last request from sample I posted above gets tested and doesn't timeout). The app gets also successfully tested by Dredd with completely the same settings, just with different blueprint - the only change I need to make is to change name of blueprint file in `dredd.yml`, nothing else. That makes me think the problem is not in the app itself, but either in the other API Blueprint (which I doubt) or in Dredd.

-------

I can show a sort-of-minimal example of this behavior in person, but I cannot post it here as it is not open source. @JackuB has seen this to happen on both my computer and in a CircleCI build, so I have a whitness ;-)

**Comment by honzajavorek** [comment]
I reported this as Dredd user. Now I've became Dredd maintainer, so I can fix it for myself :smile: However, haven't seen this for a while and I have no clue now how to reproduce this. If @JackuB doesn't have any idea and also doesn't experience this problem anymore, then this was probably fixed as side-effect of some other work on Dredd and I'm closing this.

**Comment by philsturgeon** [comment]
I am currently having this issue, and @netmilk has been looking at it on http://slack.apisyouwonthate.com. No idea wtf is going on, we're both stumped.
