### ISSUE TITLE
Strange race condition in the Dredd class integration tests

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#282]
On Mac and probably on Linux as well in test **"Dredd class Integration when using reporter -r apiary in DREDD_REST_DEBUG mode with custom apiaryApiKey and apiaryApiName"** `before all` hook. Done callback is never called. It seems some event is not processed. When the event loop is woke up by the timeout it starts magically work. See the workaround [here](https://github.com/apiaryio/dredd/blob/netmilk/race-condition-bug/test/integration/dredd-test.coffee#L168).
 
Branch testing only this bug: https://github.com/apiaryio/dredd/tree/netmilk/race-condition-bug
Failng build: https://travis-ci.org/apiaryio/dredd/builds/81374746

**Comment by honzajavorek** [comment]
This could be related: https://travis-ci.org/apiaryio/dredd/jobs/98479333 Seems like something in the first test fails to finish/close and then it blocks port for several subsequent tests.

**Comment by netmilk** [comment]
Should be hopefully adressed in #332. It's an issue with idle event-loop. I and @w-vi  we didn't manage to debug it, but little `setTimeout` is succesfully waking the event-loop.

**Comment by honzajavorek** [comment]
I haven't seen this for a while. Closing. If it appears again, let's re-open this.
