### ISSUE TITLE
Upcoming support for NodeJS 4.x.x ?

### ISSUE THREAD

**Issue by nick13jaremek** [apiaryio/dredd#290]
Hi there,

We just switched from NodeJS 0.12.3 to version 4.2.1 and the `dredd` module crashes due to the unsupported Node version. Therefore we cannot use this wonderful tool of yours :(

In the docs I see the paragraph saying that *support for node.js 4.x.x is on the way*.

I was wondering if you have defined a release date for this feature, or if you could provide more info about it.

Thank you in advance!

**Comment by w-vi** [comment]
@nick13jaremek Hi, the dependency causing the crashes was fixed last week, so I suppose next week there will be dredd release supporting Node.js 4.x.x

**Comment by nick13jaremek** [comment]
@w-vi Awesome! Thank you for the prompt reply

**Comment by w-vi** [comment]
@nick13jaremek : I have some bad news, the dependency `protagonist` is not fully working yet (some features are not there for 4.x.x yet), we have to wait until that gets fixed completely. So this week there will definitely not be any dredd release for 4.x.x

**Comment by nick13jaremek** [comment]
@w-vi No worries! :D For now we just switched off `dredd` from our project until the `dredd` release for NodeJS 4.x.x. Thank you for the feedback on the work you're doing!

**Comment by lulco** [comment]
some good news about this issue?

**Comment by w-vi** [comment]
@lulco see the note in the README

**Note**: Dredd works smoothly with node.js 5.x.x, 4.x.x, 0.12.x, 0.10.x, and iojs v2.x.x.

**Comment by lulco** [comment]
Ah, great. Thank you
