### ISSUE TITLE
Nested objects output: "undefined":null

### ISSUE THREAD

**Issue by jamesramsay** [apiaryio/dredd#291]
I'm having an issue where JSON generated from MSON containing of nested objects described using MSON are being output incorrectly when via dredd and in the Apiary interface.

We've upgraded the lions share of our API documents to MSON and I am now focussing on converting the POST and PATCH body to MSON rather than raw JSON. In doing this I ran into an error where an array of objects which contain objects resulted in the output `"undefined":null` for the content of the inner object. Our application returns an error response and the test fails despite the MSON example being constructed to pass.

Example API blueprint is below using MSON showing differing behaviours depending where the MSON is included in the API blueprint, along with a comparison of the generated by JSON.

**EXAMPLE A:** renders correctly

```apib
FORMAT: 1A
# Example
## Example [/example]
+ Attributes
    - actions (array)
        - (object)
            - action: add (string)
            - data (object)
                - productId: 779 (number)

### Example [GET]
+ Response 200 (application/json)
    + Attributes (Example)
```

**EXAMPLE B:** renderes incorrectly

```apib
FORMAT: 1A
# Example
## Example [/example]
### Example [GET]
+ Response 200 (application/json)
    + Attributes
        - actions (array)
            - (object)
                - action: add (string)
                - data (object)
                    - productId: 779 (number)
```
**OUPUT:** comparison of A and B

```diff
{
  "actions": [
    {
      "action": "add",
      "data": {
-        "productId": 779
+        "undefined": null
      }
    }
  ]
}
```

**Comment by jamesramsay** [comment]
To clarify, this example is the simplest form I could replicate the issue with. In practice this is a problem when trying to provide multiple examples of POST request/responses for more complex interactions.

Referencing the example above, we'd like to have multiple examples depending on the action specified. In our API, `action` is an enum with 5 different values and the contents of the `data` object vary action to action.

**Comment by ecordell** [comment]
I can confirm this as well. Here's an example from our blueprint:

```
    + Attributes
        + subject (object, required) - The subject the widget is displaying.
            + id: `us_1003830829_9vg5jyuwn4w04d8_7b5eaeb` (string, required)
            + type: `provider` (enum[string], required)
                + Members
                    + `organization`
                    + `office`
                    + `provider`
```

Output:

```json
{
  "subject": {
    "id": "us_1003830829_9vg5jyuwn4w04d8_7b5eaeb",
    "type": null
  }
}
```

Unnested `enum[string]` types render fine.

**Comment by honzajavorek** [comment]
I haven't had time to try to reproduce this, but it seems to me like a Drafter issue. There has been some fixes recently, so if anyone can confirm whether this bug report is still valid with the latest Dredd version, that would be awesome. Maybe we can already close this.
