### ISSUE TITLE
Error installing globally on node 5.1 due to Protagonist not compiling

### ISSUE THREAD

**Issue by amuino** [apiaryio/dredd#298]
I'm using `nvm` on OS X El Capitan.

I'm able to install on node version `0.12.x`. <del>I'm also able to install locally (without `-g`) using node 5.1.0 (which is weird).</del> (did not check the output properly, fails also locally)

Although this might be Protagonist's fault, I can install [aglio](https://github.com/danielgtaylor/aglio) on 5.1.0 without issues (uses `protagonist@1.2.0`, whereas dredd tries to install `protagonist@0.20.1`).

```
$ nvm --version
0.27.1
$ npm -v
3.3.12
$ node -v
5.1.0
$ npm install -g dredd
...
(lots of compiler errors)
...
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/amuino/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/amuino/.nvm/versions/node/v5.1.0/bin/node" "/Users/amuino/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/amuino/.nvm/versions/node/v5.1.0/lib/node_modules/dredd/node_modules/protagonist
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:protagonist@0.20.1 protagonist@0.20.1 install: `node-gyp rebuild`
npm WARN install:protagonist@0.20.1 Exit status 1
```

**Comment by kylef** [comment]
Hi @amuino, please see the comment at https://github.com/apiaryio/dredd/issues/292#issuecomment-160549620:

> We need protagonist to generate JSON Schema and that's the bit I'm now working on, basic stuff is already working...

Closing this issue since it's already tracked by #284 and #292. For now, dread requires node 0.12.x.

**Comment by 3dtomato** [comment]
Does Dredd works on Node 5.x.x / 4.x.x  or works only on Node 0.12.x?

On the Dredd Readme.md you have `Note: Dredd works smoothly with node.js 5.x.x, 4.x.x, 0.12.x, 0.10.x, and iojs v2.x.x.`

So where is the truth?

**Comment by kylef** [comment]
@3dtomato As of Dredd 1.0.2, Node 4 and 5 is supported like mentioned in the README.

**Comment by 3dtomato** [comment]
I am not able to install Dredd on Windows 10 + Python 2.7 + Visual Studio 2015 + NVM Node 5.3.0 or 4.2.3.   It is working for me only on Node 0.12.9. 

Whats are the requirements for Dredd 1.0.2? Is there any detailed installation manual?

**Comment by kylef** [comment]
@3dtomato What exactly is the build error you are facing? Can you paste the logs?

**Comment by netmilk** [comment]
@3dtomato If is this an issue feel free to reopen.

**Comment by kylef** [comment]
@3dtomato opened #318, so gonna close this one again.
