### ISSUE TITLE
Tests are failing on Master! Any help appreciated.

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#300]
Something went wrong after merging green PR containing only documentation for Go language hooks and master branch turned red in Travis for node .10 build. Builds for node 0.12 and io.js are passing. It's probably caused by some change in Travis environment.  I managed to isolate the problem in tests and it's in the HEAD in this [branch](https://github.com/apiaryio/dredd/tree/netmilk/godocupdate).

@w-vi Would you mind sharing here your experience with debugging and isolating the problem as well?

**Comment by w-vi** [comment]
@netmilk after bit of fiddling I have come to conclusion that it is one of the dependencies causing it. So I would have a look on what dependency has been updated in the last commits and see if downgrading it would help

**Comment by netmilk** [comment]
@w-vi Thanks for the info!

**Comment by WVI** [comment]
I get the feeling you sent this to me by mistake. I'm a game developer :v

On Thu, Dec 3, 2015 at 5:17 PM, Adam Kliment <notifications@github.com>
wrote:

> Something went wrong after merging green PR containing only documentation
> for Go language hooks and master branch turned red in Travis for node .10
> build. Builds for node 0.12 and io.js are passing. It's probably caused by
> some change in Travis environment. I managed to isolate the problem in
> tests and it's in the HEAD in thus branch
> <https://github.com/apiaryio/dredd/tree/netmilk/godocupdate>
>
> @wvi <https://github.com/wvi> Would you mind sharing your experience with
> debugging and isolating the problem as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apiaryio/dredd/issues/300>.
>



-- 
Thanks for your time~

**Comment by netmilk** [comment]
@wvi I'm sorry! I misspelled @w-vi.

**Comment by WVI** [comment]
Haha, no prob. That's what happens when your username is three letters.

On Tue, Dec 8, 2015 at 5:28 AM, Adam Kliment <notifications@github.com>
wrote:

> @wvi <https://github.com/wvi> I'm sorry! I misspelled @w-vi
> <https://github.com/w-vi>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apiaryio/dredd/issues/300#issuecomment-162842269>.
>



-- 
Thanks for your time~

**Comment by w-vi** [comment]
fixed in #309 it was dependecies ...
