### ISSUE TITLE
node exit with pointer error 

### ISSUE THREAD

**Issue by macdao** [apiaryio/dredd#301]
It happens when multi apib files is given.

the cmd is `node_modules/.bin/dredd "apib2/*" localhost:3000/ --names`
and the output is

```
info: Beginning Dredd testing...
info: my project > hello > /api/hello > GET
info: my project > world > /api/world > GET
complete: 0 passing, 0 failing, 0 errors, 0 skipped, 2 total
complete: Tests took 7ms
node(66075,0x7fff7d014000) malloc: *** error for object 0x100b0bb00: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    66075 abort      node_modules/.bin/dredd "apib2/*" localhost:3000/ --names
```

files in apib2 folder is `a.md`

```
FORMAT: 1A

# my project

# Group hello

## /api/hello

### GET

- Request

    - Headers

            X-Requested-With: XMLHttpRequest

- Response 401 (application/json;charset=UTF-8)
```

and `b.md`

```
FORMAT: 1A

# my project

# Group world

## /api/world

### GET

- Request

    - Headers

            X-Requested-With: XMLHttpRequest

- Response 401 (application/json;charset=UTF-8)

```

I'm using OS X El Caption 10.11.1
brew installed node012 which is 0.12.9 and tried 0.10.41 and nvm 0.12.0 and nvm 0.12.9
The error appears 50%, not every time.

Hope I can get help, thanks

**Comment by w-vi** [comment]
@macdao thanks a lot for the report, we'll have look into it.

**Comment by honzajavorek** [comment]
@macdao Could you please verify this still doesn't work with the newest Dredd?

**Comment by honzajavorek** [comment]
@macdao I didn't hear back. Try to install Dredd using `npm install dredd --no-optional` to [avoid compilation](http://dredd.readthedocs.io/en/latest/installation/#compiled-vs-pure-javascript). I'm curious whether you'd experience the error as well. Closing for now, feel free to get back and re-open the issue.
