### ISSUE TITLE
Receiving after transaction hook twice (ruby)

### ISSUE THREAD

**Issue by amuino** [apiaryio/dredd#302]
In some examples, our ruby hooks are triggered with the `after` hook callback twice. It does not seem to happen for every transaction, but reliably happens in at least one of them (as a side note, we use the after hook for database cleanup, which raised an error the second time).

I have explored the `dredd_hooks` gem but couldn't find any issues there. It is receiving the event twice. I have not been able to debug dredd code beyond the `hooks-worker-client` which looks ok.

If there's anything I can do to help fixing this issue, let me know.

**Comment by w-vi** [comment]
Hi @amuino thanks for the report, we haven't seen this before, can you provide us with a minimal example having this behavior?
Sometimes it gets a bit confusing as you get `after` and `after_each` hook calls with the same transaction, isn't this by chance the case?

**Comment by amuino** [comment]
In my debugging, I got two `after` events (no `after_each`) with different event ids and start_at, but was unable to build a minimal example sorry.

Only _strange_ thing that I can think of is that the hooks usually time out on the first example. Also, we are running dredd from `dredd.yml` with two blueprint files.

**Comment by netmilk** [comment]
Hey @amuino! Is this still an issue? Did you figure out?

**Comment by amuino** [comment]
Sorry for the very delayed response. I have just tested latest dredd on node 5.6 and I couldn't reproduce it. I'm closing the issue.

**Comment by netmilk** [comment]
@amuino Thanks for the info! :)
