### ISSUE TITLE
Make wait time for client TCP server configurable

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/dredd#328]
...because some times it is not able to start within 1 second.

**Comment by netmilk** [comment]
If you mean configurable wait time to spawn the hook handler, it's a WIP feature. Comming soon. :)

**Comment by XVincentX** [comment]
I mean the ability to configure the time to wait between process spawn and hooks execution.

Basically, [this number](https://github.com/apiaryio/dredd/blob/master/src/hooks-worker-client.coffee#L74).

**Comment by honzajavorek** [comment]
The link isn't pointing to the original place anymore. @XVincentX which one was it?

```
HOOK_TIMEOUT = 5000

CONNECT_TIMEOUT = 1500
CONNECT_RETRY = 500
AFTER_CONNECT_WAIT = 100

TERM_TIMEOUT = 5000
TERM_RETRY = 500
```

**Comment by netmilk** [comment]
@honzajavorek I think it's `CONNECT_TIMEOUT`. Right @XVincentX ? The worker client is trying to reconnect to the server repeatedly until this times out.
