### ISSUE TITLE
'Native thread-sleep not available' warning

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#335]
Taken from https://github.com/apiaryio/dredd-hooks-python/issues/10. With node v0.10.25:

```
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/local/lib/node_modules/dredd/node_modules/spawn-sync/error.log for more details
```

I guess this is related to version of node installation. Dredd warns it will be slower, but that's all and it can confuse people, who do not work in node as in primary environment. We could probably mitigate the warning by using [spawn-sync](https://github.com/ForbesLindesay/spawn-sync), [try-thread-sleep](https://www.npmjs.com/package/try-thread-sleep), but I'm not that skilled in this regard to be able to decide without a bit of investigation.

**Comment by netmilk** [comment]
+1 for shielding Dredd users from this infomration. But please note, this is only a Node,js < 0.12 issue.

**Comment by honzajavorek** [comment]
This is now "solved" by https://github.com/apiaryio/dredd/issues/660.
