### ISSUE TITLE
Segfault on OSX on master after merging PR with `protagonist` 1.2.3.

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#342]
Verified on node v0.12.2 and v0.12.2, release postponed, possible roll-back.
```
$ dredd
Configuration dredd.yml found, ignoring other arguments.
info: Using apiary reporter.
warn: Apiary reporter environment variable APIARY_API_KEY or APIARY_API_NAME not defined.
Starting server with command: node app.js
Waiting 3 seconds for server command to start...
Listening on http://localhost:3000
Segmentation fault: 11
```

**Comment by w-vi** [comment]
might be related https://github.com/apiaryio/drafter/issues/207, any particular blueprint causing the SIGSEGV?

**Comment by w-vi** [comment]
So it is the same issue as mentioned above, please follow the https://github.com/apiaryio/drafter/issues/207 issue for updates.

**Comment by w-vi** [comment]
@honzajavorek @netmilk please verify that new protagonist 1.2.5. is fixing for you as well.

**Comment by honzajavorek** [comment]
Thanks, Dredd@v1.0.4 released!
