### ISSUE TITLE
Hello world example failing on comparing body

### ISSUE THREAD

**Issue by mypark** [apiaryio/dredd#343]
Trying the hello world example with express.js and seeing this failure in the test even though the body text/html response matches

```
info: Beginning Dredd testing...
fail: GET /message duration: 56ms
info: Displaying failed tests...
fail: GET /message duration: 56ms
fail: body: Real and expected data does not match.

request: 
body: 

headers: 
    User-Agent: Dredd/1.0.2 (Darwin 15.2.0; x64)

uri: /message
method: GET


expected: 
headers: 
    Content-Type: text/html; charset=utf-8

body: 
hello

statusCode: 200


actual: 
statusCode: 200
headers: 
    x-powered-by: Express
    content-type: text/html; charset=utf-8
    content-length: 5
    etag: W/"5-XUFAKrxLKna5cZ2REBfFkg"
    date: Wed, 06 Jan 2016 13:36:46 GMT
    connection: close

body: 
hello
```

**Comment by w-vi** [comment]
@mypark very often there are some whitespace characters somewhere which are causing this seemingly matching responses ... there is an issue #305 on this topic already.

**Comment by mypark** [comment]
I checked the white space in the response and in the blueprint files, and there were no extra white spaces in the response, and none in the bluprint file.  Does dredd add some white spaces after the parsing of the blueprint file?

**Comment by netmilk** [comment]
Hey @mypark,

Would you mind trying it again with an Apiary reporter and send me the link to the report? I'll try to investigate and help you.

**Comment by mypark** [comment]
it doesn't ever get to the report, it just hangs after it makes the request.

**Comment by mypark** [comment]
this is the blueprint

```
# GET /message
+ Response 200 (text/html; charset=utf-8)

        hello
```

and this is the node.js code

```
app.get('/message', function (req, res) {
  res.send('hello');
});
```

neither of which have a trailing space after the hello

**Comment by TheKiteEatingTree** [comment]
I had a very similar issue.  Added a newline to my response and it validated correctly.  That may not be the greatest solution though.

**Comment by honzajavorek** [comment]
Could https://github.com/apiaryio/dredd/issues/305 be related?

**Comment by honzajavorek** [comment]
I was able to reproduce this problem. It indeed looks like some issue with whitespace. Simple response with `text/plain` content type doesn't pass Dredd test. If changed to something with JSON content type, it passes.

**Comment by honzajavorek** [comment]
This is still an issue, but I decided to close duplicates.

- The main issue to track this problem is now: https://github.com/apiaryio/dredd/issues/67
- Workaround can be done by hooks: http://dredd.readthedocs.io/en/latest/hooks-nodejs/#remove-trailing-newline-character-in-expected-plain-text-bodies

**Comment by honzajavorek** [comment]
I'd like to address the problem. I added a comment explaining the situation: https://github.com/apiaryio/dredd/issues/67#issuecomment-287759448 If you have any ideas, I'd be very glad to discuss possible solutions.
