### ISSUE TITLE
Dredd hangs when running against an aps.net 5 MVC 6 web api example

### ISSUE THREAD

**Issue by mypark** [apiaryio/dredd#344]
It spins up the api instance with `dnx web` and sends a request to it, but dredd seems to hang and never returns after the api response.  How can I debug to see what's going on?

```
Configuration dredd.yml found, ignoring other arguments.
Starting server with command: dnx web
Waiting 3 seconds for server command to start...
Hosting environment: Production
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Beginning Dredd testing...
info: Found Hookfiles: hooks.js
hook: before all
hook: before each
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://localhost:5000/message  
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method Foo.Controllers.HelloController.Get with arguments () - ModelState is Valid'
info: Microsoft.AspNet.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value Microsoft.AspNet.Mvc.ActionContext.
info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
      Executed action Foo.Controllers.HelloController.Get in 0.0082ms
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0321ms 200 text/plain; charset=utf-8

```

the asp.net 5 mvc6 controller
```
   [Route("/message")]
    public class HelloController : Controller
    {
        [HttpGet]
        public string Get()
        {
            return "Hello World!";
        }
    }
```

**Comment by XVincentX** [comment]
Hey!
Would you mind sharing with me the aspnet project (with .json file as well) and the APIBlueprint you're actually using?

**Comment by mypark** [comment]
here ya go https://github.com/mypark/mvc6demo

**Comment by XVincentX** [comment]
Let me have a look, I'll get back to you.

**Comment by HerrKater** [comment]
Hi,

I'm facing with the same issue.
OS : Ubuntu 14.04
DNX :  1.0.0-rc1-update1    mono  
libuv: v1.7.0

I've tried with libuv 1.8.0 but it was throwing a “System.EntryPointNotFoundException: uv_loop_size”.

What am I missing?

**Comment by mypark** [comment]
so it looks like I have the same issue with all node.js client requests, wether it's dredd or not.  Seems to be an issue with kestrel rc1 https://github.com/aspnet/KestrelHttpServer/issues/406 .  I'll try again with the coreclr mono rc2 if I can.

**Comment by HerrKater** [comment]
Hi,

I use "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final". Shall I upgrade to the latest beta?
Thanks!

**Comment by XVincentX** [comment]
@mypark 

I am using ` 1.0.0-rc2-16357/mono/linux/osx` with Kestrel `1.0.0-rc1-final`

Tested it again, it works here.
I am not really sure what I can do to help you.

![image](https://cloud.githubusercontent.com/assets/1416224/12577032/275aa218-c418-11e5-900a-6873cd52474a.png)

**Comment by HerrKater** [comment]
Could you please test it on Linux?

**Comment by mypark** [comment]
@XVincentX  I'm using the same version as well, 1.0.0-rc2-16357/mono/linux/osx with Kestrel 1.0.0-rc1-final, not sure why mine fails and yours works.  Did you make any changes to the project?  If so can you push changes back to my demo git repo and I can compare my code with yours?

**Comment by XVincentX** [comment]
@mypark 
As stated before, the only change I made is to change the startup command in `dredd.yml`: `dnx run --server Microsoft.AspNet.Server.Kestrel`

A good idea would be to create to test it on a Linux environment, which could be easily provided by TravisCI or CircleCI, which are free for open source projects.

**Comment by honzajavorek** [comment]
@mypark Could you please try whether the problem persists with v1.0.7 of Dredd? Thanks!

**Comment by mypark** [comment]
still failing - I think it's a kestrel issue and less so a dredd issue as it fails with node.js http requests overall rather than just dredd.

**Comment by honzajavorek** [comment]
@mypark In this case, I'm not sure what can we do to help you :disappointed: If you happen to find any new info proving Dredd is guilty and ideally also some clues supporting the case and allowing us to resolve the issue, please get back and don't hesitate to re-open this. We'll make sure Dredd will be judged!

**Comment by honzajavorek** [comment]
@mypark If it's still valid, check https://github.com/apiaryio/dredd/issues/450, it might be a similar problem.
