### ISSUE TITLE
Idea: Ability to modify test result from after hooks

### ISSUE THREAD

**Issue by romansklenar** [apiaryio/dredd#345]
It would be useful if `after_*` hooks could also change the result of test.

**Motivation:**
Let's say we are developing an API and we already have blueprint which our developers use as mock server until our API will be implemented. Team who is working on API implementation use this blueprint for testing using dredd. During development they have some endpoints marked as _Not yet implemented_ and those returns `501` status according to [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html).

Idea is to mark tests for these endpoints automatically as skipped so it won't break whole test suite on CI server.

**Result:**
In `after_each` hook we could mark transaction as skipped depending on response code in `transaction['real']['statusCode']` returned by test.

``` python
import dredd_hooks as hooks

@hooks.after_each
def skip_not_implemented(transaction):
    if 'real' in transaction and transaction['real']['statusCode'] == '501':
        transaction['skip'] = True
        transaction['fail'] = False
        transaction['test']['status'] = 'skip' # ?
        transaction['test']['valid'] = True # ?
```

**Comment by romansklenar** [comment]
Current workaround for that use case is to have a list of transactions you want to skip, which works but developers need to keep that list updated.

```python
import dredd_hooks as hooks

# Transaction that we want to skip
skip_transactions = [
    'Users > Avatar resource > Upload avatar',
    # ... all the other endpoints
]

@hooks.before_each
def skip_transaction(transaction):
    if transaction['name'] in skip_transactions:
        transaction['skip'] = True
```

So ability to modify test result from after hooks would be nice thing to have but definitely not necessary.

**Comment by honzajavorek** [comment]
@romansklenar This should be now possible thanks to #648. Could you please confirm this now works for you? BTW, I think setting `transaction['skip'] = True` should be sufficient now (see [emitResult](https://github.com/apiaryio/dredd/blame/master/src/transaction-runner.coffee#L409:L412) in the transaction runner, the `skip` flag is checked and taken care of before anything else).

**Comment by romansklenar** [comment]
@honzajavorek 👍
