### ISSUE TITLE
BUG: Difference in connecting to apiary hooks between linux & OSX?

### ISSUE THREAD

**Issue by justinabrahms** [apiaryio/dredd#348]
I have an issue wherein my apiary tests work on linux, but fail on osx. This is all run through docker, so it should be isolated from these sorts of problems.

The repo in question is https://github.com/mitodl/ccxcon
You can see on Travis (linux) that the tests pass fine. https://travis-ci.org/mitodl/ccxcon/builds/101861546#L3075
I'm also able to run it perfectly fine on my linux system.

A coworker is getting errors running it on his system. Pastebin here: http://hastebin.com/iwajixoqih.shell

It's getting a connection refused error like https://github.com/apiaryio/dredd-hooks-python/issues/10

### Versions: 
- dredd@1.0.1
- dredd-hooks-python==0.0.2
- python 3.4 (but is the same on python 2.7)
- node 4.2.3

### Error
```
Error connecting to the hook handler. Is the handler running?
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

Can anyone give me information about how the connection to the hooks is being made? Any ideas on why this might be broken on OSX specifically?

cc @pwilkins

**Comment by w-vi** [comment]
@justinabrahms is it possible that your hooks file is not compiling or has some sort of error that the handler fails to import it? Try `python -m py_compile yourhooks.py`. This behavior usually is caused by some error while importing hook files.

**Comment by justinabrahms** [comment]
No, it isn't possible that it has some sort of error. I've additionally run this command and it produces no output on linux, mac or docker (on linux or mac hosts).

We run this through Docker (a containerization service). This works with linux as the host OS, but not OS X.

**Comment by w-vi** [comment]
IC, so on OSX it runs in docker too? Well than it is more of the docker on OSX issue, I have never tried it in docker on OSX, can you please describe in more detail the setup, is it that hooks are local and dredd in docker or how is it? Docker on OSX is a VirtualBox VM and the networking is different a lot, like binding to `0.0.0.0` etc so it very well maybe some of this sort.

**Comment by justinabrahms** [comment]
Yes, the failure is with linux guest (via virtualbox) and OSX as the host
OS. Everything is in the docker instance. I'm mostly in need of information
about how the system looks for the underlying hooks implementation, so I
can trace it through docker's routing mechanisms.

**Comment by w-vi** [comment]
The bridge between Dredd and hooks handler is a TCP connection where the server is started by the hook handler listening on `127.0.01` and port `61321` and Dredd connects to it again using the loopback and that may be the issue that it relies on loopback device. See https://github.com/apiaryio/dredd-hooks-python/blob/master/dredd_hooks/dredd.py for the details.

**Comment by romansklenar** [comment]
I've run into similar issue - for me tests are running fine on CirleCI and locally on OSX (tried on several machines) but they don't run in vagrant.
Once I change dredd's config to don't load hook files (written in python), tests at least runs although they all fails.

`python -m py_compile test/hooks.py` runs without error. Also whole app and tests are linted by pylint which is also clean.


### Versions
Ubuntu 14.04 LTS (tried also 15.10)
node v4.2.6 (tried also v0.10.35)
npm  2.14.12 (tried also v3.5.3)
dredd v1.0.4
dredd-hooks-python v0.0.2
Python v3.5.0

### Error
```bash
Spawning `python` hooks handler
Error connecting to the hook handler. Is the handler running?
{ [Error: connect ECONNREFUSED 127.0.0.1:61321]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 61321 }
make: *** [test] Error 3
```

I've spent already several days debugging this but without any success.

**Comment by romansklenar** [comment]
@justinabrahms Does your coworker installed python and node directly from homebrew? I've installed it using pyenv and nvm (which I've installed using homebrew) and it's running fine. Might worth to try it.

**Comment by pwilkins** [comment]
I'm the co-worker.  :-)  I'm using the Yosemite system Python 2.7.10 and node installed through Homebrew.  When I get to work I'll try what you propose.

**Comment by w-vi** [comment]
I think that it has something to do with how Virtualbox exposes `127.0.0.1` maybe we should try to bind to `0.0.0.0` on the hooks handler side or something similar, will have to find a OSX machine and give it a try.

**Comment by w-vi** [comment]
@romansklenar If you want to give it a bit more time, can you try to change the binding address in the dredd_hooks package https://github.com/apiaryio/dredd-hooks-python/blob/master/dredd_hooks/dredd.py#L32

**Comment by romansklenar** [comment]
Thanks for tip! Here's what I've tried:

```bash
# uninstall dredd and install if from my fork
sudo -H pip3 uninstall dredd_hooks
sudo -H pip3 install https://github.com/romansklenar/dredd-hooks-python/archive/host_change.zip

# find installed location
python3
>>> import dredd_hooks as hooks
>>> hooks.__file__
'/usr/local/lib/python3.5/dist-packages/dredd_hooks/__init__.py'
>>> exit()

# check that fork's change is really present
cat /usr/local/lib/python3.5/dist-packages/dredd_hooks/dredd.py | grep 0.0.0.0
HOST = '0.0.0.0'
```


But output of dredd looks still the same. It's even still reporting the same address 127.0.0.1 instead of 0.0.0.0

```bash
Spawning `python` hooks handler
Error connecting to the hook handler. Is the handler running?
{ [Error: connect ECONNREFUSED 127.0.0.1:61321]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 61321 }
```

**Comment by w-vi** [comment]
Hmmm, so something really fishy here. next thing I would try is to run the `dredd_hooks` alone without dredd, using https://github.com/apiaryio/dredd-hooks-python/tree/master/bin this file and then either with netcat or telnet manually connect to it using `127.0.0.1:61321` and see if it works

**Comment by romansklenar** [comment]
That seems to be working:

```bash
$ dredd-hooks-python
Starting Dredd Python hooks handler
```

```bash
$ telnet 127.0.0.1 61321
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
```

**Comment by w-vi** [comment]
So it looks like there is something wrong in dredd, will have to look a bit deeper, thanks a lot for providing all this debugging info.

**Comment by justinabrahms** [comment]
If you think you have a fix and you have some experience with docker + osx, you should be able to reproduce the problem here: https://github.com/mitodl/ccxcon/issues/83. Happy to walk you through the problem on our end if you need a reproducable test case.

**Comment by honzajavorek** [comment]
Could you please try whether the problem persists with v1.0.7 of Dredd? Handling of hooks and server processes went through a significant revamp. Thanks!

**Comment by romansklenar** [comment]
Yes it fixes the issue for me.
Thanks @honzajavorek for great effort with 1.0.6 & 1.0.7 releases :100:

**Comment by honzajavorek** [comment]
@romansklenar Thanks! :blush:
