### ISSUE TITLE
Introduce hooks before and after server start

### ISSUE THREAD

**Issue by w-vi** [apiaryio/dredd#351]
In some scenarios user wants to perform some tasks before the server is started, now we resolve to shell scripts etc but it would be nice to be able to do taht directly in a hook. Example, django DB maigrate.

**Comment by honzajavorek** [comment]
@w-vi We discussed this feature with @netmilk thoroughly and we both agreed this feature isn't needed in Dredd currently. People can perform actions before and after they run Dredd itself in their wrapping shell scripts. Maybe there are more concrete use cases for this and more users will vote for this feature, but until that time, I'm closing this.
