### ISSUE TITLE
2nd level MSON structure not implemented in JSON schema?

### ISSUE THREAD

**Issue by mekanixdk** [apiaryio/dredd#354]
This might be a dupe of https://github.com/apiaryio/dredd/issues/319 . But as it is marked at fixed I am thinking it might be something else as dredd/protagonist are all up to date.

I am seeing this from a little testcase I made (actually I expanded a little on http://dredd.readthedocs.org/en/latest/example/):

```
# dredd  blueprint.apib http://localhost:3000
info: Beginning Dredd testing...
fail: GET / duration: 38ms
info: Displaying failed tests...
fail: GET / duration: 38ms
fail: body: JSON schema is not valid draft v4! Invalid type: string (expected object) at path "/properties/type"

request:
body:

headers:
    User-Agent: Dredd/1.0.4 (Darwin 15.2.0; x64)

uri: /
method: GET


expected:
headers:
    Content-Type: application/json; charset=utf-8

body:
{
  "message": "Hello Word!",
  "myobject": {
    "item": ""
  }
}
statusCode: 200
bodySchema: {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "message": {
      "type": "string"
    },
    "type": "object"
  },
  "required": [
    "message"
  ]
}


actual:
statusCode: 200
headers:
    x-powered-by: Express
    content-type: application/json; charset=utf-8
    content-length: 54
    etag: W/"36-qupWQ33wo1wPtGnodw5i6g"
    date: Thu, 21 Jan 2016 20:51:46 GMT
    connection: close

body:
{"message":"Hello World!","myobject":{"item":"value"}}



complete: 0 passing, 1 failing, 0 errors, 0 skipped, 1 total
complete: Tests took 46ms
```

app.js:
```javascript
var app = require('express')();

app.get('/', function (req, res) {
  res.json({message: 'Hello World!', myobject: {item: "value"}});
})

var server = app.listen(3000);
```

blueprint.apib
```md
FORMAT: 1A

# API

# Group X

## GET /

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Testing)

# Data Structures

## Testing (object)
+ message: Hello Word! (string, required)
+ Include Level Two

## Level Two (object)
+ myobject (object, required)
  + item (string, required)
```

I am quite new to API Blueprint so I am possibly missing something here.

**Comment by philsturgeon** [comment]
I think I'm also suffering this same problem.

**Comment by w-vi** [comment]
This is a bug in drafter,  it is not correctly generating schema for `Include` statements, please track the issue  on dratfer repo https://github.com/apiaryio/drafter/issues/223

**Comment by xlexi** [comment]
Is there any workaround for this? I am also experiencing it.

**Comment by w-vi** [comment]
@xlexi Do not use the `Include` statement .. not really a workaround. The issue should be fixed very soon.

**Comment by w-vi** [comment]
It is now fixed in the drafter/protagonist and released so no more workarounds needed, just update the protagonist dependency to [1.2.6](https://github.com/apiaryio/protagonist/releases/tag/v1.2.6)

**Comment by pksunkara** [comment]
@honzajavorek This should be fixed too. Please check once.

**Comment by honzajavorek** [comment]
I will "check" it by adding it to our regression tests. If they pass, then
I'll consider this to be fixed in Dredd.

**Comment by philsturgeon** [comment]
![popcorn](https://cloud.githubusercontent.com/assets/67381/13296350/343e1560-dafb-11e5-8cc6-94edcf17b61f.gif)

**Comment by honzajavorek** [comment]
@pksunkara @w-vi I'm sad to announce that this is not fully fixed yet. Using `Include` as part of MSON definitions in the `Data Structures` section is fixed indeed (and can be used now like a workaround for this issue), but using `Include` in resources won't produce correct assets.

### How to reproduce the issue

1. `git clone` Dredd repository, perform `git fetch` to get all branches.
2. `git checkout honzajavorek/regression-354`
3. `npm install`
4. `./scripts/test --grep='Regression: Issues #319 and #354'`
5. You should get `32 passing, 10 failing`.

See the test and the API Blueprint in this PR: #380

### Workaround for Dredd users

1. Make sure you have `protagonist@1.2.6` installed. Go to your Dredd installation and run [`npm update`](https://docs.npmjs.com/getting-started/updating-local-packages).
2. Move all your definitions using `Include` from definitions of resources to the `Data Structures` section, at least temporarily until this issue gets fixed.
