### ISSUE TITLE
Question: Naming transactions in multiple transactions scenario

### ISSUE THREAD

**Issue by hussainjunaid** [apiaryio/dredd#361]
Hi,

I have the following scenario in my blueprint:

# Resource [/resource]
## Create Resource [POST]

+ request A
        ...
+ response 200
        ...
+ request B
        ...
+ response 200
        ...
+ request C
        ...
+ response 500
        ...

Which is picked up by dredd as 
'Resource > Create Resource > Example 1'
'Resource > Create Resource > Example 2'
'Resource > Create Resource > Example 3'

Is there any way of renaming these examples to more meaningful names? As shown in the example above, although the requests are titled as A, B and C, dredd still picks them as Example 1,2 & 3. 
I am writing a hook for this resource to add tests for all these possible scenarios but its pretty difficult to identify them using Example based naming. It will also be difficult from maintenance point of view if a particular scenario is changed and requires corresponding changes in the hook.

**Comment by honzajavorek** [comment]
Hi @hussainjunaid, at the moment it's not possible to go beyond the [implicit transaction examples](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#example-multiple-transaction-examples). However, we are working on an improved way how to address HTTP Transactions in Dredd hooks. There is a fresh proposal on how it could look like: https://github.com/apiaryio/dredd/issues/227 The new way should allow you to properly address any request-response pair. Do you think it would solve your problem? Feel free to drop a comment there.

**Comment by hussainjunaid** [comment]
Thanks @honzajavorek i'll follow #227 for updates
