### ISSUE TITLE
New Hook Langauge handler

### ISSUE THREAD

**Issue by ungrim97** [apiaryio/dredd#364]
Hi,

Just to let you know that I have written a module for writing hooks in Perl. It can be found here: https://github.com/ungrim97/Dredd-Hooks and can also be installed from CPAN (the perl packaging system) from https://metacpan.org/pod/Dredd%3A%3AHooks

It currently (at version 0.01) passes all tests in the dredd-hooks-templates repo. Please let me know if there is anything further you need of me.

Cheers,
Mike E
mre (ungrim97)

**Comment by netmilk** [comment]
Hey @ungrim97,

This is absolutely awesome! It's super exciting to have support for Perl in Dredd! Thank you so much for this fantastic contribution.

Would you mind doing several tweaks?

- Please set-up Travis CI for the repository
- Please add the Cucumber/Aruba test suite to the Travis file
- Add the Travis badge to the Readme
- Please file a PR for [Dredd documentation](https://github.com/apiaryio/dredd/tree/master/docs) with examples a brief how-to similar to other languages 

Let us know here when it's done, please. We'll add your project repo to our [integration builds](https://github.com/apiaryio/dredd/blob/master/scripts/test-hook-handlers.coffee) for the pre-release QA.

Thanks!

PS: Send me your t-shirt size and address If you're interested in one of these:

![image](https://cloud.githubusercontent.com/assets/79609/13080183/e25695a8-d4c7-11e5-94d2-f382a0132077.png)

**Comment by ungrim97** [comment]
Cheers @netmilk,

Will add those suggestions and let you know

**Comment by ungrim97** [comment]
All done

**Comment by netmilk** [comment]
@ungrim97 That's perfect! Thank you so much again!
