### ISSUE TITLE
Update the image in Dredd's README so it contains Perl

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#372]
Image will be provided by @jandvorak, work in progress.

**Comment by jandvorak** [comment]
![dredd](https://cloud.githubusercontent.com/assets/4904006/13142100/3a8a638e-d63b-11e5-8ff0-468e7a2dee75.png)

**Comment by ddelnano** [comment]
Looks dope

**Comment by honzajavorek** [comment]
@jandvorak Thanks very much! :+1:
