### ISSUE TITLE
Sometimes CLI reporter outputs 'NaNms'

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#376]
`pass: GET /message duration: NaNms`

**Comment by romansklenar** [comment]
+1 for that. I get that every time when test case passes but when it fails it shows actual time in miliseconds (using python hooks).

**Comment by itcraftsmanpl** [comment]
+1, the same problem, every test case: `duration: NaNms` but when fails time is correct number.
```
dredd --version
dredd v1.0.7
```
Hooks: PHP

**Comment by jakubkratina** [comment]
Same in `dredd v1.0.11`

**Comment by honzajavorek** [comment]
Yes, this is still an issue. I haven't got to fix it due to working heavily on #388 and #389 these days. I think the fix wouldn't be difficult. It's probably [somewhere in the CLI reporter](https://github.com/apiaryio/dredd/blob/master/src/reporters/cli-reporter.coffee). Also, if fixed there, it would be nice to look into the other reporters if there's not a similar bug. Would anyone of you like to work on this?

**Comment by jakubkratina** [comment]
I'll take a look, but no promises with solving it :)

**Comment by honzajavorek** [comment]
Released as v3.5.1 🎉
