### ISSUE TITLE
If additional files are given in --path and they don't exist, Dredd silently ignores them

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#378]
Is this bug or feature? In case Dredd should ignore them, it should be documented and there should be at least warning logged. In case Dredd should fail, then it does not and it's a bug.

``` shell
$ ls
apiary.apib
$ dredd ./apiary.apib http://localhost:8000 --path=./non-existent.apib
...
$ echo $?
0
```

**Comment by netmilk** [comment]
It is a bug. 🐞

**Comment by jgjadaoag** [comment]
Would it be alright if I make a fix for this?

**Comment by honzajavorek** [comment]
@jgjadaoag It would be awesome! 😄
