### ISSUE TITLE
Dredd fails after "ExtendElement must be composed from Elements of same type" warning

### ISSUE THREAD

**Issue by amuino** [apiaryio/dredd#381]
When parsing our blueprint, which uses `Include` in MSON Data Structures, we get the following output:

```
$ dredd
Configuration dredd.yml found, ignoring other arguments.
Starting server with command: false
Waiting 0 seconds for server command to start...
warn: Parser warning in file 'doc/api/public.apib.md': (4) ExtendElement must be composed from Elements of same type
/Users/amuino/.nvm/versions/node/v5.7.0/lib/node_modules/dredd/node_modules/blueprint-transactions/lib/blueprint-ast-to-runtime.js:25
  if (blueprintAst['name'] !== "") {
                  ^

TypeError: Cannot read property 'name' of undefined
  at blueprintAstToRuntime (/Users/amuino/.nvm/versions/node/v5.7.0/lib/node_modules/dredd/node_modules/blueprint-transactions/lib/blueprint-ast-to-runtime.js:25:19)
  at Object.module.exports.compile (/Users/amuino/.nvm/versions/node/v5.7.0/lib/node_modules/dredd/node_modules/blueprint-transactions/lib/blueprint-transactions.js:11:14)
  at Dredd.compileTransactions (/Users/amuino/.nvm/versions/node/v5.7.0/lib/node_modules/dredd/lib/dredd.js:285:44)
  at /Users/amuino/.nvm/versions/node/v5.7.0/lib/node_modules/dredd/lib/dredd.js:117:26
  at /Users/amuino/.nvm/versions/node/v5.7.0/lib/node_modules/dredd/lib/dredd.js:272:16
  at done (/Users/amuino/.nvm/versions/node/v5.7.0/lib/node_modules/dredd/node_modules/async/lib/async.js:132:19)
  at /Users/amuino/.nvm/versions/node/v5.7.0/lib/node_modules/dredd/node_modules/async/lib/async.js:32:16
  at /Users/amuino/.nvm/versions/node/v5.7.0/lib/node_modules/dredd/lib/dredd.js:245:18
```

Initial debugging points to either `drafter` or `protagonist` (or both) as the culprit.

Drafter detects [an error on the blueprint](https://github.com/apiaryio/drafter/blob/8dd33e76654901a7ea076fbd667fdef5b9962b27/src/refract/Element.cc#L182) but it is reported to dredd as successful parse with warnings. However, the parse result has no elements to process:

```{ _version: '2.2',
  warnings:
   [ { code: 4,
       message: 'ExtendElement must be composed from Elements of same type',
       location: [] } ] }```

... which ends in the error reported above:
```
  if (blueprintAst['name'] !== "") {
                  ^

TypeError: Cannot read property 'name' of undefined
```

**Comment by honzajavorek** [comment]
@amuino Thanks for filing the bug and initial investigation! @apiaryio/apiary-parser could you please help me to confirm this?

If this is valid Drafter/Protagonist output, then I assume we'll have to teach Dredd how to behave when the AST is "empty" and ensure by tests it behaves correctly.

**Comment by amuino** [comment]
Might be related to https://github.com/danielgtaylor/aglio/issues/237, which causes the same error and has a minimal blueprint to reproduce

**Comment by amuino** [comment]
One additional note, the blueprint looks perfectly valid to me, that's why I think that it might be a problem with drafter, in addition to teaching dredd how to handle empty AST.

**Comment by honzajavorek** [comment]
Just for the record, this issue consists of two problems:

- Drafter issue https://github.com/apiaryio/drafter/issues/217
- Dredd issue https://github.com/apiaryio/dredd/issues/403

**Comment by RyanHavoc** [comment]
I'm experiencing this issue as well. My first time using Dredd and I get it straight away so I don't actually know what success results look like at this stage. :-S

Is there a work around?

**Comment by amuino** [comment]
@RyanHavoc  We were able to get rid of the non-object types (an array) and inline them. The cause is fixed on `drafter`, so I expect it to be fixed in the next `dredd` release

**Comment by honzajavorek** [comment]
@RyanHavoc This is fixed in the underlying parser tooling, but since it wasn't released as stable version yet, I'm still hesitant to upgrade. If you feel adventurous, workaround would be to update Dredd's `protagonist` dependency in `package.json` to version `1.3.0-pre.0` and install it into Dredd's `node_modules`.

**Comment by honzajavorek** [comment]
And I'm sorry for the trouble, really. I see it's not a good first time experience to run into a bug like this :disappointed: [MSON](https://github.com/apiaryio/mson) (a.k.a. Attributes) still isn't completely bug-free and officially released as a production-ready technology in all the tooling around [API Blueprint](https://apiblueprint.org/). In [Apiary](http://apiary.io/) we're working around the clock to get it polished on all fronts! :triumph:
