### ISSUE TITLE
Migration to API Elements

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#388]
### Motivation
API Blueprint parser `drafter` and its Node.js binding `protagonist` is slowly migrating to the [API Elements](http://api-elements.readthedocs.org/en/latest/overview/) output format and any new functionality is no longer implemented in the legacy AST Dredd is integrated with. 

### Defensive prep stage
- [x] Create an equivalent test for all API Blueprint AST based tests using the respective API Blueprint and parser in Dredd
    - https://github.com/apiaryio/dredd/pull/417
- [x] Do the same with [blueprint-transactions](https://github.com/apiaryio/blueprint-transactions)
    - https://github.com/apiaryio/blueprint-transactions/pull/9

### The actual labour
- [x] Fork `blueprint-transactions` to `dredd-transactions`
    - [apiaryio/dredd-transactions](https://github.com/apiaryio/dredd-transactions)
    - https://github.com/apiaryio/dredd-transactions/pull/1
- [x] Hide the current implementation of Cannonical Transaction Paths
    - https://github.com/apiaryio/blueprint-transactions/pull/10
    - https://github.com/apiaryio/dredd-transactions/pull/1
- [x] Deprecate `blueprint-transactions` - will no longer be maintained
    - https://github.com/apiaryio/blueprint-transactions/pull/10
- [x] Reconstruct Example groups from Refract Source Maps to keep backward compatibility for Transaction Names
    - https://github.com/apiaryio/dredd-transactions/pull/2
- [x] Switch from API Blueprint AST to API Elements
    - https://github.com/apiaryio/dredd-transactions/pull/8
- [x] Move parsing from Dredd to `dredd-transactions`
  - https://github.com/apiaryio/dredd/pull/445

  - [ ] ~~Change the AST input interface to an interface consuming a string on top of same fixtures using [`fury.js`](https://github.com/apiaryio/fury.js)~~
  - [x] Change the AST input interface to an interface consuming a string on top of same fixtures using [`protagonist`](https://github.com/apiaryio/protagonist)
  - [x] Use `dredd-transactions` in `dredd`
    - https://github.com/apiaryio/dredd/pull/445
  - [x] Handle errors and warnings annotations from parse result (make sure tests exist)
    - https://github.com/apiaryio/dredd/pull/445

## Unblocking
- [API Blueprint Request Parameter](https://github.com/apiaryio/api-blueprint-rfcs/blob/master/rfcs/0004-request-parameters.md) 
  - Announced here: https://github.com/apiaryio/api-blueprint/issues/310#issuecomment-189452940
  - Original API Blueprint issue https://github.com/apiaryio/api-blueprint/issues/58
  - Solves https://github.com/apiaryio/dredd/issues/78 https://github.com/apiaryio/dredd/issues/361 ...

- [Transaction Path](https://github.com/apiaryio/dredd/issues/227) to support multiple responses https://github.com/apiaryio/dredd/issues/25#issuecomment-190643228
  - Write the same test for all Transaction Name tests using Transaction Path
  - Solves https://github.com/apiaryio/dredd/issues/361

- [Swagger 2.0 / OAI support](https://github.com/apiaryio/dredd/issues/389)
  
- Transaction Paths support in external language workers/handlers 
  - Adding a feature to the [hook worker integration template](https://github.com/apiaryio/dredd-hooks-template)
  - Support in all known workers ([Ruby](https://github.com/apiaryio/dredd-hooks-ruby), [Python](https://github.com/apiaryio/dredd-hooks-python), [PHP](https://github.com/ddelnano/dredd-hooks-php), [Go](https://github.com/snikch/goodman), [Perl](https://github.com/ungrim97/Dredd-Hooks))

- Deprecation of all integrations to Transaction Names, introduction of Transaction Paths
  - Dredd Hooks Documentation using only Transaction Paths
  - The [Transaction Object](https://dredd.readthedocs.org/en/latest/hooks/#transaction-object-structure) has `path` instead of `name`
  - `pathOrigin` instead of `origin`
  - Updating documentation in hook workers original repositories
  - 💀 `--names`, 🙌 `--paths`

- Moving Transaction Name logic from `dredd-transactions` to Dredd Reporters where it belongs

**Comment by honzajavorek** [comment]
@netmilk Just realised we also need to somehow deal with the fact that Apiary Reporting API has API Blueprint AST as part of it's contract:

```apib
...
  - blueprints (array, required) ... Array of blueprints used for the test run
      - filename (string, required) ... file name
      - raw (string, required) ... raw bleuprint content in Markdown
      - parsed (object, required)  ... parsed blueprint from raw data
        - ast (object, required) ... parsed blueprint ast
        - sourcemap (object, optional) ... sourcemap from protagonist
        - warnings (array, required) ... bleuprint parser warnings
...
```
