### ISSUE TITLE
Using Dredd with babel

### ISSUE THREAD

**Issue by ddelnano** [apiaryio/dredd#391]
For the current project I am working on we are using babel so we have access to ES2015 features and such.  I am trying to write the hooks file that dredd will use with the features that must be compiled by babel.  What I am trying to do is first build to hooks file then have dredd used the compiled version to run but I am running into issues.  The nodejs hooks can't seem to use my compiled version of the file since I receive the following error message.

<img width="626" alt="screen shot 2016-03-01 at 11 10 58 pm" src="https://cloud.githubusercontent.com/assets/5855593/13450398/eb7d2a02-e002-11e5-89da-428d2dc9c6c6.png">

So I am not asking why this compiled version isn't working but more is there a better approach to this?  Can I get the dredd to spawn the nodejs hooks via babel instead of node?

**Comment by honzajavorek** [comment]
Hi, are you sure you are passing the compiled version of the file or that
it correctly compiles imports to requires? It seems like the file you are
running contains keyword `import`, which is ES2015 syntax, not ES5.

**Comment by honzajavorek** [comment]
@netmilk What do you think of supporting hooks in Babel/Coffee/whatever-compiled JS out of the box? User would just specify in config / argument what to use to compile the thing, similar to mocha's `--compilers='coffee:coffee-script/register'`.

**Comment by ddelnano** [comment]
I am running Babel and I can verify that I don't see the import statement but I do see generators (function *) so something is weird. I'm gonna look into it more today

**Comment by ddelnano** [comment]
However, I am wondering if I could do the following.  I wrote the php hooks so I understand how the process works but I am struggling to find where to hooks server is in the dredd repo from the minimal searching I did.  I was thinking about just using the pieces of the hooks server inside a new executable file that instead of using `#!/usr/bin/env node` I could do `#!/usr/bin/env babel-node` and then in that file create the server.  that would allow dredd to execute it like normal and I would pass it to `dredd.yml` via the language option

**Comment by honzajavorek** [comment]
I think the main logic you are looking for is in [`hooks-worker-client.coffee`](https://github.com/apiaryio/dredd/blob/master/src/hooks-worker-client.coffee). However, Node.js hooks have some special handling. They can be ran [directly](http://dredd.readthedocs.org/en/latest/hooks-nodejs/) within the Dredd process ([loading here](https://github.com/apiaryio/dredd/blob/cf52b69cb9a49f092a4cee878571abaadbd6d6cd/src/add-hooks.coffee#L123:L127)) or in [sandbox mode](http://dredd.readthedocs.org/en/latest/hooks-js-sandbox/) using [pitboss](https://github.com/mdp/pitboss). I believe you can pass `--language=your/arbitrary/node/script.js` as a custom hooks handler, but it would have to be a complete separate implementation, the same way as PHP hooks are.

**Comment by ddelnano** [comment]
Ah I see, I was expecting it to be the same as the other languages hooks.  I believe if it was separate that would solve my issues cause then I could launch the server with babel-node.  Is there a reason the node hooks were not broken off like the other language hooks?

**Comment by ddelnano** [comment]
If they were broken off like the others than coffeescript/babel/whatever compiled would work like I described.  I could do that if the contribution would be accepted.  Is there any reasons for keeping it the way it is?

**Comment by honzajavorek** [comment]
I think that's something for @netmilk to answer.

**Comment by ecordell** [comment]
It's a little hacky, but what we do is keep all of our hook files in a `/hooks/` directory, then compile them to `/compiled-hooks/` and reference that when running Dredd.

Also, I wrote the "direct" hook loading way back when Dredd was a monolingual baby and can verify that if you loaded hooks directly they could be written as Coffeescript, because that's what Dredd is written in. Skimming the current source it looks like this would still work, though I agree that it would be nicer to see various "hook servers" take over that role so that javascript and it's ever-changing dialects can continue to be supported.

**Comment by ddelnano** [comment]
@netmilk would nodejs hooks be accepted as a contribution?

**Comment by netmilk** [comment]
@ddelnano You mean babel, right? If so, totally, go for it. I'd be excited to have it here. 

@honzajavorek Actually, it might be a good thing to move the JS sandbox hooks to a separate hook handler as well because the [`add-hooks.coffee`](https://github.com/apiaryio/dredd/blob/master/src/add-hooks.coffee) is a hot mess and it's worth refactoring and simplifying anyways.

**Comment by ddelnano** [comment]
I mean separating the nodejs hooks to their own server like the other ones are.  That way when starting up the server you could use babel-node, or whatever for all the different javascript variants.

If it were separate I wouldn't need to have this build step then run dredd I could just use babel-node to run the hooks server.

**Comment by netmilk** [comment]
@ddelnano I'm not sure if it will work for you. I tried following the thing bellow which should be an equivalent of what you're proposing and it didn't work.

I installed `babel-cli`
```shell
$ npm install -g babel-cli
```

I had following hookfile using ES2015
```
import hooks from './hooks';

hooks.beforeAll( callback => {
  console.log('babel works');
  callback();
});
```

Then I ran Dredd as you proposed to run the Node.js hooks runner
```
$ babel-node `which dredd` test/fixtures/single-get.apib http://localhost:3000 --hookfiles=./es2015.js
```

And I got this result with this error
```
nfo: Beginning Dredd testing...
info: Found Hookfiles: ./es2015.js
warn: Skipping hook loading...
warn: Error reading hook file "/Users/netmilk/projects/dredd/es2015.js"
warn: This probably means one or more of your hookfiles is invalid.
warn: Message: /Users/netmilk/projects/dredd/es2015.js:1
(function (exports, require, module, __filename, __dirname) { import hooks fro
                                                              ^^^^^^
Unexpected reserved word
warn: Stack: /Users/netmilk/projects/dredd/es2015.js:1
(function (exports, require, module, __filename, __dirname) { import hooks fro
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
  at exports.runInThisContext (vm.js:73:16)
  at Module._compile (module.js:443:25)
  at loader (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:126:5)
  at Object.require.extensions.(anonymous function) [as .js] (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:136:7)
  at Object.require.extensions.(anonymous function) [as .js] (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/proxyquire/lib/proxyquire.js:243:43)
  at Module.load (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at Proxyquire._withoutCache (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/proxyquire/lib/proxyquire.js:177:12)
  at Proxyquire.load (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/proxyquire/lib/proxyquire.js:134:15)
  at loadHookFile (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/add-hooks.js:66:7)
  at addHooks (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/add-hooks.js:142:9)
  at TransactionRunner.run (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/transaction-runner.js:59:12)
  at Dredd.startRunner (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/dredd.js:317:24)
  at /Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/dredd.js:125:30
  at /Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/dredd.js:309:18
  at EventEmitter.<anonymous> (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/reporters/cli-reporter.js:24:14)
  at EventEmitter.emit (events.js:129:20)
  at Dredd.emitStart (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/dredd.js:301:39)
  at /Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/dredd.js:121:28
  at Dredd.compileTransactions (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/dredd.js:294:12)
  at /Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/dredd.js:117:26
  at /Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/dredd.js:272:16
  at done (/Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/async/lib/async.js:132:19)
  at /Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/node_modules/async/lib/async.js:32:16
  at /Users/netmilk/.nvm/versions/node/v0.12.2/lib/node_modules/dredd/lib/dredd.js:245:18

error: GET /machines duration: 5ms
error: Error connecting to server under test!
info: Displaying failed tests...
fail: GET /machines duration: 5ms
fail: Error connecting to server under test!
complete: 0 passing, 0 failing, 1 errors, 0 skipped, 1 total
complete: Tests took 19ms
```

**Comment by netmilk** [comment]
It seems like @w-vi's feature request #351 for support for some pre-runtime scripts/hooks would finally make sense.

**Comment by ddelnano** [comment]
Sorry what I proposed was probably not clear.

What I meant was to develop nodejs hooks that are equivalent to the other ones like the php ones I wrote.  Then instead of using the hooks as an executable the user would use the hooks as a library and write an executable for it that could be executed by babel-node or coffeescript or whatever and dredd would run that executable command to start the server and parse the hooks.  So the command would look like this `dredd --language babel-node bin/hooks.js`

Does that make more sense?

**Comment by ddelnano** [comment]
That would make the hook usage different between others so maybe not a good idea.  But yea @w-vi's feature seems like it could provide this functionality.

**Comment by netmilk** [comment]
@ddelnano And what's the difference between running whole Dredd with `babel-node` and only the hooks handler you're proposing to write? I think I understand what you mean and I'm concerned it won't work.

**Comment by netmilk** [comment]
@ddelnano, my bad, I haven't installed and enabled the babel ES2015 preset. Ignore my comments above. I think it's solved. Would you mind trying it?

This works for me:

```
npm install -g babel-cli babel-preset-es2015
echo '{ "presets": ["es2015"] }' > .babelrc
babel-node `which dredd` test/fixtures/single-get.apib http://localhost:3000 --hookfiles=./es2015.js
```


With this hook file in `es2015.js`
```
import hooks from 'hooks';

hooks.beforeAll( callback => {
  console.log('babel works');
  callback();
});
```

**Comment by ddelnano** [comment]
Ah I didn't think of that but it works for me.  You definitely need to configure babel, in its newest version it just does nothing by default

**Comment by ddelnano** [comment]
Yea I got it working too.  Cool well this works just fine for me then, wish I would have thought of that earlier haha.

**Comment by netmilk** [comment]
@ddelnano So it's this solving the issue?

@ecordell Would you mind trying this workaround too?

**Comment by ddelnano** [comment]
Yea that solves my issue.  I just didn't want to have a build step for my hooks.

**Comment by netmilk** [comment]
@honzajavorek Please review my PR on documentation: https://github.com/apiaryio/dredd/pull/398

**Comment by ddelnano** [comment]
Thanks for the help

**Comment by netmilk** [comment]
@ddelnano My pleasure

**Comment by ecordell** [comment]
@netmilk That works, thanks!

**Comment by jch254** [comment]
Any solution for Windows users?

**Comment by jch254** [comment]
Looks like utilising where.exe instead of which should do the trick ;)

**Comment by webmato** [comment]
How to run Dredd + Babel + ES6 dreddhooks on Windows? 
```
C:\Users\tom\Work\Project>where.exe dredd

C:\Program Files\nodejs\dredd
C:\Program Files\nodejs\dredd.cmd
```
but 

```
C:\Users\tom\Work\TouchArt\Project>babel-node where.exe dredd
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\tom\Work\Project\where.exe'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at C:\Users\tom\AppData\Roaming\nvm\v5.6.0\node_modules\babel-cli\lib\_babel-node.js:159:24
    at Object.<anonymous> (C:\Users\tom\AppData\Roaming\nvm\v5.6.0\node_modules\babel-cli\lib\_babel-node.js:1
60:7)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```
