### ISSUE TITLE
Hook Spawner Broken after commit

### ISSUE THREAD

**Issue by xvalentino** [apiaryio/dredd#393]
Commit a8d544bbb4825911c09bae570c9df60da4471bc6 broke hook spawning

**Comment by honzajavorek** [comment]
@xvalentino We tried to make sure this won't happen with loads of tests, so it's hard to hear that it broke despite our efforts, but I'm really glad you discovered the problem before new Dredd version got released. Thank you very much for that! You've just shielded a lot of users from the problem :+1: 

Could you please elaborate on what's exactly wrong and how can I reproduce it? Again, thank you very much for reporting this!

**Comment by xvalentino** [comment]
Yeah sure thing!

When I compile this commit, and run dredd with a ruby hook, I get the output 

`info: Configuration dredd.yml found, ignoring other arguments.
info: Beginning Dredd testing...
info: Found Hookfiles: ./dreddhooks.rb`

Then the process stops, but raises no error. It silently fails. It works fine if there is no hook being ran. If this doesn't reproduce the error, let me know and I can get a sample app up reproducing the error.

**Comment by honzajavorek** [comment]
@xvalentino Thank you!

I tried to reproduce this on top of current `master`, but unsuccessfully. Could you please try to assemble the minimal app or at least share your `dredd.yml`?

**Comment by netmilk** [comment]
I smell some race condition. Can it be connected with this flaky test: https://travis-ci.org/apiaryio/dredd/jobs/114224085?

**Comment by netmilk** [comment]
@xvalentino 

> I tried to reproduce this on top of current master, but unsuccessfully. Could you please try to assemble the minimal app or, at least, share your dredd.yml?

Or just the hooks file and the `dredd.yml` :) I'm keen to know what's going on there. :)

**Comment by honzajavorek** [comment]
> When I `npm run prepublish` this commit, and run dredd with a ruby hook, I get the output...

@xvalentino Did you try that also on top of current master or is it just the commit you mentioned? The commit alone won't work all right and won't pass tests.

> I smell some race condition.

@netmilk The flaky test is documented in #384, it's still the same. I can give it some time.

**Comment by honzajavorek** [comment]
@xvalentino There is very similar bug described in #404. Could you please confirm whether it is the same problem you are experiencing?

**Comment by xvalentino** [comment]
@honzajavorek #404 was what I was experiencing. Thanks!
