### ISSUE TITLE
Dredd should have completely strict dependency on Drafter aka Protagonist

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#394]
Currently, every minor version of Protagonist brings various regressions etc., but the package.json as it is now allows users to install the latest version. Any new install of Dredd evaluates the Protagonist dependency to it's latest version. Thus I think we should pin it to be sure about what users have installed and to have control over what combination we consider in Dredd as stable. Once Drafter stabilizes, we can make this more loose again.

@kylef @netmilk

**Comment by w-vi** [comment]
@honzajavorek :+1:

**Comment by netmilk** [comment]
+1 we should bump the APIB parser version only if it can pass our test suite.
