### ISSUE TITLE
Dredd crashes if it is provided with "empty" or otherwise invalid AST

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#403]
If for some reason Dredd is provided with "empty" AST, it crashes. It should detect the problem and report there's nothing to test instead (error, warning... something). Then Dredd should gracefully exit - either with status 1 or 0, that's up to discussion.

---

Follow up to https://github.com/apiaryio/dredd/issues/381.

**Comment by kylef** [comment]
Just want to link this together with https://github.com/apiaryio/drafter/issues/255.

**Comment by honzajavorek** [comment]
I don't think this is an issue anymore with new Dredd Transactions, but I didn't find a test for it, so I can't close this yet 😒
