### ISSUE TITLE
v1.0.6 possibly affects Codeship CI integration

### ISSUE THREAD

**Issue by charliemaffitt** [apiaryio/dredd#404]
The release of v1.0.6 this morning affected my Codeship integration. I'm not sure yet if that's due to my setup or configuration, or whether it will affect everyone using Codeship. In my case, the update caused the Dredd suite to no longer execute on Codeship, causing Codeship to fail the build after 10 mins of inactivity. No errors, it was as though it ran silently without output, or not at all.

I'll experiment with it locally and see if I can find a way to configure my setup to work with v1.0.6 in Codeship. In the meantime, be advised that if this happens, specifying Dredd version 1.0.5 in the Codeship integration allows one to continue using 1.0.5 as before without problems.

**Comment by honzajavorek** [comment]
@charliemaffitt Thanks for reporting this! If you stumble upon any details on why the new version stopped to work for you, please share it here. I'm keen to fix any possible issues ASAP. You can try to run dredd with `--level silly` to raise logging output.

**Comment by charliemaffitt** [comment]
@honzajavorek raising the log output level to `silly` surprisingly didn't change anything. That would suggests it's not initiating at all. I'll keep working on it.

**Comment by romansklenar** [comment]
Same thing here. Just using python hooks and `dredd.yml` config file.

**Comment by honzajavorek** [comment]
@charliemaffitt No change is expected on user's side. We did some refactoring of those parts and although I believe we did our best in testing the thing, something apparently slipped through the net and under some circumstances spawning of processes breaks.

If anyone would be able to assemble something I could replicate, that would be awesome. Sample hooks and `dredd.yml` or minimal app... I'll try to get to this behavior myself, but so far I don't have many clues to follow.

**Comment by honzajavorek** [comment]
OK, looks like I made some progress...

![dredd](https://cloud.githubusercontent.com/assets/283441/13635268/f40f3518-e5fa-11e5-859f-2c1106d2fe1e.gif)

Is this the same thing you are experiencing?

**Comment by romansklenar** [comment]
@honzajavorek Yes, exactly.

**Comment by romansklenar** [comment]
Confirmed that issue is fixed for me in 1.0.7 release.

But now I sometimes get "Connect timeout 1.5s to the handler on localhost:61321 exceeded, try increasing the limit." but there is no way how to increase this configuration cause it's hard coded in source code. 

https://github.com/apiaryio/dredd/pull/382 seems that it's on a good way to adress this.

**Comment by charliemaffitt** [comment]
Fixed for me by 1.0.7 as well. I sincerely appreciate your quick attention to the issue. :confetti_ball: :tada:

**Comment by honzajavorek** [comment]
@romansklenar @charliemaffitt Thanks for confirmation! I'm glad this is resolved!

#382 will definitely be part of the next release. It is 99% done and if @xvalentino doesn't have time to finish @netmilk's nitpicks, I'll do it myself before new version will be released. Much praise to @xvalentino for the hard work in issues here and also for noticing this problem in #393 first.
