### ISSUE TITLE
get another transition in a hook

### ISSUE THREAD

**Issue by lippea** [apiaryio/dredd#411]
Hi

I'm wondering if there is a way to get another transition in the hook?

The problem I have now is I need hook to get some dynamic value after a transition, then use it in another transition, but this transition has to run on another server.

That means I have two transitions against two servers, but they share some dynamic value.

Either I have to run them in one session with after&before hooks and against two servers,
like dredd -f file1.apib -s server1 -f file2.apib -s server2
or I have to retrieve the value from first transition and modify the second transition in ONE after hook.

Cheers
Lucy

**Comment by netmilk** [comment]
Hey Lucy,

Dredd is meant at this moment for testing of the API reference item by item in isolation (analogy to unit tests) and this sounds to me like a cross-server integration scenario testing. 

**But** I'd like to get Dredd there (#358) and I like your approach and thinking. I think the usage of two API Blueprints and after&before [hooks for saving and retrieving from the request stash](http://dredd.readthedocs.org/en/latest/hooks-nodejs/#sharing-data-between-steps-in-request-stash) is something what I'd recommend.

You can also create the data retrieving HTTP transaction programatically in `beforeAll` hooks by manually creating [the transaction object](http://dredd.readthedocs.org/en/latest/hooks/#transaction-object-structure) and injecting it to the transaction array (first parameter of the `beforeAll` hook function). 

Disclaimer: Dredd wasn't design for this and this usage is not tested. :)

**Comment by lippea** [comment]
Hi netmilk

Thanks for your suggestion. I'm actually testing one item in isolation. The second transition is not for testing, but get the data for verification for the first transition. That means I have no way to verify the data but put another transition to the second item.

I'm currently thinking of two possible ways to solve it: 1. save the response into a file 2. modify the blueprint of second transition in the after hood of the first transition

**Comment by honzajavorek** [comment]
Closing in favor of https://github.com/apiaryio/dredd/issues/995
