### ISSUE TITLE
Sending duplicate headers

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#412]
Dredd doesn't support sending the same header twice. 

The only workaround at this moment is to use the same header with different casing:

`transaction.request.headers.x-header = "foo";`
`transaction.request.headers.X-header = "bar";`

**Comment by honzajavorek** [comment]
@netmilk IMHO dupe of https://github.com/apiaryio/dredd/issues/356, but the workaround is a new information, thanks!

**Comment by netmilk** [comment]
@honzajavorek Thanks for pointing it out!
