### ISSUE TITLE
Create gif example for README

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#418]
https://github.com/apiaryio/dredd#quick-start could contain gif video of how Dredd works.

**Comment by honzajavorek** [comment]
https://github.com/nbedos/termtosvg

**Comment by artem-zakharchenko** [comment]
Workflow GIF is mentioned as one of the points in the checklist of #703. I don't see a reason to keep individual tasks if there is a master task tracking the progress. Especially if the changes are all related to a single goal improving the README.

Should we close this, @honzajavorek?

**Comment by honzajavorek** [comment]
Up to you how you organize this. Feel free to close. This issue was created before the master issue, that's why it exists separately.
