### ISSUE TITLE
Allow hiding the values of certain headers on failures

### ISSUE THREAD

**Issue by realityking** [apiaryio/dredd#421]
The source for our API documentation is public and tested on TravisCI. When a test failure occurs it includes the authentication token which is a security issue.

The best solution from our end would be, if we could pass a list of headers whose value should never be printed to the CLI output.

**Comment by honzajavorek** [comment]
This makes sense to me! Thanks for the idea. What would be @netmilk's thoughts on this?

**Comment by honzajavorek** [comment]
@realityking We're in the process of designing how removing sensitive data from Dredd reports could work in https://github.com/apiaryio/dredd/issues/623#issuecomment-246737489. Would you mind looking at the proposal and comment / give us feedback if that would work for you?
