### ISSUE TITLE
Schema generated from MSON misses items in advanced array

### ISSUE THREAD

**Issue by lippea** [apiaryio/dredd#423]
MSON:

```apib
+ Response 200 (application/json; charset=UTF-8)

    + Attributes
        - tobreak: abc (string, fixed)
        - errors (array)
            - (object, fixed)
                - desc: Sent
```

Generated schema:
```
statusCode: 200
bodySchema: {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "tobreak": {
      "type": "string",
      "enum": [
        "abc"
      ]
    },
    "errors": {
      "type": "array"
    }
  },
  "required": [
    "tobreak"
  ]
}
```

But I would expect something like
...
        "errors": {
            "type": "array"
            "items":[
                "type": "object",
                "properties":{
                    "desc": {
                        "type": "string"
                    }
                }
            ] 
        }
...

**Comment by kylef** [comment]
You can make the array fixed for it's contents to show in the schema:

```diff
 + Response 200 (application/json)
     + Attributes
           - tobreak: abc (string, fixed)
-          - errors (array)
+          - errors (array, fixed)
               - (object, fixed)
                   - desc: Sent
```

Then it would result in the following schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "tobreak": {
      "type": "string",
      "enum": [
        "abc"
      ]
    },
    "errors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "desc": {
              "type": "string",
              "enum": [
                "Sent"
              ]
            }
          },
          "required": [
            "desc"
          ],
          "additionalProperties": false
        }
      ]
    }
  },
  "required": [
    "tobreak",
    "errors"
  ]
}
```

However, `fixed` has more meanings and this probably adds unwanted constraints.

**Comment by lippea** [comment]
Thanks kylef for your so quick reply.
Does that mean all the items in the array needs to be exact the same as listed under the array?
But I only concern the item listed under it.

**Comment by honzajavorek** [comment]
@lippea

> MSON describes structures that MAY be observed versus what MUST be observed.
> -- [MSON Spec](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#13-promises)

What you want to achieve goes against the "MAY" nature of MSON, so it won't be easy to implement, if even possible. The only exception from this behavior is `fixed`, but as @kylef noted, that might sometimes bring too much constraints.

There are two ways out of this:

1. Do not check what simple arrays MUST contain, just document what they MAY contain.
2. Use manually-crafted JSON Schema (API Blueprint's [Schema section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-schema-section)) to ensure what the array MUST contain. If Schema section is present, it overrides anything what could get auto-generated from MSON.

If you think this all isn't the way it should be, you can suggest changes in [MSON issues](https://github.com/apiaryio/mson/issues/).

**Comment by lippea** [comment]
@honzajavorek I have achieved it by using schema section, but it's a bit too long (more than 600 lines)
So I would like to see if it's possible to do it with MSON, which would contain just over 100 lines.
Or maybe I will explore other ways to solve my problem. But so far, I like the BluePrints stuff.

**Comment by honzajavorek** [comment]
@lippea Good! Thanks for sharing. I really recommend you to file an [MSON issue](https://github.com/apiaryio/mson/issues/) to discuss the use case. 600 vs 100 lines is, I believe, quite strong argument.

> But so far, I like the BluePrints stuff.

Great! Don't forget you can find out more docs and list of Open Source tools at [API Blueprint's website](https://apiblueprint.org/).
