### ISSUE TITLE
Error: RuntimeWarning: Parent module 'hooks' not found while handling absolute import

### ISSUE THREAD

**Issue by teone** [apiaryio/dredd#428]
I'm facing this output while running `dredd` with `python` hooks enabled:

```
info: Configuration dredd.yml found, ignoring other arguments.
info: Using apiary reporter.
info: Beginning Dredd testing...
info: Found Hookfiles: ./hooks.py
info: Spawning `python` hooks handler
info: Hook handler stderr: ./hooks.py:1: RuntimeWarning: Parent module 'hooks' not found while handling absolute import
  import dredd_hooks as hooks

info: Hook handler stdout: Starting Dredd Python hooks handler

info: Connected to the hook handler, waiting 0.1s to start testing.
info: Dry run, skipping API Tests...
info: Dry run, skipping API Tests...
info: Dry run, skipping API Tests...
info: Dry run, skipping API Tests...
info: Dry run, skipping API Tests...
info: Dry run, skipping API Tests...
info: Sending SIGTERM to the hooks handler
info: Hook handler stderr:
Connection closed
```

My config is: 

```
reporter: apiary
custom:
  apiaryApiKey: f941658c6714ebf58eeda5e0786e937f
  apiaryApiName: xos
dry-run: null
hookfiles: "./hooks.py"
language: python
sandbox: false
server: null
server-wait: 3
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
blueprint: apiary.apib
endpoint: 'http://localhost:3000'
```

My `hooks.py` file is:

```
import dredd_hooks as hooks

@hooks.before_each
def my_before_each_hook(transaction):
    print('before each')
```

How can I solve this?

Thanks

**Comment by w-vi** [comment]
Hi @teone the warning is harmless, as the hooks are importing modules dynamically from given files it causes this warning in Python 2 because it is geared towards Python 3. So it looks like you have no issue actually. The reason you don't see the print output in dredd is that `print()` uses buffered io and to make sure that it get's propagated you need to add `sys.stdout.flush()` after your print statement. See https://github.com/apiaryio/dredd-hooks-python/issues/16

**Comment by honzajavorek** [comment]
This can be really confusing. We should definitely put this to docs and think of possible workarounds so the message won't appear.

**Comment by w-vi** [comment]
@honzajavorek Yes it is bit confusing and it is one of the things to be fixed once there is a time for it, as always :)

**Comment by teone** [comment]
@w-vi thanks, it works... I'm new too python and this looks confusing, for sure adding this note to the documentation will help!

**Comment by honzajavorek** [comment]
@teone I'm glad we worked it out! However, I'll leave this open to have a reminder this needs to go to docs. I added respective labels.

**Comment by honzajavorek** [comment]
This won't go to docs! 😱 Why? Because it's no more an issue thanks to https://github.com/apiaryio/dredd-hooks-python/pull/20! 🎉
