### ISSUE TITLE
Python hook handler not being correctly located on Windows

### ISSUE THREAD

**Issue by Crimack** [apiaryio/dredd#429]
dredd does not run correctly for me from the command prompt. Despite having the dredd-hooks for Python installed under both the virtual environment and the default Python, neither of them are being located by dredd during its run.
### System Info
- Windows 8.1 x64
- Python 2.7.10
- dredd-hooks v0.0.3
### Output of command 'dredd'

info: Configuration dredd.yml found, ignoring other arguments
info: Starting server with command: python manage.py runserver 7000 --noreload --settings=myapp.settings
info: Beginning Dredd testing...
info: Found Hookfiles: _hooks.py
info: Spawning `python` hooks handler
error: Python hooks handler server command not found: dredd-hooks-python
Install python hooks handler by running:
$pip install dredd-hooks
info: Sending SIGTERM to the backend server
info: Backend server was killed.
### Output of manually running python dredd-hooks-python

<virtual env> app_path > python C:\Users\Crimack\Envs\my_app\Scripts\dredd-hooks-python
Starting Dredd Python hooks handler

Is this a problem with the way I have my virtual environment set up, dredd's interaction with Windows, or the hooks package?

**Comment by honzajavorek** [comment]
Hi, thanks for the report! Dredd isn't very well tested on Windows (see https://github.com/apiaryio/dredd/issues/204), unfortunately. It [uses which](https://github.com/apiaryio/dredd/blob/master/src/which.coffee) to [locate the handler](https://github.com/apiaryio/dredd/blob/master/src/hooks-worker-client.coffee#L96). I guess `which` won't work in standard Windows environment :cry: 

Workaround would be to create something executable called `which` in your `PATH`, which would do the same thing, i.e. determine whether something exists or not. I believe Windows actually have a similar utility called `where`, so maybe just aliasing it or wrapping in a simple `.bat` script would do the job.

Please note I did not try the workaround, so it's not 100% solution. If you go that way, I'd love to hear your experiences. Also, any debugging in the direction towards Windows compatibility would be extremely helpful. For instance, we don't even have a list of things which would have to be changed so Dredd works seamlessly on Windows and e.g. noting such blockers in comments under https://github.com/apiaryio/dredd/issues/204 would be a tremendous help with broader compatibility.

**Comment by Crimack** [comment]
I've done a little bit more digging into this. I'm unsure if the `which ` command is the problem or not. I've tried aliasing the two, but the output of 'where' is slightly different to `which` (`'where` returns all possible results, `which` only returns the location of the command which would be run). They should both return a 0 exit code though.

I've tried the same thing using `git-bash` and `cygwin`, but the issue persists on both of those `Unix` terminals as well.

Interestingly, since Windows doesn't cope very well with shebangs, it's unable to simply run the command 'dredd-hooks-python', and needs to be explicitly supplied with 'python <file_path>'. git-bash has no problems with this command though. Perhaps this could be the problem?

It could also possibly be a `PATH` issue related to virtual environments on Windows. Since the `Scripts` folder is only prepended to the `PATH` on activation, maybe node is having issues with this?

I'll do a little more investigation tomorrow, and also try to help with debugging where possible.

**Comment by honzajavorek** [comment]
@Crimack That is a great insight, thanks! Thank you very much for all this!

If you have `git-bash` or `cygwin`, I'd focus on making Dredd correctly executable there first and then moving to having it working in `cmd.exe`. However, I experienced some problems when trying to make virtualenv and `git-bash` working together. I think the virtualenv has to be created from within the `git-bash`, otherwise it will install `cmd.exe`-compatible scripts and those won't run elsewhere. It's a minefield :grimacing: 

I think the aim here should be to have a bash prompt (inside virtualenv or not), where you can run following commands, exactly as they are written:

```
$ which
$ dredd-hooks-python
$ dredd
```

If they can be executed like that, I believe the thing should work together. If `python .../dredd-hooks-python` is necessary or something similar, we're still not there. I wouldn't be afraid `npm`-installed stuff won't pick up binaries from virtualenv - from my experience, as far as virtualenv is activated and the binaries can be found in the altered PATH under their names, it is not an issue.

Regarding `where`, I think it shouldn't matter how much output is there. I believe we check just exit code or at most just any output vs. no output.

**Comment by Crimack** [comment]
Yeah, virtualenv can be a little tricky in these cases. It's still possible to activate the virtualenv within git bash by running `source path_to_scripts/activate` though, even if it's created a lot of .bat files.

Out of curiousity I also created a Linux VM (OpenSUSE Leap 42.1) to ensure that it wasn't my project setup. With exactly the same code/`PYTHONPATH`/virtualenv setup, the VM dredd works correctly.

I'm still having the same _Python hooks handler server command not found: dredd-hooks-python_ with this though. `dredd`, `dredd-hooks-python` and `which` all run as expected. `which` is also still 'aliased'  to where, so even if `node` is running a secret command prompt it should still work correctly. 

The developer of [this](https://www.npmjs.com/package/cross-spawn) seems to believe that `spawnSync`, which seems to be how the `which` command is executed in [this](https://github.com/apiaryio/dredd/blob/master/src/which.coffee) file, has existing issues on Windows. I'm not sure how accurate this is since I'm not particularly experienced with `node`, but it could be something else to look into.

**Comment by honzajavorek** [comment]
@Crimack That actually might be the case, `spawnSync` could have problems on Windows. That would explain your situation, exactly as you write! I believe there is no special reason we use specifically `spawnSync` as a drop-in replacement for [`child_process.spawnSync`](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) missing in earlier versions of Node. I think it could be replaced by anything else doing the job. If `cross-spawn` would pass all tests, I'm willing to give it a try.

Do you think you might be able to work on a Pull Request? I'd be happy to provide any missing clues to contributing.

**Comment by Crimack** [comment]
Yeah, I'll take a look at trying to do this at some stage today.

**Comment by honzajavorek** [comment]
@Crimack I'm pretty confident https://github.com/apiaryio/dredd/pull/737 solves all the issues we've been discussing here. Once it's merged and a new version of Dredd gets released, I'd greatly appreciate if you could go and try, whether Dredd works for you with the Python hooks (beware #742, please).

Your prior investigation has been a great help in implementing the basic Windows support and I'd like to say thank you again for the help 👍

**Comment by Crimack** [comment]
@honzajavorek I'm unfortunately not going to be able to test this for you under the same conditions as where I previously encountered these issues. I was working as an intern for a company, and have returned to university since I created this issue so I can't access the original project I was working on.

I've contacted a former colleague who hopefully might get a chance to investigate or refer it to someone who can. I'm unsure how many Windows machines they're still using, or if they'll be able to help. I'll let you know what he says though 😄 

Sorry I couldn't be of more help with the pull request. I quickly ended up having to switch to a VM to get some work done, and I'm not particularly familiar with Javascript so found it hard to get things to work whenever I tried to tinker 😢

**Comment by honzajavorek** [comment]
@Crimack I completely understand. Anyway, I would like to thank you for all the time and attention you paid to debug Dredd on Windows. I'm sorry it didn't turn out to have a successful results right away. If your former colleagues bring any feedback, it would be appreciated! Good luck with your studies 🎓 😉
