### ISSUE TITLE
\n is appended to the value of last parameter

### ISSUE THREAD

**Issue by lippea** [apiaryio/dredd#432]
When I send following request, the Email value received by the application is actually "abc@bbb.com.au\n". "\n" is appended to the value and hence the request is rejected because it's invalid email format.

```
+ Request (application/x-www-form-urlencoded; charset=utf-8)

    + Body

            firstName=a&lastName=b&email=abc@bbb.com.au

+ Response 200 (application/json; charset=utf-8)

    OK
```

**Comment by honzajavorek** [comment]
Thanks for reporting this! Similar bug is already reported many times already:

- https://github.com/apiaryio/dredd/issues/343
- https://github.com/apiaryio/dredd/issues/67
- https://github.com/apiaryio/dredd/issues/217

The only difference is that the old bug is being usually reported with `text/plain` content type and you use `application/x-www-form-urlencoded`. I'll make sure this thing gets higher in our priorities :sweat:

**Comment by honzajavorek** [comment]
This is still an issue, but I decided to close duplicates.

- The main issue to track this problem is now: https://github.com/apiaryio/dredd/issues/67
- Workaround can be done by hooks: http://dredd.readthedocs.io/en/latest/hooks-nodejs/#remove-trailing-newline-character-in-expected-plain-text-bodies

**Comment by honzajavorek** [comment]
I'd like to address the problem. I added a comment explaining the situation: https://github.com/apiaryio/dredd/issues/67#issuecomment-287759448 If you have any ideas, I'd be very glad to discuss possible solutions.
