### ISSUE TITLE
Runtime variables for dredd

### ISSUE THREAD

**Issue by GiritharanR** [apiaryio/dredd#433]
Is there any way to pass runtime variables to hook files? As of now, within hooks i am doing a file read to get configurable values.

**Comment by honzajavorek** [comment]
I think you can use `custom` (see http://dredd.readthedocs.org/en/latest/usage/ ) and then access it through `hooks.configuration` in the hooks, but I believe that works only for the Node.js hooks. Would that solve your problem?

**Comment by GiritharanR** [comment]
@honzajavorek - Thank you for this. I will try and let you know the updates :+1:

**Comment by honzajavorek** [comment]
@GiritharanR did it work for you? I just realised there's actually an older issue for this: https://github.com/apiaryio/dredd/issues/215
