### ISSUE TITLE
hypen no allowed in URL template expansion

### ISSUE THREAD

**Issue by ungrim97** [apiaryio/dredd#434]
Hi. I am hitting an issue where if an example parameter value for URL template paths contain a hyphen then only the sting up to the hypen is placed in the template expansion

```
## Bar Item [/bar/{barid}]

### Get Bar [GET]

+ Parameters
    + barid: 1-foo (string)
```

makes a request to 

> /bar/1

 rather than 

> /bar/1-foo

Is this a known/expected behaviour or a bug

Cheers

**Comment by kylef** [comment]
@ungrim97 This might not be very clear from the spec. But in API Blueprint, parameters and attributes where the value contains `-` or `_` must be escaped, so we can differentiate between the sample value and the description.

You will want to escape your value as such:

```apib
## Bar Item [/bar/{barid}]

### Get Bar [GET]

+ Parameters
    + barid: `1-foo` (string)
```

**Comment by ungrim97** [comment]
@kylef Cheers
