### ISSUE TITLE
Jenkins CI not detected correctly as CI environment by Apiary reporter

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#436]
Dredd looks into system environment variables and checks whether some typical variables indicating CI are present. For instance,
- CircleCI exports https://circleci.com/docs/environment-variables/
- Travis CI exports https://docs.travis-ci.com/user/environment-variables/

There is usually `CI=true` and also others, such as `CIRCLECI` or `TRAVIS` set inside the build. I believe detecting the `CI` variable [should be enough](https://github.com/apiaryio/dredd/blob/092b373bea35ebbec961822eafd39f13b352c89e/src/reporters/apiary-reporter.coffee#L80) for Dredd to decide.

I checked the variables Jenkins exports by default and I can't see the `CI` or anything Dredd would currently look for: https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables

Since Jenkins is probably the most used self-hosted OSS CI people use, this is a bug and we should fix it.

> As a workaround, you can set CI=true in your build and Dredd should then correctly report to the CI tab in Apiary.

**Comment by colinrymer** [comment]
So I think there are a couple environment variables that are worth looking into using - if we want to make this as Jenkins specific as possible, `JENKINS_URL` is about the only option. A more generic option, that would allow other CI services besides Jenkins to have be compatible out of the box would be `BUILD_ID`.
