### ISSUE TITLE
MSON / arrays / JSON schema is rendered incompletely

### ISSUE THREAD

**Issue by beyourselfman** [apiaryio/dredd#448]
issue occurs at dredd@1.0.10

Hi all,

given the following MSON data structure:

```
## testItem (object)
+ name: name (string)
+ properties (object)
    + prop: p (string)

## testArray (array)
+ (testItem)
```

and referencing this in a request:

```
+ Request (application/json)

    + Headers

            Accept: application/vnd.siren+json

    + Attributes(testArray)
```

dredd renders the json correctly like this

```
body:
[
  {
    "name": "name",
    "properties": {
      "prop": "p"
    }
  }
]
```

Thus, I expect the rendered json schema of `testArray` to be:

```
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "properties": {
        "type": "object",
        "properties": {
          "prop": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

But the actual json schema rendered by dredd is

```
bodySchema: {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array"
}
```

This means that the response is not checked against the structure of the array, but merely if the response is an array at all.

**Comment by honzajavorek** [comment]
Hi @beyourselfman, this is actually a feature of MSON and cannot be improved or fixed on Dredd level. See @w-vi's comment at https://github.com/apiaryio/dredd/issues/177#issuecomment-211294577 and most importantly, read and feel free to comment issue https://github.com/apiaryio/mson/issues/31. Thanks!
