### ISSUE TITLE
Ability to specify order of the transactions

### ISSUE THREAD

**Issue by tu1ly** [apiaryio/dredd#456]
current:
Dredd runs the transactions as they’re specified in blueprint.
expected:
ability to define transactions order. Othervise 2 blueprints which are sematicaly the same could behave differently when sharing data across the transactions

**Comment by smizell** [comment]
@tu1ly Cool idea :) Did this cause an issue for you? Would it be difficult to keep track of two lists of transactions—one in the blueprint and one in your Dredd hooks/configuration?

Would the ability to randomize the tests be a solution here?

**Comment by lazlojuly** [comment]
Maybe the "only" option's array order could be used as first implementation?

**Comment by Souler** [comment]
I ran into the same issue today, I ended up using the `beforeAll` hook

```js
var order = [
    // Your API names in the wanted order of execution
]

hooks.beforeAll(function(transactions, done) {
    transactions.sort(function(a, b) {
        var aIdx = order.indexOf(a.name)
        var bIdx = order.indexOf(b.name)
        return aIdx - bIdx
    })
    done()
})
```

**Comment by honzajavorek** [comment]
@Souler This is an interesting solution!

Just to add to the discussion, Dredd is primarily a tool designed to perform isolated tests and hooks are here to help you to isolate each test. [See docs on this.](http://dredd.readthedocs.io/en/latest/how-to-guides/#isolation-of-http-transactions)

If you need to order your transactions, it's a sign you're not creating isolated tests. YMMV if that's good or bad.

**Comment by adityasaxena** [comment]
@Souler Thank you very much! You saved my day!

**Comment by honzajavorek** [comment]
Closing in favor of https://github.com/apiaryio/dredd/issues/995

**Comment by shivshankar3578** [comment]
> I ran into the same issue today, I ended up using the `beforeAll` hook
> 
> ```js
> var order = [
>     // Your API names in the wanted order of execution
> ]
> 
> hooks.beforeAll(function(transactions, done) {
>     transactions.sort(function(a, b) {
>         var aIdx = order.indexOf(a.name)
>         var bIdx = order.indexOf(b.name)
>         return aIdx - bIdx
>     })
>     done()
> })
> ```

Not working for me @dredd v12.0.7

**Comment by honzajavorek** [comment]
@shivshankar3578 Could you share more in a separate issue with a full bug report? This should work.

**Comment by shivshankar3578** [comment]
```

let testFlow = [
  "GET /services/ug/{id}",
  "POST /services/ug",
  "POST /services/account/add_user",
  "POST /services/ug/user",
  ]


hooks.beforeAll(function(transactions, done) {
  hooks.log("before all");
  transactions = _(transactions)
  .map(item=> {
    item.name = item.request.method+" "+item.origin.resourceName
    return item
  })
  .filter(item=>{
    return testFlow.indexOf(item.name) >= 0
  })
  .sortBy(item=>{
    return testFlow.indexOf(item.name)
  })
  .value()

  done();
});
```
And in
```
hooks.beforeEach(function(transaction, done) {
```
I'm not getting GET /services/ug/{id} First 
Tried with done(transactions), done(null, transactions), hooks.configuration.only = transactionsNames but nothing works

**Comment by honzajavorek** [comment]
What does `_(transactions)` do? Does it copy the array? You need to modify the original `transactions` array.

**Comment by shivshankar3578** [comment]
No, it doesn't and I'm reassigning transactions again after modification. It's not immutable also. All the Array functions (filter, sort or map) return a new modified array so I need to reassigning it again.

**Comment by honzajavorek** [comment]
It cannot be reassigned. This is a hack which counts with the fact that you modify the original array, the one `transactions` variable references to. So `transactions = ` won't work, because ten `transactions` will reference to a different array in memory. [This](https://stackoverflow.com/a/44660117/325365) could help you to achieve what you need.

**Comment by shivshankar3578** [comment]
Got it, but it's a bit confusing, Either you should freeze the array or impl. it using immutable way

**Comment by honzajavorek** [comment]
It is confusing, it is a kind of a hack. As you say, ideally there would be a nice immutable interface to achieve this. We're working on decoupling things in Dredd internally which would allow that in the long run.
