### ISSUE TITLE
Pass external data to hook

### ISSUE THREAD

**Issue by tu1ly** [apiaryio/dredd#457]
current:
can not pass external data to hook
expected:
can pass external data to hook

**Comment by smizell** [comment]
@tu1ly Could you provide an example here? What do you mean when you talk of external data? Thanks!

**Comment by honzajavorek** [comment]
I think this is duplicate of https://github.com/apiaryio/dredd/issues/433.

**Comment by honzajavorek** [comment]
...and since #433 is duplicate of https://github.com/apiaryio/dredd/issues/215, I'm closing this :) The https://github.com/apiaryio/dredd/issues/215 now contains an example on how to use the `custom` configuration key for passing data to JavaScript hooks.
