### ISSUE TITLE
Recent change in docs made some old links 404

### ISSUE THREAD

**Issue by JackuB** [apiaryio/dredd#467]
I've noticed docs link that got changed

```diff
- https://dredd.readthedocs.org/en/latest/usage/
+ https://dredd.readthedocs.org/en/latest/usage-cli/
```

Can a 301 redirect be added? For the old one?

**Comment by honzajavorek** [comment]
I doubt it, it's mkdocs & RTD. But I can try.

**Comment by honzajavorek** [comment]
Tried this

<img width="622" alt="screen shot 2016-05-02 at 16 26 07" src="https://cloud.githubusercontent.com/assets/283441/14956917/a271d672-1082-11e6-84aa-1aa026d28f35.png">

but still experiencing 404s. Not sure whether I should wait or whether it just doesn't work.

**Comment by JackuB** [comment]
Nope, still 404. Not sure how RTD redirect works, but maybe it needs also the `/en/latest/` part http://docs.readthedocs.io/en/latest/automatic-redirects.html

**Comment by honzajavorek** [comment]
The redirect should cout with that:

<img width="611" alt="screen shot 2016-05-05 at 12 08 50" src="https://cloud.githubusercontent.com/assets/283441/15041163/29f410ea-12ba-11e6-911b-cfe7c7696745.png">

I added one more, but without success to change anything:

<img width="817" alt="screen shot 2016-05-05 at 12 06 38" src="https://cloud.githubusercontent.com/assets/283441/15041166/392b7634-12ba-11e6-9880-e3f2d7574808.png">

I'm afraid we're being hit by https://github.com/rtfd/readthedocs.org/issues/1826 here.

**Comment by smizell** [comment]
@honzajavorek looks like one hack is to do what is mentioned here:

https://github.com/rtfd/readthedocs.org/issues/1826#issuecomment-214753550

**Comment by honzajavorek** [comment]
@JackuB @smizell Tried to address this by https://github.com/apiaryio/dredd/pull/489. Please review.

**Comment by honzajavorek** [comment]
It works! Also, I think https://github.com/apiaryio/dredd/pull/491 will fix the rest.
