### ISSUE TITLE
Dredd - API Blueprint Testing Tool. “Undefined” while testing

### ISSUE THREAD

**Issue by imp-partner-test** [apiaryio/dredd#47]
I installed dredd - API Blueprint Testing Tool and trying to test our APIary API against the implementation. 
In the blueprint I have just one resource which is correctly implemented on somehost... but test fails :(

test command: dredd apiary.apib http://somehost.de:8443/imp-endpoint
output: Info: Beginning Dredd testing... undefined

I tried also with more options to get more information what is undefined.. like -l verbose and some other options. But I did not get more information about the failure :( Does anyone have experience with it? Thank you!!! :)

---

platform - win, dredd - v0.2.1, test apib: https://www.dropbox.com/s/p9zexrj3g6htzlq/apiary.apib, test.sh: https://www.dropbox.com/s/vqn6gch91vwqc16/test.sh
on stackoverflow: http://stackoverflow.com/questions/21881988/dredd-api-blueprint-testing-tool-undefined-issue

**Comment by awesome** [comment]
FWIW: Had this issue and fixed it with: https://www.npmjs.com/package/gulp-convert-newline . Formatted lined endings like:

```javascript
'use strict';

var gulp = require('gulp'),
  concat = require('gulp-concat'),
  config = require('./config/apib_config.js'),
  // […]
  soften = require('gulp-soften'),
  template = require('gulp-template'),
  convertNewline = require("gulp-convert-newline");

var srcDir = './src/**/*.apib',
  outDir = './build/',
  outFile = 'output.apib';

gulp.task('main', function() {
  gulp.src(srcDir)
    .pipe(template(config))
    .pipe(soften(4))
    .pipe(concat('output.apib'))

    .pipe(convertNewline({
      newline: "lf"
    }))

    .pipe(gulp.dest('./build/'));
});
```
