### ISSUE TITLE
Missing tag of latest master

### ISSUE THREAD

**Issue by mrtnrst** [apiaryio/dredd#471]
**_Problem_**: After the latest merge a new tag was not made which is causing problems with node v6. 

**_Proposed Solution_**: Tag the latest release as 1.1.0-pre.1 

**_Relevant Pull Request_**: #465  which has already been merged into master

**Comment by honzajavorek** [comment]
Just about to release 1.1.0-pre.1. Sorry for the delay, #440 still isn't ready!
