### ISSUE TITLE
Migrate all mentions of readthedocs.org to readthedocs.io

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#472]
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.

**Comment by kylef** [comment]
I think this would be a good opportunity to switch to our own CNAME. Perhaps something like `dredd.apiary.io` which shields us from these kinds of changes in the future.

Currently we're tied to, and giving away links to readthedocs. If the service ever goes away, or if we decide to move away from them in the future we will have a lot of broken links. It would be good to have our own CNAME that we can move elsewhere.

**Comment by honzajavorek** [comment]
I would like to also hear opinions from @netmilk, @abtris, @Almad, @JackuB.

**Comment by JackuB** [comment]
Sadly `dredd.apiary.io` is taken.

**Comment by Almad** [comment]
I casted my vote with `dredd.api.sexy` :trollface: 

Agreed about CNAME, and project landing pages in general...but it kinda goes back to branding. Maybe `oss.apiary.io/dredd`? Or separate top-level for dredd, akin to apiblueprint.org? @paraskakis ?

**Comment by honzajavorek** [comment]
Just for the record, this [already has an internal Trello ticket](https://trello.com/c/BBckAej7/120-migrate-dredd-documentation-into-own-project-page).

**Comment by honzajavorek** [comment]
> I casted my vote with dredd.api.sexy

Yeah... there was also internal Trello ticket to disable `dredd.api.sexy` :trollface:

**Comment by honzajavorek** [comment]
Let's leave the effort to mirgate somewhere else as an internal ticket or let's create another issue. I'll close this issue by simply moving `.org` links to `.io` now.
