### ISSUE TITLE
npmjs.com isn't the latest update, still 1.1.0-pre.0

### ISSUE THREAD

**Issue by davepoon** [apiaryio/dredd#474]
npmjs.com isn't the latest update, still 1.1.0-pre.0,
which is causing the build error(error: no type named 'GCEpilogueCallback' in 'v8::Isolate') using node 6.0/6.1 when you do `npm install -g dredd`.

**Comment by honzajavorek** [comment]
Linking my comment: https://github.com/apiaryio/dredd/pull/473#issuecomment-217369049

**Comment by honzajavorek** [comment]
<img width="256" alt="screen shot 2016-05-06 at 11 28 45" src="https://cloud.githubusercontent.com/assets/283441/15069425/be0b848e-137d-11e6-9e0b-fe3ae2fabe46.png">

**Comment by davepoon** [comment]
Yeah! Congrats!
