### ISSUE TITLE
Backport Node 6 support

### ISSUE THREAD

**Issue by LinusU** [apiaryio/dredd#476]
How about releasing `v1.0.11` which just bumps the patch-version of protagonist so that we can get support for Node.js 6 in a non-pre version. This is currently causing problems in our CI and I would love a quick release of this ❤️

**Comment by honzajavorek** [comment]
I can consider it, but it would mess up branches, since all the current work is in `master` now. I didn't really think anyone would need Node 6 that early after release and considered adding the support as _nice to have_ task. Honestly, I'd rather spend time with fixing the issues you have than backporting Node 6 support. Would you please help me with that and file issues related to problems you experience? Thanks!

**Comment by LinusU** [comment]
Actually, it's very easy to do it without messing up branches.

```sh
# Create a new branch for the 1.0.x release line, starting at the v1.0.10 tag
git checkout -b v1.0.x v1.0.10

# Apply the fix for Node.js 6
git cherry-pick 28d97fb

# Cut a new patch release
npm version patch

# Publish the new branch to github
git push --follow-tags --set-upstream origin v1.0.x

# Publish to npm
npm publish
```

I would really appreciate if you would do this for me 👌

**Comment by LinusU** [comment]
@honzajavorek I have reported my error with the pre-release here: #478. I would really appreciate it if you could publish a patch release to fix Node 6 compatibility while fixing the bugs in the newer version. I have outlined all the steps necessary, and it shouldn't take you more than 5 minutes...

**Comment by honzajavorek** [comment]
@LinusU I'm sorry, but I couldn't react yesterday. Thanks very much for reporting the issue!

I created the [`v1.0.x`](https://github.com/apiaryio/dredd/tree/v1.0.x) branch. Once all integration tests pass, I'll make the release.

**Comment by LinusU** [comment]
No problem, thank you! 🎉

**Comment by LinusU** [comment]
@honzajavorek Seems like the version wasn't published to npm, did you forget to run `npm publish`?

**Comment by honzajavorek** [comment]
Tests are still running :) https://travis-ci.org/apiaryio/dredd/builds/129089159

**Comment by LinusU** [comment]
Cool 👌

**Comment by LinusU** [comment]
@honzajavorek All is green, time to publish 🙌

**Comment by honzajavorek** [comment]
```
$ npm dist-tag ls
latest: 1.0.11
unstable: 1.1.0-pre.1
```

If I may present a wish here too, please do continue with testing `1.1.0-pre.x` as it's tremendous help for us. We need to find and kill all regression issues.

**Comment by LinusU** [comment]
> If I may present a wish here too, please do continue with testing 1.1.0-pre.x as it's tremendous help for us. We need to find and kill all regression issues.

Will do, thanks for resolving this 👍
