### ISSUE TITLE
Dredd hooks on windows

### ISSUE THREAD

**Issue by frexin** [apiaryio/dredd#477]
Does it work on windows? I'm trying implement php hooks, but always getting error "Hooks handler server command not found", however file path is correct.
As i see from dredd source code, you are using system call "which" for checking file exist: https://github.com/apiaryio/dredd/blob/master/src/hooks-worker-client.coffee#L107

Of course, windows does not have this command.

**Comment by honzajavorek** [comment]
Hi, unfortunately there's no official Windows support yet. There are [some known issues](https://github.com/apiaryio/dredd/issues?q=is%3Aopen+is%3Aissue+label%3AWindows), you're specifically talking about one from https://github.com/apiaryio/dredd/issues/429. I'd definitely love to have Windows support, but as of now I can't dedicate much resources to it myself. If you'd be willing to work on the issue and nail down at least part of the Windows problems, it would be completely awesome and you'd gain eternal glory.
