### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by LinusU** [apiaryio/dredd#478]
I'm getting this error when trying out Dredd version `1.1.0-pre.1`, it worked at version `1.0.10`.

```text
/.../node_modules/dredd/lib/transaction-runner.js:339
      fullPath = '/' + [this.parsedUrl['path'].replace(/^\/|\/$/g, ""), request['uri'].replace(/^\/|\/$/g, "")].join("/");
                                                                                      ^

TypeError: Cannot read property 'replace' of null
  at TransactionRunner.configureTransaction (/.../node_modules/dredd/lib/transaction-runner.js:339:87)
  at TransactionRunner.configureTransaction (/.../node_modules/dredd/lib/transaction-runner.js:3:57)
  at /.../node_modules/async/lib/async.js:246:17
  at iterate (/.../node_modules/async/lib/async.js:146:13)
  at /.../node_modules/async/lib/async.js:157:25
  at /.../node_modules/async/lib/async.js:248:21
  at TransactionRunner.configureTransaction (/.../node_modules/dredd/lib/transaction-runner.js:381:12)
  at TransactionRunner.configureTransaction (/.../node_modules/dredd/lib/transaction-runner.js:3:57)
```

**Comment by Ramblurr** [comment]
I'm a fresh dredd user (literally npm install -ged a few minutes ago) running node v.5.5.0, and I'm getting this error when my `endpoint` config has a path after the `host:port`.

How can I work around this for now?

**Comment by Ramblurr** [comment]
Looks like I had  installed `v1.1.0-pre.1`. Downgrading to `v1.0.10` fixed it (v1.0.11 isn't on npm yet).

**Comment by honzajavorek** [comment]
Thanks for reporting this! That's definitely a regression we need to fix. Yes, downgrading is a preferred option right now.

**Comment by smizell** [comment]
@LinusU I was wondering if you include any additional information to help debug this? I have seen this issue come up when people have a URI template but did not define the parameters for it.

Example:

```apib
FORMAT: 1A

# My API

# Item [/item{?foo}]
Parameters should be defined here, but they are not.

## GET
+ Response 200
```

Do you have anything like this in your blueprint?

**Comment by smizell** [comment]
@LinusU I have added some more information to an issue that may be related. Maybe this is what you're seeing as well?

https://github.com/apiaryio/dredd/issues/469

**Comment by honzajavorek** [comment]
The problem seems to be that now `dredd-transactions` do pass such transaction to Dredd although in the past they did not. Working on a fix.
