### ISSUE TITLE
[Questions] Partial Response Assertions

### ISSUE THREAD

**Issue by bkuhl** [apiaryio/dredd#483]
Is it possible to perform partial assertions on responses?  We're looking to follow the [JSON-API spec](http://jsonapi.org) for some upcoming projects and the responses can become quite exhaustive.  In some scenarios we may wish to just perform assertions based on the `data` section of the response, not relations.

**Comment by honzajavorek** [comment]
@bkuhl I admit it took some time to find a matching response, but I think you might want to check out https://github.com/apiaryio/dredd/issues/253. It contains an example on how you can write your own validation and rewrite Gavel.js validation results with it. Do you think that would work for you?

**Comment by honzajavorek** [comment]
Let me know please and feel free to re-open!
