### ISSUE TITLE
Module version mismatch. Expected 48, got 47.

### ISSUE THREAD

**Issue by wise007** [apiaryio/dredd#486]
Hello, 

when I run `dredd` command I'm getting 'Module version mismatch. Expected 48, got 47.' error.

Node version is `6.1.0.` and npm `3.8.6`.

Complete error message:
```
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/dredd/lib/dredd.js:11:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

What should I do to fix this?

Thank you

**Comment by kylef** [comment]
This sounds like you've installed dredd and then upgraded or changed the version of node you are using. To solve this, you will need to reinstall dredd with the version of node you want to run it from.

```shell
$ npm install -g dredd
```

**Comment by wise007** [comment]
Thank you for quick answer. I have reinstalled dredd and still not working, same error.

```
npm install -g dredd
/usr/local/bin/dredd -> /usr/local/lib/node_modules/dredd/bin/dredd
/usr/local/lib
└── dredd@1.0.11 
```

**Comment by honzajavorek** [comment]
I found a similar issue in the wild: https://github.com/mscdex/mmmagic/issues/66 Could you please, @wise007, try out the hints mentioned in the issue I linked? This really looks like problem with your setup, not with Dredd.

**Comment by wise007** [comment]
@honzajavorek: Yeah, it is possible (a probably is) problem with my setup, but every command after upgrade works fine, except `dredd`. I'll try and post a response.

**Comment by wise007** [comment]
So reinstallation of node and npm and it solved the problem. Thank you for your assistance. Great job with dredd.

**Comment by honzajavorek** [comment]
@wise007 Thanks for praise and for sharing! I hope this issue helps anyone bumping into the same problem. I'm glad it works for you now :+1:

**Comment by marshall-kapfudza** [comment]
I experienced the same issue, to resolve it I stated by checking my node version and I installed the node vision manager then I switched to the version `nvm use 6`

**Comment by asbjornu** [comment]
I'm seeing this although `nvm` says I'm using node v6.10.0:

```shell
$ nvm current
v6.10.0
```

I've also tried to reinstall `dredd` (leading to nodejs/node-gyp#942), without success.

**Comment by alexey-sh** [comment]
same error
node v6.10.0
npm 3.10.10

**Comment by honzajavorek** [comment]
@asbjornu @alexey-sh Did you try the solutions mentioned above? You could also give a try to the [pure JS version](http://dredd.readthedocs.io/en/latest/installation/#compiled-vs-pure-javascript) to avoid compilation:

```sh
$ npm uninstall dredd
$ npm install dredd --no-optional
```
