### ISSUE TITLE
Proposal on new way of tagging releases on npm

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#497]
Current way of tagging versions:

- All regular versions are released with the `latest` tag.
- `pre` versions are released only with the `unstable` tag.

Proposal on new way of tagging versions:

- All versions are released with the `latest` tag.
- Non-`pre` versions are released also with the `stable` tag.

Reasons / thoughts:

- This way people will help with testing `pre` versions by default.
- People will still be able to "pin" their installations to just `stable` releases by `npm install dredd@stable` (e.g. in CI).

How to make the transition:

- We could add a installation warning (printed during `npm install dredd`) that `unstable` will be deprecated and people seeking for stability can use `stable`.
- We should add description of the practice to both contributing docs and installation docs.

-------

Related also to #440.

**Comment by pksunkara** [comment]
👍

**Comment by honzajavorek** [comment]
Starting a transitional period - introduced the `stable` tag:

```
$ npm dist-tag ls
latest: 1.0.11
stable: 1.0.11
unstable: 1.1.0-pre.4
```

**Comment by honzajavorek** [comment]
Proposal on how the warning could work:

<img width="528" alt="screen shot 2016-06-09 at 17 44 53" src="https://cloud.githubusercontent.com/assets/283441/15936085/f2017eea-2e69-11e6-9767-2aaeb8739d43.png">

**Comment by honzajavorek** [comment]
I suggest we add the warning now, but we switch the behavior no earlier than with next major release, so people aren't surprised. It's basically a "breaking change" sort of thing.

**Comment by honzajavorek** [comment]
Dredd version 1.1.0 should be released as

```
$ npm dist-tag ls
latest: 1.1.0
stable: 1.1.0
unstable: 1.1.0
```

and should close this issue.

**Comment by honzajavorek** [comment]
This has been put into action, hence I'm closing this as implemented.
