### ISSUE TITLE
Testing should validate off of MSON Properties as well as schema

### ISSUE THREAD

**Issue by donbobbo4** [apiaryio/dredd#498]
Testing should validate off of MSOM Properties as well as schema.  Here is the current rules but think if  MSOM properties are defined then it should validate schema.  Apiary is already generating a schema based off of these properties. 

**Expectations**
There are some automatically-generated expectations on HTTP responses based on examples in the blueprint with the use of Gavel.js library. Please refer to Gavel rules if you want to know more.

**Headers Expectations**
- All headers given in example must be present in the response
- Only values of headers significant for content negotiation are validated
- All other headers values may differ

**Body Expectations**
- All JSON keys on any level given in the example must be present in the response JSON
- All JSON values may differ
- Response JSON values must be of the same JSON primitive type
- Arrays may have additional items, type or structure is not validated
- Plain text must match perfectly
- If JSON Schema v4 or JSON Schema v3 is given in the blueprint, JSON response must be valid against this schema and JSON example is ignored

**Comment by honzajavorek** [comment]
@donbobbo4 I'm afraid I don't understand your issue very well. We want to better document it (see https://github.com/apiaryio/dredd/issues/496), but Dredd goes like this:

1. If response was defined in the API Blueprint with `+ Schema` section containing JSON Schema, then such schema used for validation.
2. If response was defined in the API Blueprint by example and there's no `+ Schema` section, [gavel.js](https://github.com/apiaryio/gavel.js) takes the example and checks whether the real response has at least object properties of the same names.
3. If response was defined in the API Blueprint by `+ Attributes` (a.k.a [MSON](https://github.com/apiaryio/mson)), then API Blueprint parser generates both example and schema and Dredd uses the generated schema for validation.

As of now validation of headers is done by checking whether all documented headers are present in the real response (i.e. headers with the same names are present). Only values of headers significant for content negotiation are validated also by value.

**Comment by honzajavorek** [comment]
The behavior was documented (https://github.com/apiaryio/dredd/issues/496) and there's no follow up from @donbobbo4. Closing this for now.
