### ISSUE TITLE
Document why CoffeeScript is not a dev dependency

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#502]
It's because of hooks. See #500.

**Comment by pksunkara** [comment]
Ideally hooks should be converted to js before publishing dredd and thus making coffee-script dev only dependency.

**Comment by honzajavorek** [comment]
@pksunkara I believe the reason why hooks in Dredd contain `require 'coffee-script/register'` is to support user-provided hooks written in Coffee Script. So it has nothing to do with publishing.

Nice solution to that could be to provide a way to specify transpilers as arguments (i.e. the same way as Mocha or other JavaScript test frameworks). That would touch also direct Babel support https://github.com/apiaryio/dredd/issues/391.
