### ISSUE TITLE
Add the ability to specify hooks based on parameters in the URI template

### ISSUE THREAD

**Issue by brettneese** [apiaryio/dredd#508]
We have an issue where we have several nested resources, and in order to properly test them, we need to be able to specify a hook for all transactions with certain parameters. 

For instance, if the url is 

`/forms/{formId}/questions/{responseId}`

We can't actually get to anything past the {formId} without first inserting a form and specifying it. (http://dredd.readthedocs.io/en/latest/hooks-nodejs/#sharing-data-between-steps-in-request-stash)

We could write a hook for _every_ transaction involving nested resources, but that would be very un-DRY (wet?) and the code is so generic that it seems like even specifying a long list of transaction names and calling a function in each one of those would be a painful exercise. Even specifying an array of transaction names would be fairly annoying.

I'd like to propose -- and I will probably build for our own sake, but I'd appreciate community input here -- the ability to specify hooks not just based on transaction name, but on parameters in the URI template.  

For instance, for us, we would like to be ability to do a `beforeAllTemplate('{formID}')` and run it before any transaction with a `{formId}`. 

We think this would be pretty easy to implement, but what are some "gotchas" we should look out for? And is this kind of thing really necessary, or are we missing something?

(tagging my colleague @mnaughto for input as well)

**Comment by honzajavorek** [comment]
@brettneese I didn't have an immediate idea on how to solve your problem when I was first reading it. But now I got back to this issue and I've got an idea. Do you think that multiple hooks like following would work for you?

```js
hooks.beforeEach(function(transaction, done) {
  if (transaction.fullPath.indexOf('{formID}') > -1) {
    // alter transaction.fullPath and transaction.request.uri
  }
});
```

**Comment by honzajavorek** [comment]
This is a workaround for #227 not being done, basically. I'd say documenting the solution in a comment here is enough, not sure if this is such a common case that people need a dedicated example in Dredd docs.
