### ISSUE TITLE
Support for http(s)_proxy

### ISSUE THREAD

**Issue by ChrisWeiss** [apiaryio/dredd#51]
it doesn't appear that dredd leverages http_proxy or https_proxy when doing it's web calls to the API endpoint.

**Comment by honzajavorek** [comment]
Related: https://github.com/apiaryio/dredd/issues/591

**Comment by weejames** [comment]
It would be great to see this made available. The lack of this makes Dredd difficult to use behind our company proxy.

**Comment by honzajavorek** [comment]
This is going to be implemented 🎉 I'd appreciate all of you commenting here (and adding @alex-glv from #591) - do you think [this kind of support](https://github.com/request/request#proxies) would be sufficient to fulfill your dreams? 🙂

**Comment by honzajavorek** [comment]
Support for HTTP(S) proxy has been implemented in Dredd [v3.3.0](https://github.com/apiaryio/dredd/releases/tag/v3.3.0). See [documentation](https://dredd.readthedocs.io/en/latest/how-it-works/#using-https-proxy) on how to use it.
