### ISSUE TITLE
Newest prelease not published to npm

### ISSUE THREAD

**Issue by ddelnano** [apiaryio/dredd#517]
Sorry to keep annoying you about this @honzajavorek but I am trying to merge a PR I have with an example with a sample go app using dredd.  I saw it was tagged on Github but trying to install it does not work.

<img width="1440" alt="screen shot 2016-06-08 at 8 13 22 pm" src="https://cloud.githubusercontent.com/assets/5855593/15915226/882062f2-2db5-11e6-804a-ed59ce77cc49.png">

**Comment by ddelnano** [comment]
Didn't realize that the tag was made but not on master like i thought.

**Comment by honzajavorek** [comment]
@ddelnano Sorry about the delay, we're trying to perform the release in https://github.com/apiaryio/dredd/pull/516, but it got delayed again by an issue in hooks tests.

**Comment by ddelnano** [comment]
yea no problem partially my fault with that hooks delay.  I am looking into that as well

**Comment by honzajavorek** [comment]
Already addressed in ac8c695, I hope, waiting to see the tests when they spin up.
