### ISSUE TITLE
Dredd should be able to consume documents with Windows newlines

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#518]
- Currently, API Blueprint parser isn't able to consume Windows newlines.
- To seamlessly support Windows, we should be able to load such document in Dredd.
- The problem is, if we automatically replace the newlines, we may end up having sourcemaps of annotations etc. wrong in comparison with the original document user provided.

**Comment by zdne** [comment]
For the record the root cause is in the underlaying parser https://github.com/apiaryio/snowcrash/issues/29

**Comment by jch254** [comment]
Pls pls pls!

**Comment by phenixiim** [comment]
Hi there, what's the status? We have also problem with \r:
Parser error in file '../apiary/position.md': (error code 2) the use of carriage return(s) '\r' in source data isn't currently supported, please contact makers on line 1

**Comment by honzajavorek** [comment]
The status is solely dependent on whether [Drafter](https://github.com/apiaryio/drafter) team introduces this feature or not. According to what @w-vi told me, until they drop [sundown](https://github.com/vmg/sundown) as a dependency, this cannot be done in any way.

**Comment by phenixiim** [comment]
Ok, thanks

S přátelským pozdravem a přáním hezkého dne / Best regards
Dalibor Jaroš
+420 773 740 852

Dne 06/01/2017 v 11:45 Honza Javorek napsal(a):

**Comment by honzajavorek** [comment]
Possible workaround would be to convert the document to UNIX newlines before testing by Dredd. You could create a script along the lines of this (batch file, untested):

```batch
REM See http://stackoverflow.com/a/27844521/325365
TYPE apiary.apib | MORE /P > apiary-unix.apib
dredd apiary-unix.apib %*
```

The `apiary-unix.apib` file would also be in your `.gitignore`. While some source maps could be off, I don't think they play such an important role in Dredd output, so it's not that likely you would have any problems reading the test reports.

**Comment by honzajavorek** [comment]
@kylef mentioned in Dredd, we could try to come up with an internal workaround:

> There could be some kind of work around in Dredd, such as replacing `\r` with `\u{000b}` and thens stripping `\u{000b}` from the bodies or even converting them back to `\r`  
> perhaps it would end up in other parts though, might be tricky to remove them from everywhere  
> obviously horrible, but probably works:  
> ```
> JSON.parse(JSON.stringify(drafter.parseSync(source.replace('\r', '\u{000b}'))).replace('\u{000b}', '\r'))
> ```

Noting this down here in case someone would like to work on it.

**Comment by phenixiim** [comment]
Thank you very much for you effort, we solved it manually while changed 
CLRF to LF for each .md file.  But next, we were stopped by not fully 
function dredd_hooks on windows anyway.

BUt thanks for that great tool as Dredd is, CI works perfectly at debian 
server.

S přátelským pozdravem a přáním hezkého dne / Best regards
Dalibor Jaroš
+420 773 740 852

Dne 06/01/2017 v 14:50 Honza Javorek napsal(a):

**Comment by honzajavorek** [comment]
Glad to hear that! Adding full support for Windows is on our roadmap, let's see how it goes. Hooks can be tricky 😄 If you didn't completely give up on running Dredd on Windows, [see this section in docs](http://dredd.readthedocs.io/en/latest/installation/#windows-support).

**Comment by honzajavorek** [comment]
Note - there is a nice workaround mentioned here: https://github.com/apiaryio/snowcrash/issues/29#issuecomment-289614192

**Comment by litingjun2015** [comment]
`awk '{ sub("\r$", ""); print }' api-description.apib > api-description.apib-unix.apib`

is tested under windows.

**Comment by honzajavorek** [comment]
I think this is an issue of the underlying parser Dredd can do nothing about. If Dredd attempted any preprocessing, the source maps would be off, etc. Workarounds exist. I'm closing this issue.
