### ISSUE TITLE
Support for binary data

### ISSUE THREAD

**Issue by pickerflicker** [apiaryio/dredd#52]
My api serves images inline, so the body contains actual data instead of json.  In this case, I only want to validate that a non-0 body size is returned with the expected content type.

**Comment by cilf** [comment]
hey guys,
the suggested workaround is not working for me :-/ 

I have a 
```
### Get photo [GET]

+ Response 200 (image/jpeg)

    + Headers

            content-length: 6347
```
but it fails with **fail: body: Real and expected data does not match.**

Do you have any idea how to skip validating image data and only check the response status code?

**Comment by mikz** [comment]
Having the same issue. Would be nice to have at least a working workaround.

Looks like that would be properly supported by https://github.com/apiaryio/api-blueprint/issues/20

**Comment by honzajavorek** [comment]
Please see https://github.com/apiaryio/dredd/issues/87#issuecomment-187958406.
