### ISSUE TITLE
Dredd should support all +json media types, not just application/json

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#531]
See https://github.com/apiaryio/dredd/pull/529#discussion_r67153232 for details, but basically, there are many places in Dredd where we rely purely on `application/json`. We should ensure that Dredd is able to treat all `+json` media types as JSON, consistently everywhere in its stack.

**Comment by artem-zakharchenko** [comment]
I believe with the recent redesign of Gavel (the library that performs HTTP messages validation) Dredd should be able to consume `any+json` media types:

https://github.com/apiaryio/gavel.js/blob/84c514b0467f1dc53ec186a50caa6e9934dd4514/lib/units/validateBody.js#L13-L22

> Mainly the `mediaType.suffix === 'json'` part

Gavel itself has a [unit test for body validation of `hal+json` content type](https://github.com/apiaryio/gavel.js/blob/84c514b0467f1dc53ec186a50caa6e9934dd4514/test/unit/units/validateBody.test.js#L118). Do we need a test to verify the support of such media types in Dredd as well?

**Comment by artem-zakharchenko** [comment]
According to the latest release of [`fury-adapter-swagger`](https://github.com/apiaryio/api-elements.js/blob/c7b61228f370575739c5f806611e00e896296f5f/packages/fury-adapter-swagger/lib/media-type.js#L23), OA2 specs should be acceptable by Dredd even if a spec produces/consumes a media type other than `application/json` (basically, `any+json`).

This issue needs to have a test that verifies an OA2 `produces`/`consumes` with a different `+json` media type.
