### ISSUE TITLE
Go hooks not working

### ISSUE THREAD

**Issue by grounded042** [apiaryio/dredd#537]
I cannot seem to get Go hooks to work. It seems to be wanting to run the `go` command instead of running goodman. I compile my hooks to a binary named `hooks`.

The command I run is: `dredd blueprint.apib http://localhost:3333 --language go --hookfiles ./hooks`
And the output I get is:
```
info: Beginning Dredd testing...
info: Found Hookfiles: ./hooks
info: Spawning `go` hooks handler
info: Hook handler stderr: go: unknown subcommand "./hooks"
Run 'go help' for usage.

error: Hook handler 'go' exited with status: 2
error: Hook handler 'go' exited with status: 2
```

**Comment by ddelnano** [comment]
@grounded042 have you checked out the complete worked out [example](http A://github.com/snikch/goodman/example) in the Go hooks repo?  Also if you had previously used the Go hooks before the made rewrite was done you are using an updated version that must be upgraded. 

Did you install the goodman hook binary to your $GOPATH? And what version of dredd are you using? You must use a recent version (see the example).

**Comment by grounded042** [comment]
@ddelnano thanks for the quick reply. I followed the example from the goodman repo - I'm actually just trying to get that to work before writing my own hooks. This is my first time writing hooks using Go.

I've followed the steps for installing goodman, and running `$GOPATH/bin/goodman ./hooks` gets me output that says `Accepting connection`.

I am using version 1.0.11 of dredd.

**Comment by grounded042** [comment]
It looks like it's just straight running the `go` command as ` dredd blueprint.apib http://localhost:3333 --language go --hookfiles version` produces: `info: Hook handler stdout: go version go1.6.2 darwin/amd64`.

**Comment by ddelnano** [comment]
No problem, that dredd version is too old. The pre leases for 1.0.11 is too old which is kind of weird because you would think a pre release would come before the non pre one. Did you install from the package.json I pointed to?

Like I said before if you have an old version all dredd will do is run the --language flag as the command which in this case will just run the go command like you are experiencing.

**Comment by ddelnano** [comment]
Sorry mobile and release my second sentence did not make sense. Look at the dredd releases on the GitHub page, I was trying to say 1.0.11 is older than 1.0.11-pre.5.

**Comment by grounded042** [comment]
Ah, I didn't realize go was not supported in the current version on npm. Works like a charm now. 

Did I just miss something, or is it not documented that you need to run a newer version than the latest on npm?

**Comment by honzajavorek** [comment]
@grounded042 1.1.0 will be released very soon. In the pre-releases, we were developing #389 and basically, I incorrectly merged also @ddelnano's contributions into it. In an ideal world, I'd backport his contributions to Go into the `1.0.x` branch and I would release it separately as 1.0.12.

**Comment by honzajavorek** [comment]
Since we'll put #497 into action since 1.1.0, from that point you should get all new stuff in the latest release and only get stuck on something older if using `npm install dredd@stable`.

**Comment by grounded042** [comment]
Thanks for the info! Ya'll are awesome and this project is a huge help. Thanks for all the hard work and helping me get go hooks working!

**Comment by ddelnano** [comment]
@grounded042 I was expecting people to run the example and install dredd through the package.json provided in the example.  I will update the goodman repo to reflect that you must use a prerelease until 1.1.0 is out.

**Comment by honzajavorek** [comment]
@ddelnano Maybe just wait, we really really want to release 1.1.0 during today.

**Comment by ddelnano** [comment]
@honzajavorek ok cool, well I will still update the docs, but to say that 1.1.0 is required.  But I will wait until that is released.
