### ISSUE TITLE
Default value of a parameter is not used for a request in version 1.1

### ISSUE THREAD

**Issue by jakubzapletal** [apiaryio/dredd#541]
In the version `1.0.11` this was using a default value for sending a request:

```
## Retrieve balance [GET]
+ Parameters
    + person_id (number, required, `1`)
+ Request
    + Parameters
        + person_id
```

in the version `1.1.0` it is not sending that anymore and the parameter value must be specified:

```
## Retrieve balance [GET]
+ Parameters
    + person_id (number, required, `1`)
+ Request
    + Parameters
        + person_id: 1
```

For me, the behaviour of using the default value makes more sense.

**Comment by honzajavorek** [comment]
Hi, I'm sorry for a rather late response. There were some changes in how sample vs. default values are being picked up.

You are using older syntax for parameters. The API Blueprint format transitioned to the [MSON](https://github.com/apiaryio/mson) format for parameters notation, so I'd better provide my examples using that. Also, request-specific parameters are work in progress and they're rather experimental feature as of now. What are your exact intentions?

```
## Retrieve balance [GET]
+ Parameters
    + person_id: 1 (number, required)
```

This will mean the `person_id` URI (either path or query) parameter is required, it should be number and the value `1` is a sample value of the parameter.

```
## Retrieve balance [GET]
+ Parameters
    + person_id: 1 (number, default)
```

This will mean the `person_id` URI parameter is optional, it should be number and the value `1` is a default value of the parameter if not specified.

```
## Retrieve balance [GET]
+ Parameters
    + person_id: 1 (number)
        + Default: 42
```

This will mean the `person_id` URI parameter is optional, it should be number and the value `1` is a sample value of the parameter. Moreover, [this notation provides also default value](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#45-default), which says that if not specified, the parameter will default to `42`.

In Dredd, sample values now take precedence over the default ones. If you want Dredd to use default value, do not specify any sample values. If you want the documentation to specify default value, but you'd rather Dredd to use a different one for testing, provide it as a sample value. Note there are [brand new docs on this topic](http://dredd.readthedocs.io/en/latest/how-it-works/#uri-parameters).

**Comment by honzajavorek** [comment]
@jakubzapletal Any updates on this?

**Comment by jakubzapletal** [comment]
Hi @honzajavorek, thanks for the explanation and it makes sense what you described. I think that works as should be. Thank you

**Comment by honzajavorek** [comment]
Thanks! 👍
