### ISSUE TITLE
Provide scripts alternative for Windows

### ISSUE THREAD

**Issue by zdne** [apiaryio/dredd#55]
Scripts in the [`/scripts`](https://github.com/apiaryio/dredd/tree/master/scripts) are *nix (OS X)-only. 

The goal is to provide the functionality on Windows so I can run

```
$ npm install
$ npm test
```

On Windows as well.

https://www.npmjs.org/doc/misc/npm-scripts.html

Related to #47

**Comment by netmilk** [comment]
Related  to #204

**Comment by honzajavorek** [comment]
With https://github.com/apiaryio/dredd/pull/737, both `npm install` and `npm test` should work on Windows. There are going to be some *NIX-specific scripts, but only those related to the Travis CI build runtime (Semantic Release, Coveralls), which is fine, I think.

When https://github.com/apiaryio/dredd/pull/737 gets merge, I'm going to close this issue.
