### ISSUE TITLE
Fallback to default value for required parameters if the example value is not present

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#555]
I'm proposing to adjust `dredd-transaction`'s [parameter expander](https://github.com/apiaryio/dredd-transactions/blob/5f17f5ae5ce1f637fc1e2dabb0c05370530e80be/src/expand-uri-template-with-parameters.coffee#L43) to fall back to the parameter default value when example value is not present and emit a warning even though it doesn't make a lot of sense from the API specification standpoint. 

In Swagger/OAI there's no way how to express example parameter value and we're using this pattern in Swagger/OAI header parameters anyways. It could help with the example/default parameter value in the API Blueprint during onboarding to Dredd.

Possibly solving: #540 #541

**Comment by honzajavorek** [comment]
The change is not propagated to Dredd yet, it's only implemented in dependency now. Hence I'm reopening this not to confuse anyone about current state of things.
