### ISSUE TITLE
Do not parse and validate body if no expectations are set and response content-length is zero or not present

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#556]
I propose to do not try to parse and validate the body response in case the response `content-length` header value is `0` and the expected `body` or `bodySchema` is empty.

At the moment when your API response has JSON content type (`application/json` etc) but empty body (empty string - zero characters) Dredd tries to parse the body and it results slightly not understandable error `fail: body: Real body "Content-Type" header is "application/json" but body is not a parseble JSON.`

The zero `content-length` header is indicating the intent to do not send any data and we shouldn't expect any and assume it's ok.

Here is a temporary workaround solution with user of hooks:

``` js
var hooks = require('hooks');


// Do not parse and validate response body if the expected body and schema is empty and the response 
// header content-type is zero or not present regardless the response content-type
hooks.beforeEachValidation(function(transaction){
  var body = transaction['expected']['body'];
  var bodySchema = transaction['expected']['bodySchema'];

  var isBodyEmpty = body == null || body == undefined || body == ''
  var isBodySchemaEmpty = bodySchema == null || bodySchema == undefined || bodySchema == ''

  if(isBodyEmpty && isBodySchemaEmpty){

    //caseless lookup for the content-length header key
    var contentLengthKey = null;
    var responseHeaderKeys = Object.keys(transaction['real']['headers']);
    responseHeaderKeys.forEach(function(responseHeaderKey){
      if(responseHeaderKey.toLowerCase() == 'content-length'){
        contentTypeKey = responseHeaderKey;
      };
    });

    var contentLength = null;
    // if response has content-length
    if(contentLengthKey !== null){
      var contentLength = parseInt(transacation['real']['headers'][contetLengthKey],10);
    }

    if(contentLengthKey === null || conetntLength === 0){
      //skip the body validation the way mentioned in https://github.com/apiaryio/dredd/issues/510
      hooks.log("skipping body validation")
      transaction['expected']['body'] = undefined;
      transaction['expected']['bodySchema'] = undefined;
    };
  };
});
```

**Comment by mcurry7** [comment]
**I have attempted to use this and it still fails. The goal is to get an audio file to be called successfully after removing the binary file output to the body.
With one hook I remove the body of the response:**
`hooks.beforeValidation('Call Recordings > Access Call Recordings > Get - Recording', function (transaction) {
  transaction.real.body = '';
});`

**This succeeds in setting the response body to blank.
I then run the above hook to force dredd to not parse. However it still tries to parse and throws the error:**

>error: Error: Parse Error
    at CleartextStream.socketOnData (http.js:1639:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at CleartextStream.read [as _read] (tls.js:520:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at CleartextStream.read [as _read] (tls.js:520:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

**Which causes this:**

![image](https://cloud.githubusercontent.com/assets/19844853/17065090/224babca-4ffd-11e6-9e86-55364f38a5f5.png)

**Here are the headers:**

+ Request
    + Headers

            Authorization: apikey (required in string form)
            accept-encoding:gzip, deflate, sdch
            accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8

+ Response 200
    + Headers

            content-description:File Transfer
            content-transfer-encoding:binary
            Content-Type:audio/wav
            content-disposition: attachment; filename=out-1001-7203986241-2016-06-17-11-12-59-FunctionalTest.wav
            pragma:public
            Connection:keep-alive
            Vary:Accept
            Cache-Control:private, must-revalidate
            Expires:0

**Comment by mcurry7** [comment]
This is also the same behavior I have been experiencing with the calls that i have that are returning a response of 204. There is inherently no body and the error happens before the hook above runs. Here is an example of the output 

    error: DELETE /v1/core/FunctionalTest/dynamicagents/200 duration: 1241ms
    error: Error: Parse Error
        at CleartextStream.socketOnData (http.js:1639:20)
        at CleartextStream.read [as _read] (tls.js:514:12)
        at CleartextStream.Readable.read (_stream_readable.js:341:10)
        at EncryptedStream.write [as _write] (tls.js:369:25)
        at doWrite (_stream_writable.js:226:10)
        at writeOrBuffer (_stream_writable.js:216:5)
        at EncryptedStream.Writable.write (_stream_writable.js:183:11)
        at write (_stream_readable.js:602:24)
        at flow (_stream_readable.js:611:7)
        at Socket.pipeOnReadable (_stream_readable.js:643:5)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:427:10)
        at emitReadable (_stream_readable.js:423:5)
        at readableAddChunk (_stream_readable.js:166:9)
        at Socket.Readable.push (_stream_readable.js:128:10)
        at TCP.onread (net.js:529:21)

    hook: skipping body validation

    info: Displaying failed tests...

    fail: DELETE /v1/core/FunctionalTest/dynamicagents/200 duration: 1241ms
    fail: 
    request: 
    method: DELETE
    uri: /v1/core/FunctionalTest/dynamicagents/200
    headers: 
        Content-Type: text/plain
        authorization: apikey (required in string form)
        accept-encoding: gzip, deflate, sdch
        accept: application/json, text/javascript, */*; q=0.01
        User-Agent: Dredd/1.1.0 (Linux 3.10.0-123.4.2.el7.x86_64; x64)
        Authorization:  6QAhVNNE-sv6j-UGzK-wt6ioCSESBQg
    
    body: 
        
    
    
    expected: 
    headers: 
    
    body: 
    undefined
    statusCode: 204
    bodySchema: undefined


    actual: 
    statusCode: 204
    headers: 
        server: nginx/1.10.0
        date: Fri, 22 Jul 2016 19:31:06 GMT
        content-type: application/json; charset=utf-8
        content-length: 0
        connection: keep-alive
        vary: Accept
        cache-control: no-cache, must-revalidate
        expires: 0
        x-powered-by: Luracast Restler v3.0.0rc3
        content-language: en

    body:

**Comment by duczen** [comment]
I don't believe this work around will work. I added a log entry as the first line in this hook:

```
hooks.beforeEachValidation(function(transaction) {
    hooks.log("in beforeEachValidation")
    ...
});
```


The error occurs before the function is called:

```
error: Error: Parse Error
  at Error (native)
  at Socket.socketOnData (_http_client.js:361:20)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at TCP.onread (net.js:543:20)

hook: in beforeEachValidation
hook: skipping body validation
```

There are also 3 typos in the snippet above.

`var contentLength = parseInt(transacation['real']['headers'][contetLengthKey],10);`

`transacation` and `contetLengthKey`

`if(contentLengthKey === null || conetntLength === 0){`

and `conetntLength`

**Comment by honzajavorek** [comment]
Thanks for correcting! This is an issue which is very high on our task list, but there are still some details we would like to discuss before we proceed to fix this. With @netmilk we composed following break down of the problem:

### The issue

Dredd currently has inconsistent behavior when it comes to validating empty request or response bodies. Even when it behaves in the right way, it doesn't help user to understand what's the actual problem and how they can solve it.

### Possible Scenarios

Following table show how Dredd should correctly behave in various scenarios. However, it's still subject to be discussed. The "Content Length" means value of `Content-Length` header provided by user in the API description. N/A means user didn't provide any specific value in the description for given HTTP header.

| Body | Content Type | Status Code | Content Length | Dredd's Verdict | Explanation |
|:----- |:--------------|:-------------|:----------------|:----------------|:------------|
| empty | text | any | 0 or N/A | ✅ | empty string is valid text |
| empty | N/A | any | 0 or N/A | ✅ | when Content-Type is not specified, Dredd assumes text and empty string is valid text |
| empty | json | any | 0 or N/A | ❌ | empty string is never valid JSON |
| empty | json | 204 | 0 or N/A | ❌ | empty string is never valid JSON |
| non-empty string | json | 204 | 0 or N/A | ❌ | response with 204 status code should not have body |

So in most cases, the solution is not to provide (erroneous) JSON Content-Type for empty bodies or to explicitly say it's `text/plain`:

```apib
FORMAT: 1A

# The Simplest API
## GET /message
+ Response 204
```

```apib
FORMAT: 1A

# The Simplest API
## GET /message
+ Response 204 (text/plain)
```

...instead of:

```apib
FORMAT: 1A

# The Simplest API
## GET /message
+ Response 204 (application/json)
```

I haven't done examples for Swagger yet - if someone would be able to contribute corresponding Swagger examples to this discussion, it would help a lot.

**At the same time, there should be available examples in documentation which work around the rules above (possibly using hooks), based on real world cases provided by Dredd users.** If you think you know about any right now, please share them here.

### Feedback?

What do you guys think about this? If Dredd worked correctly according to the table above, all covered by tests, would that work for you?

**Comment by ungrim97** [comment]
A server should return no content length header on a 204 response

From the HTTP RFC (7230):
>    A server MUST NOT send a Content-Length header field in any response
>    with a status code of 1xx (Informational) or 204 (No Content).  A
>    server MUST NOT send a Content-Length header field in any 2xx
>    (Successful) response to a CONNECT request (Section 4.3.6 of
>    [RFC7231]).

Also the response should always be terminated by the first empty line after the headers. A 204 MUST NOT have a message content.

From the HTTP RFC (7231):

> A 204 response is terminated by the first empty line after the header
> fields because it cannot contain a message body. 

I can't see anything about a Content-type on a 204 being erroneous (though that does make sense). That said it would seem that the best thing to do would be to:

Body  | Content Type | Status Code | Content Length | Dredd's Verdict | Explanation
---------|-------------------|------------------|----------------------|----------------------|----------------
empty | text | any | 0 or N/A | :white_check_mark: | empty string is valid text
empty | N/A | any |	0 or N/A | :white_check_mark: | when Content-Type is not specified, Dredd assumes text and empty string is valid text
empty | any | 204 | N/A | :white_check_mark: | Any empty body is valid for a 204
empty | json | any | 0 or N/A | :x: | empty string is never valid JSON
empty | json | 204 | 0 or N/A | :white_check_mark: | An empty body is always valid for a 204
non-empty string | any | 204 | any | :x: | response with 204 status code should not have body

**Comment by ungrim97** [comment]
This discussion is also valid for a 205 response and other responses that are explicitly no content

**Comment by honzajavorek** [comment]
Just for the record, links to spec for the 204 and 205 status codes:

- https://tools.ietf.org/html/rfc7231#section-6.3.5 - 204
- https://tools.ietf.org/html/rfc7231#section-6.3.6 - 205

The section about 205 has a whole paragraph about how the body should be treated :open_mouth: 

@ungrim97 The main difference between solution proposed by me and you, if I read it correctly, is that if the response is 204 (let's leave 205 for later now), then Content Type should be **ignored**, while my solution says it should be respected during validation.

Seems like it is the main point to discuss. The spec isn't crystal clear about this, which doesn't help much - I found no RFC saying exactly "when you have 204, do X with Content-Type". I'm not strongly opinionated about this and I can see how the clues you mention support your proposal.

Both options make sense in some way. We can also work with more granular verdicts - as in, it doesn't need to be only ✅ or ❌, but also "✅ with warning that this and this isn't a violation, but doesn't make much sense".

**Comment by ungrim97** [comment]
@honzajavorek Agreed.

Basically I believe that if the response is a 204 then the content-type is irrelevant (or that null is always valid).

A warning if you have a content-type with no content would certainly make sense.

**Comment by netmilk** [comment]
@ungrim97 @honzajavorek So I would suggest changing this

Body  | Content Type | Status Code | Content Length | Dredd's Verdict | Explanation
---------|-------------------|------------------|----------------------|----------------------|----------------
non-empty string | any | 204 | any | :x: | response with 204 status code should not have body

To:

Body  | Content Type | Status Code | Content Length | Dredd's Verdict | Explanation
---------|-------------------|------------------|----------------------|----------------------|----------------
non-empty string | any | 204 | any | :white_check_mark: with ⚠️  | response with 204 status code should not have body but Dredd's purpose is not to validate RFC7231 complience

**Comment by honzajavorek** [comment]
@netmilk But in that case, should it then validate according to the Content Type? I mean:


Body  | Content Type | Status Code | Content Length | Dredd's Verdict | Explanation
---------|-------------------|------------------|----------------------|----------------------|----------------
non-empty string | text | 204 | any | :white_check_mark:⚠️  | response with 204 status code should not have body (warning)
non-empty string, **valid** json | json | 204 | any | :white_check_mark:⚠️  | response with 204 status code should not have body (warning)
non-empty string, **invalid** json | json | 204 | any | :white_check_mark:⚠️  | response with 204 status code should not have body (warning)

versus


Body  | Content Type | Status Code | Content Length | Dredd's Verdict | Explanation
---------|-------------------|------------------|----------------------|----------------------|----------------
non-empty string | text | 204 | any | :white_check_mark:⚠️  | response with 204 status code should not have body (warning)
non-empty string, **valid** json | json | 204 | any | :white_check_mark:⚠️  | response with 204 status code should not have body (warning)
non-empty string, **invalid** json | json | 204 | any | :x:⚠️  | invalid JSON (error) & response with 204 status code should not have body (warning)

**Comment by netmilk** [comment]
Some points:
- We should point out we're talking about **Expected body** in the tables above - I updated them
- We should distinguish between 
  - *Empty string in the body* (`""`) - it's expected to have an empty string in the request or response body
  - *Empty expected body* - the body wasn't given in the AD - no expectation were set on the body

**Comment by bkuhl** [comment]
The temporary workaround of adding `+ Response 204 (text/plain)` did not work for me, even when adding `text/plain` as a Content-Type on the response.

**Comment by honzajavorek** [comment]
I'm sorry for pointing you wrong way. I'm afraid you'll have to use hooks then to fix this, e.g. like this: https://github.com/apiaryio/dredd/issues/468#issuecomment-256343379

**Comment by duczen** [comment]
Has anyone gotten this working with hooks? I tried a similar hook in js (above in this thread) and found the parse error is happening before the beforeEachValidation hook gets run.

**Comment by honzajavorek** [comment]
@duczen That's strange. The parsing happens in Gavel, which is triggered during validation.

**Comment by mcurry7** [comment]
If there is a hook line like so:

`hooks.beforeValidation('Group > Sub Group > Call', function (transaction) {
  var body = JSON.parse(transaction.real.body)
  delete body.config.log;
  transaction.real.body = JSON.stringify(body)
  hooks.log("Remove Log Object");
});`

 does the log line print after validation and run the hook before? That's the only explanation i could think of is that its some sort of delay.

**Comment by mcurry7** [comment]
It looks like the problem has to do with the way nodejs is handling it before hand and then the dredd issues occur.

**Comment by galenandrew** [comment]
@honzajavorek it's been a year since the last comment here…any update here?

**Comment by honzajavorek** [comment]
@galenandrew There has been no follow-ups to the design sessions we had and the tables we produced above. I currently have no ETA on when this gets our attention, but the "Epic" label means we recognize it as one of core Dredd problems, which definitely needs to get addressed.

**Comment by honzajavorek** [comment]
I propose following as a final solution. The ⚙️ symbol means that actual validation takes place.

| Expected Body | Expected Schema | Real Body | Content Type | Dredd's Verdict | Explanation |
| --- | --- | --- | --- | --- | --- |
| none or empty string | none or implying empty string | none or empty string | any  | :white_check_mark: | |
| none or empty string | none | non-empty | any | :white_check_mark: | no assertions = no validation |
| none or empty string | non-empty | any | any | ⚙️ | schema = validation | 
| non-empty | any | any | any | ⚙️ | body example = validation | 

#### Additional rules

If the expected body, expected schema, or real body are non-empty and the status code is 204 or 205, Dredd provides warning that such status codes should not have body according to RFC.

#### How to avoid body validation

Do not specify any body example or schema

#### How to force validation to require empty body

Do not specify body example. Specify schema implying an empty string, such as

```json
{"type": "string", "enum": [""]}
```

Even if you do not specify such schema, Dredd will warn in case of non-empty bodies of 204/205 HTTP status codes.

**Comment by ungrim97** [comment]
That behaviour matches my expectations

**Comment by honzajavorek** [comment]
I just found out [Gavel.js](https://github.com/apiaryio/gavel.js/) isn't able to validate primitive types like this:

```json
{"type": "string", "enum": [""]}
```

That means either

- that there will be no way to force validation of the empty response,
- or that we need to figure out how Gavel could support such use case,
- or that we need to figure out a different way user could signalize they want to force validation of the empty response.

🤔

**Comment by honzajavorek** [comment]
I found out that technically

```json
{"type": "string", "enum": [""]}
```

doesn't imply an empty string, but a string `""`, because that would be a representation of an empty string in JSON:

```
> JSON.parse('')
SyntaxError: Unexpected end of JSON input

> JSON.parse('""')
''
```

Also using JSON Schema implies the response should have JSON content type. I wonder whether there is any other way how a Dredd user could signalize they want to force an empty response 🤔

**Comment by honzajavorek** [comment]
Proposal (add 👍 to this comment if you think it's a good idea, comment if you disagree):

- No body and no schema in the API description means there are no assertions. No validation will happen, any response body will pass.
- No body and any schema will fail, because Gavel supports only JSON Schema as schema and there is no way to describe an empty response in JSON Schema
- In case anyone would want to force empty body validation, they can do so by hooks 🙂 It should be pretty simple:

```js
hooks.beforeValidation('My API > ...', function (transaction, done) {
  if (transaction.real.body) {
    transaction.fail = 'The response body must be empty';
  }
  done();
});
```

**Comment by ungrim97** [comment]
👍

**Comment by honzajavorek** [comment]
Rejoice! [v4.7.1](https://github.com/apiaryio/dredd/releases/tag/v4.7.1) brings the solution and new docs on this topic. Dredd should finally be able to correctly deal with empty bodies! 🎉

**Comment by honzajavorek** [comment]
Of course, thanks everyone involved! ❤️

**Comment by honzajavorek** [comment]
The docs: https://dredd.readthedocs.io/en/latest/how-it-works.html#empty-response-body

**Comment by plroebuck** [comment]
No one mentioned [section 3.3.3](https://tools.ietf.org/html/rfc7230#section-3.3.3) of RFC7230 which specifies how to determine message body length.
