### ISSUE TITLE
Provide example values in Swagger using a vendor specific property (x-example)

### ISSUE THREAD

**Issue by guillemcanal** [apiaryio/dredd#561]
Hi,

Is it possible to provide example values for `uri` and `query` request parameters using a vendor specific property (prefixed with `x-*`) ? 

`enum` is already used by Swagger UI and Swagger Editor ; It generate a dropdown list with specified values. So, it's impossible to test the API against user defined values.

**Comment by netmilk** [comment]
Hey @quillemcanal! Thank you for your thoughts! lThis is exactly what we plan to do. We're going to add `x-example` to the `parameter object` very soon. We also want to do a fallback to the `default` if no example is given (#555).

**Comment by guillemcanal** [comment]
Very nice! Can't wait!

**Comment by kylef** [comment]
@guillemcanal I think these changes would be outside of Dredd itself and actually in the Swagger adapter we use for converting Swagger to the [API Elements](http://api-elements.readthedocs.io) format that Dredd internally consumes.

The change should be as simple as adding the sample to the structure for Href within https://github.com/apiaryio/fury-adapter-swagger/blob/master/src/parser.js#L1182. It should just add the sample to the "value" part (example of an API Elements document with a Href sample: https://github.com/apiaryio/drafter/blob/master/test/fixtures/api/action-parameters.json#L55)

**Comment by honzajavorek** [comment]
@guillemcanal Would you be willing to work on this? I can provide you with pointers and any support you may need during implementation 🔨

**Comment by guillemcanal** [comment]
Since I really need it, yes of source ;) I'll be able to have a look this weekend. I'm not very found of coffeescript, but I can manage ;)

**Comment by honzajavorek** [comment]
@guillemcanal Great, thanks! I'm already working on https://github.com/apiaryio/dredd/issues/555 which should provide workaround. And yes, we're trying to write new stuff in plain JS as it started evolve :)

**Comment by honzajavorek** [comment]
@guillemcanal Any chance you had time to look into it?

**Comment by guillemcanal** [comment]
Not yet, I'll try to work on it this week.

**Comment by honzajavorek** [comment]
@guillemcanal Just in case you get back to this, I took care of it. It should bubble up the dependency chain and be published as part of Dredd soon. It turned out to be a bit more tricky after all :)
