### ISSUE TITLE
Can't install Dredd on Travis CI

### ISSUE THREAD

**Issue by RomainEndelin** [apiaryio/dredd#572]
Hi,

I've tried to setup Dredd with TravisCI, using the following script:

    language: ruby
    sudo: false
    rvm:
      - 2.3.1
    cache: bundler
    branches:
      only:
        - master
    before_install:
      - npm install -g dredd
    script:
      - bin/rake db:migrate RAILS_ENV=test --trace
      - bin/rspec
    after_success:
      - CI=travis dredd

However, I have the following error:

    $ npm install -g dredd
    - 
    > spawn-sync@1.0.15 postinstall /home/travis/.nvm/v0.10.36/lib/node_modules/dredd/node_modules/spawn-sync
    > node postinstall
    \ay take up to a minute)
    /npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"1.4.28"})
    npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"1.4.28"})
    npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"1.4.28"})
    npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
    -> protagonist@1.4.1 install /home/travis/.nvm/v0.10.36/lib/node_modules/dredd/node_modules/dredd-transactions/node_modules/fury-adapter-apib-parser/node_modules/protagonist
    > node-gyp rebuild
    make: Entering directory `/home/travis/.nvm/v0.10.36/lib/node_modules/dredd/node_modules/dredd-transactions/node_modules/fury-adapter-apib-parser/node_modules/protagonist/build'
      CXX(target) Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.o
    cc1plus: error: unrecognized command line option ‘-std=c++11’
    cc1plus: error: unrecognized command line option ‘-std=c++11’
    make: *** [Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.o] Error 1
    make: Leaving directory `/home/travis/.nvm/v0.10.36/lib/node_modules/dredd/node_modules/dredd-transactions/node_modules/fury-adapter-apib-parser/node_modules/protagonist/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Linux 3.13.0-40-generic
    gyp ERR! command "node" "/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/travis/.nvm/v0.10.36/lib/node_modules/dredd/node_modules/dredd-transactions/node_modules/fury-adapter-apib-parser/node_modules/protagonist
    gyp ERR! node -v v0.10.36
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok 
    npm ERR! protagonist@1.4.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the protagonist@1.4.1 install script.
    npm ERR! This is most likely a problem with the protagonist package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls protagonist
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.13.0-40-generic
    npm ERR! command "/home/travis/.nvm/v0.10.36/bin/node" "/home/travis/.nvm/v0.10.36/bin/npm" "install" "-g" "dredd"
    npm ERR! cwd /home/travis/build/RomainEndelin/product_manager_assessment
    npm ERR! node -v v0.10.36
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0
    The command "npm install -g dredd" failed and exited with 1 during .
    Your build has been stopped.

Unfortunately, I haven't been able to reproduce the mistake locally on my laptop, where Dredd is installed correctly.

Thanks

**Comment by ddelnano** [comment]
Try adding this [line](https://github.com/snikch/goodman/blob/master/.travis.yml#L2), I believe you are getting this failure because the default OS does not have a C++11 compiler installed by default.

**Comment by RomainEndelin** [comment]
Thanks a lot, it worked :+1: .

**Comment by netmilk** [comment]
@ddelnano Thanks for helping here! I'd like to keep this issue open, because it's just a workaround not resolution. The resolution is coming soon and it will be the use of `drafter.js` instead of compiled `protagonist`. It should solve this issue and speed up the install process tremendously.

**Comment by honzajavorek** [comment]
Yup, @netmilk's right that we're in the process of introducing compilation-free Dredd in one of soon-to-be issued PRs. Teaser: https://github.com/apiaryio/dredd-transactions/pull/51

**Comment by honzajavorek** [comment]
This was now fixed by #573.

**Comment by honzajavorek** [comment]
@RomainEndelin Could you please confirm this works for you now?

**Comment by RomainEndelin** [comment]
Yes, I've just removed the workaround (adding `dist: trusty`), and dredd installs perfectly. Thanks :)

**Comment by honzajavorek** [comment]
@RomainEndelin Great, thanks! 🎉

**Comment by iamharish** [comment]
Hi 

I'm seeing similar issue while trying to integrate with Travis using command

>   - npm install -g dredd@3.4.5

**Logs**
```
> node-gyp rebuild
make: Entering directory `/home/travis/.nvm/v0.10.36/lib/node_modules/dredd/node_modules/dredd-transactions/node_modules/fury-adapter-apib-parser/node_modules/drafter/node_modules/protagonist/build'
  CXX(target) Release/obj.target/libmarkdownparser/drafter/ext/snowcrash/ext/markdown-parser/src/ByteBuffer.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
cc1plus: error: unrecognized command line option ‘-std=c++11’
```

But it works when I tried below 

>   - npm install -g dredd@3.4.5 --no-optional

**Comment by honzajavorek** [comment]
@iamharish The errors should not fail your build though. Read [Why I'm Seeing node-gyp Errors?](https://dredd.readthedocs.io/en/latest/installation/#why-im-seeing-node-gyp-errors)
