### ISSUE TITLE
Vulnerability in minimatch

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#578]
There's a [vulnerability in `minimatch` library](https://snyk.io/vuln/npm:minimatch:20160620), which propagates to Dredd through other dependencies. I've

- Sent a PR to `html` dependency to solve this: https://github.com/maxogden/commonjs-html-prettyprinter/pull/11

- After some time nobody reacted to the PR, I created a fork of the project in [apiaryio/commonjs-html-prettyprinter](https://github.com/apiaryio/commonjs-html-prettyprinter) and Dredd will depend on that (I re-created the PR to upstream to go from our fork: https://github.com/maxogden/commonjs-html-prettyprinter/pull/12)

**Comment by galenandrew** [comment]
@honzajavorek looks like maxogden/commonjs-html-prettyprinter#14 has been merged, so this issue can be resolved by updating to `html@1.0.0` (this would close #589).

**Comment by honzajavorek** [comment]
@galenandrew Ah, we just merged our own crafted fix. Good! I'll put back upstream dependency.
