### ISSUE TITLE
Dot reporter is not working

### ISSUE THREAD

**Issue by aledeg** [apiaryio/dredd#594]
In #593, I was referred to the dot reporter to do what I was requesting.

I've tried to make it work without any luck.
When I run it, dredd stalled on ```info: Beginning Dredd testing...```.
I've tried the other reporters and they are all working. Even the ```nyan``` reporter ;)

Here is the command I sent:
```
dredd sales.apib 'http://127.0.0.1:8888/app_dredd.php' --server 'php -S 127.0.0.1:8888 -t web/' --language vendor/bin/dredd-hooks-php --hooks-worker-timeout 50000 --hooks-worker-connect-timeout 15000 --hooks-worker-after-connect-wait 1000 --hooks-worker-term-timeout 50000 --hookfiles tests/dredd/BoilerPlateHook.php --hookfiles 'tests/dredd/Sale/*Hook.php' --reporter dot
```

**Comment by honzajavorek** [comment]
I was able to reproduce this by

```
$ dredd test/fixtures/single-get.apib http://example.com --reporter=dot
info: Beginning Dredd testing...
```

and that's it, no other output. `nyan` works, `apiary` works, `cli` works. `markdown` and `junit` create `report.md` and `report.xml`, respectively. According docs there are no other available reporters, so the only one broken now seems to be the dot reporter.

**Comment by honzajavorek** [comment]
@aledeg Thanks for filing the issue! This really helps! 🎈

**Comment by aledeg** [comment]
@honzajavorek my pleasure. I am glad you reproduced the bug. I was completely off :)
