### ISSUE TITLE
API Project Subdomain isn't clear

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#611]
> the documentation says to add the environment variable: `APIARY_API_NAME=<API Project Subdomain>` ... so I put in the full URL to my project and my dredd test failed with no obvious error message. So, I removed the url and put the project name and it worked. Might want to change `<API Project Subdomain>` to just `<API Project Name>`

**Comment by artem-zakharchenko** [comment]
Good call, @honzajavorek. I've address that in the #1573. Please take a look when you have a minute. Thank you.
