### ISSUE TITLE
Allow filtering the resources/actions/transactions to test

### ISSUE THREAD

**Issue by kylef** [apiaryio/dredd#619]
It would be really handy while iterating over my API implementation to be able to only test a subset of the resources/actions in my ADD with dredd.

Usage:

```shell
$ dredd --filter-path /parser
$ dredd --filter-method POST
```

Not sure how far you can go so I'd suggest keeping it simple without adding a bunch of mechanisms for filtering for various parameters. Path would be the most useful to me, perhaps going into a specific transaction too.

**Comment by kylef** [comment]
I just noticed the `--only` option already allows filtering by transaction so going to close my silly feature request which is already implemented.

**Comment by honzajavorek** [comment]
🎯
