### ISSUE TITLE
Add way to retry transaction if it fails

### ISSUE THREAD

**Issue by BrydenR** [apiaryio/dredd#621]
I don't know if this would actually be feasible/useful for many people, but I have found that there are certain transactions that fail and the rest of the test is more or less useless. I would like to be able to tell dredd to take the last transaction and redo it if criteria are met (e.g. `transaction.results.test === "fail"`). This issue may also just be me not able to figure out how to do this, but I have not seen any information on it, so this would be a good place to get solid steps on retrying one transaction if certain conditions are met.

Also, thanks so much for creating dredd!

**Comment by honzajavorek** [comment]
@BrydenR Thanks for the suggestion! Could you please elaborate on your use case and why do you need this? What are you trying to achieve?

**Comment by BrydenR** [comment]
In my case, there is a graphical front end that needs to load an object, otherwise all tests after will fail (because they use the object). Due to some backend problems, the object is currently not loading each time. Each time the object fails to load, the test suite needs to be re-run.

The front end continues to be stable because of retry commands, but the api call just fails. Using Selenium, we have graphical tests. In Selenium, this problem of the object not loading is taken care of by a timer (for 60 seconds) and if it fails, retries the individual testcase (allowing for greater flexibility to deal with back-end problems).

Specifically what I would be looking for is a way to tell dredd to ignore the results of the last transaction, and send out the transaction again. Ideally, I would like to be able to run a transaction until a timeout, or a success, and have dredd only record the last transaction. 

basic pseudocode:
```
send transaction
if transaction failed
    retry transaction
else
    continue testing
```

Using nodejs, I could implement this code, but the dredd reporter would still report it as a failure, which makes the automatic testing less automatic, as someone would have to check each result.

**Comment by honzajavorek** [comment]
Closing in favor of https://github.com/apiaryio/dredd/issues/995
