### ISSUE TITLE
[Feature request] support wildcards in --only parameter

### ISSUE THREAD

**Issue by aledeg** [apiaryio/dredd#622]
Currently, if I have an apib file which describes multiple APIs, and I want to test a single one, I cannot do something similar to this:
```sh
dredd --only 'Foo > *'
```

My only options are:

- split the apib file
- use a command similar to this:
```sh
dredd --only 'Foo > Foo Collections > List Foo' --only 'Foo > Foo Collections > Add Foo' --only 'Foo > Foo > Get Foo' --only 'Foo > Foo > Update Foo' --only 'Foo > Foo > Delete Foo'
```

It would be neat if I could use wildcard syntaxes:
```sh
# Filter on the whole API
dredd --only 'Foo > *'

# Filter on collections
dredd --only 'Foo > Foo Collections > *'

# Filter on items
dredd --only 'Foo > Foo > *
```

**Comment by honzajavorek** [comment]
Related to #248

**Comment by aledeg** [comment]
@honzajavorek My bad! I didn't see it.

**Comment by honzajavorek** [comment]
@aledeg No problem! It's a bit different use case. I wanted to leave this open for that reason. However, you're right it's better to concentrate the ideas around it under a single issue. Would you mind to share this idea for `--only` in a comment under #248?

**Comment by aledeg** [comment]
@honzajavorek sure
