### ISSUE TITLE
Remove sensitive data from the reports

### ISSUE THREAD

**Issue by netmilk** [apiaryio/dredd#623]
In case the request or the response contains some sensitive data I want to be able to remove them before they are sent to the reporter in order to avoid leaking of sensitive data.

This should be possible by modifying the `test` object in the [`transaction`](https://dredd.readthedocs.io/en/latest/hooks/#transaction-object-structure) passed to the `after` or `afterEach` hook. The test object is passed to reporters and reporters transform this object to CLI output, the Apiary reporter etc...

But it doesn't work at this moment because [if the test fails the `failed` event is triggered before](https://github.com/apiaryio/dredd/blob/master/src/transaction-runner.coffee#L638) the `after` and `afterEach` hooks. This means if the test fails, test data are sent to the reporters before executing `after*` hooks. If this will be fixed, the reporter data sanitization hooks should work as expected.

Current behavior violates the documented [execution lifecycle](https://dredd.readthedocs.io/en/latest/how-it-works/#execution-life-cycle).

This should fix this one as well: https://github.com/apiaryio/dredd/issues/421

**Comment by honzajavorek** [comment]
Let's see if docs-first approach could help us to discuss the interface before we get the implementation done. I'm proposing this new section to the [How-To Guides](http://dredd.readthedocs.io/en/latest/how-to-guides/) page in the documentation:

⚠️ **The proposal below is still work in progress, wait for final version before commenting** ⚠️

## Removing sensitive data from test reports

Sometimes your API sends back sensitive information you don't want to get disclosed in [Apiary Tests](http://dredd.readthedocs.io/en/latest/how-to-guides/#using-apiary-reporter-and-apiary-tests) or in your CI log. In that case you can use [Hooks](http://dredd.readthedocs.io/en/latest/hooks/) to do sanitation:

### Sanitation of the Entire Request Body

```js
after('Resource > Update Resource', function(transaction, done) {
  transaction.test.request.body = '';
  done();
});
```

### Sanitation of the Entire Response Body

```js
after('Resource > Update Resource', function(transaction, done) {
  transaction.test.actual.body = '';
  transaction.test.expected.body = '';
  done();
});
```

### Sanitation of a Request Body Attribute

```js
after('Resource > Update Resource', function(transaction, done) {
  var body = JSON.parse(transaction.test.request.body);
  delete body.token;
  transaction.test.request.body = body;
  done();
});
```

### Sanitation of a Response Body Attribute

```js
after('Resource > Update Resource', function(transaction, done) {
  var body;

  body = JSON.parse(transaction.test.actual.body);
  delete body.token;
  transaction.test.actual.body = body;

  body = JSON.parse(transaction.test.expected.body);
  delete body.token;
  transaction.test.expected.body = body;
  
  done();
});
```

### Sanitation of Request Headers

Following example uses the [caseless](https://www.npmjs.com/package/caseless) library to ensure we're dealing with HTTP header names in case-insensitive way.

```js
var caseless = require('caseless');

after('Resource > Update Resource', function(transaction, done) {
  var headers = caseless(transaction.test.request.headers);
  var name = headers.has('Authorization');
  delete headers[name];
  transaction.test.request.headers = headers;
  done();
});
```

### Sanitation of Response Headers

Following example uses the [caseless](https://www.npmjs.com/package/caseless) library to ensure we're dealing with HTTP header names in case-insensitive way.

```js
var caseless = require('caseless');

after('Resource > Update Resource', function(transaction, done) {
  var headers;
  var name;

  headers = caseless(transaction.test.actual.headers);
  name = headers.has('Authorization');
  delete headers[name];
  transaction.test.actual.headers = headers;

  headers = caseless(transaction.test.expected.headers);
  name = headers.has('Authorization');
  delete headers[name];
  transaction.test.expected.headers = headers;
  
  done();
});
```

### Sanitation of URI Parameters

```js
var url = require('url');
var qs = require('querystring');

after('Resource > Update Resource', function(transaction, done) {
  var urlParts = url.parse(transaction.test.request.uri);
  var parameters = qs.parse(urlParts.query);
  delete parameters.token;
  urlParts.query = parameters;
  transaction.test.request.uri = url.format(urlParts);
  done();
});
```
