### ISSUE TITLE
Dredd sends empty PUT body when using MSON

### ISSUE THREAD

**Issue by thejuan** [apiaryio/dredd#627]
Using the following blueprint

``` apib
FORMAT: 1A
HOST: https://dummycopr.com

# Group Device

## Devices [/devices]

### Update Devices [PUT]

+ Request
    + Attributes (array)
        + id: `123` (required)
        + name: `Johnny` (optional)

+ Response 200
```

nothing is sent to the server

```
fail: body: Real and expected data does not match.
statusCode: Status code is not '200'

request: 
body: 

headers: 
    User-Agent: Dredd/1.6.1 (Linux 4.4.0-36-generic; x64)

method: PUT
uri: /devices
```

Am I doing something wrong?

**Comment by honzajavorek** [comment]
Hi @thejuan, sorry that it took me so long to reply. I didn't have time to reproduce the problem, but this is really strange. There might be glitches in what resulting JSON is generated and sent, but it should be definitely generated and sent towards the server.

How do you run dredd? If you use `dredd.yml`, could you paste the settings here? Thanks! And sorry again for the delay.

**Comment by thejuan** [comment]
I don't have a config file.
I do have hooks that setup an Auth header but no logic for just PUT
If the apib has body and json syntax it works, just not with MSON

Adam

**Comment by honzajavorek** [comment]
Okay, thanks. I'll get back here if I'm able to replicate this and find out what's the issue.

**Comment by honzajavorek** [comment]
@thejuan Just realised you could experience a problem described in https://github.com/apiaryio/dredd/issues/449. Could you please confirm this?

**Comment by thejuan** [comment]
Looks like it may be the same issue.

**Comment by honzajavorek** [comment]
@thejuan Thanks! The solution is to use [`fixed-type`](https://apiblueprint.org/documentation/mson/specification.html#353-type-attribute). I'll add it to the issue I linked as well. Thanks for drawing attention to this and for filing this issue! Please let me know whether `fixed-type` works for you.
