### ISSUE TITLE
Mocking HTTP Requests / Responses for external services

### ISSUE THREAD

**Issue by philsturgeon** [apiaryio/dredd#650]
I've come across an interesting use-case, which is stopping me allowing Dredd to run on two endpoints. 

These endpoints take input from the request, make a call to a third-party service (in this instance SalesForce) and then use content from the response as a portion of the response. 

In a unit testing world you'd stub the class that made the method call to SalesForce. In an integration testing world, you'd likely use something like [VCR](https://github.com/vcr/vcr) or [webmock](https://github.com/webmock/webmock) to short-circuit the request as its made by the HTTP request package (netHTTP, Faraday, curb, etc).

None of that will work here as dredd is running actual code, from node over HTTP to whatever (maybe Ruby) and hooks cannot help us directly either. Even trying to run one of those Ruby HTTP mocking tools in a Ruby hook, would still be no good as it's a different process to the actual Ruby code being called via HTTP.

One solution would be to spin up some sort of mock server in hooks, like running this https://github.com/unixcharles/mock_server which would be actually accessible via HTTP on a specific port, and the Ruby code would be looking for a host provided in an ENV variable. 

1. Ruby hook spins up mock server on `localhost:4567` before `Blah A > Get Stuff`
2. Dredd calls endpoint `GET /blah/stuff`
3. Ruby knows that mock server will be on `localhost:4567` from config, so hits `http://localhost:4567/api/salesforceshit` and gets the fake response its looking for
4. After `Blah A > Get Stuff` hook closes it down somehow

I thiiiiiink this will work, and am going to play with it soon. 

But, I'd be interested on what people think, about if this should be something dredd helps out with, and if so how could dredd make the process easier.

**Comment by hannesvdvreken** [comment]
I would use some kind of http client middleware that returns mock responses when under test. That way you don't even need the dredd hooks.

**Comment by fgblomqvist** [comment]
Is what @hannesvdvreken wrote still considered the best solution? Sounds a bit odd to me to mix production and test code just to have the requests be mocked automatically if running in a test environment. Although, I cannot think of a way that Dredd could make this easier since it is trying to be so separate from the code it is testing. Unless Dredd could provide a mock server that you can configure in a request easily (e.g. set endpoint and what it should return).

**Comment by artem-zakharchenko** [comment]
Unfortunately, Dredd doesn't have a strong answer on this. I would say mocking of such third-party communication currently lies on a developer. You can use any solution available to do that, not necessarily integrating such logic into a production server.

1. Record a third-party communications and use it as a snapshot during local testing. You may schedule a nightly job to pull the actual third-party responses and update the snapshots to verify you are not out of sync.
1. Alternatively, you can make third-party API endpoints parametric, using your local mock servers during the tests. So your server doesn't contain any test-specific logic, but uses environment-dependent endpoints.

Perhaps, in the future Dredd may evolve and support mocking as a first-class functionality. Until then I'd treat this as something outside of its jurisdiction.
