### ISSUE TITLE
Installation of protagonist finishes with errors, which confuses users

### ISSUE THREAD

**Issue by borekb** [apiaryio/dredd#659]
When installing Dredd 2.2.3 on Windows 10, I see these errors:

![image](https://cloud.githubusercontent.com/assets/101152/20079928/58d1d53a-a547-11e6-8293-1273a3dc2b54.png)

The installation still seems to work fine, interestingly (I am able to run `dredd` from the console). Also to note is that I tried on another Windows 10 PC and there, all was fine (no errors).

**Comment by honzajavorek** [comment]
Thanks! My first idea would be following: Dredd internally uses [Drafter](https://github.com/apiaryio/drafter) to parse API Blueprint. There are two versions of Drafter - one faster in C++11 and one slower (but more portable) in pure JavaScript. The [npm package for drafter](https://github.com/apiaryio/drafter-npm/) decides which one to use based on success of installation of the C++11 version. If it fails, it continues to use the JavaScript version.

Your installation seems to be the case. However, usually people do not have C++ compiler at all, so the failure doesn't look so severe. My hypothesis would be that you have some kind of C++ compiler present in the system, but it's not able to compile C+11, so the C++11 drafter installation fails with some unusual, terrible hairy errors. At the same time, the Dredd installation continues, finishes (I can't say, because the very bottom of the output isn't on your screenshot) and Dredd then runs correctly.

@w-vi What do you think?

--------------

_Mandatory disclaimer: Dredd isn't officially supported on Windows yet (it's planned!) and especially non-JS hooks probably won't work for you. However, there are people happily using Dredd on Windows._

**Comment by borekb** [comment]
For the record, on my laptop where it all works fine, I've got [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) installed.

**Comment by pksunkara** [comment]
@borekb Can you make sure you have C++ installed from the latest visual studio community edition and try again?

**Comment by borekb** [comment]
Should the C++ Build Tools linked above suffice? I'm hesitant to install the full Visual Studio (even the Express edition is large) on my PC.

**Comment by w-vi** [comment]
@borekb I think so.

**Comment by honzajavorek** [comment]
@borekb Just to reiterate, if the installation finishes correctly and Dredd works for you, you should not need to fix anything. The JS version of Drafter is fully equivalent to the C++11 version and the red output during installation is just result of finding out that Dredd isn't able to use the C++11 version and will use the JS one. If the whole Dredd installation finishes normally and Dredd works for you, you can ignore the error output for building the native module.

Of course, with correctly installed C++11 Drafter the parsing will be faster, but most of the time it's barely noticeable, in my humble experience.

**Comment by borekb** [comment]
@honzajavorek Thanks, I understand, just the user experience is not very good :) Perhaps the post-installation message could mention this, or the entire C++ compilation process could be wrapped in something like "try/catch" (if npm allows that, I don't know). Or the entire native package could be dropped if it's not significantly faster than JS :) (Hello, @klokane!)

**Comment by pksunkara** [comment]
> If the whole Dredd installation finishes normally and Dredd works for you, you can ignore the error output for building the native module.

I think the post-installation process should check for this and output a helpful message.

**Comment by honzajavorek** [comment]
@pksunkara you mean post-installation of Drafter or Dredd?

@borekb I agree, the message is scary at the first sight. Not good first
user experience, that's a good point.

**Comment by honzajavorek** [comment]
BTW I believe the performance boost is more significant larger your
blueprint is, I believe. But yes, this is not even properly documented yet.
It should be clear that the C++11 version is an optional dependency and
it's not the case at the moment.

**Comment by pksunkara** [comment]
Post installation of dredd.

**Comment by honzajavorek** [comment]
@pksunkara then Drafter NPM should expose an interface where I could programatically determine which version was actually installed (JS or C++11). I remember @kylef offered me such interface in the past (in the context of https://github.com/apiaryio/drafter-npm/issues/3), but I so far didn't feel I need it.

**Comment by honzajavorek** [comment]
If following is ran as a `postinstall` script, it prints to the terminal right after the protagonist installation fails:

```js
try {
  if (require.resolve('protagonist')) {
    process.exit(0);
  }
} catch (e) { }

process.stderr.write(`

MESSAGE BLAH BLAH

`);
```

It looks like this:

```
...
  File "/Users/honza/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/honza/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/honza/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/honza/.nvm/versions/node/v8.9.4/bin/node" "/Users/honza/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/honza/Projects/dredd/node_modules/protagonist
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> jsonpath@1.0.0 postinstall /Users/honza/Projects/dredd/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js


> dredd@0.0.0-semantically-released postinstall /Users/honza/Projects/kappa-workshop/node_modules/dredd
> node ./scripts/postinstall.js


MESSAGE BLAH BLAH


npm WARN rollback Rolling back nan@2.11.1 failed (this is probably harmless): /Users/honza/Projects/dredd/node_modules/nan is not a child of /Users/honza/Projects/kappa-workshop
npm WARN rollback Rolling back protagonist@1.6.8 failed (this is probably harmless): /Users/honza/Projects/dredd/node_modules/protagonist is not a child of /Users/honza/Projects/kappa-workshop
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 (../dredd/node_modules/protagonist):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: protagonist@1.6.8 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ dredd@0.0.0-semantically-released
added 247 packages and updated 1 package in 31.413s
```

That's nice, but I believe people will overlook it as it's not the last thing in the output. I don't know if assembling an advice about the failure makes sense in such case. I'd rather vote for https://github.com/apiaryio/drafter-npm/pull/16
