### ISSUE TITLE
Question: Response body testing

### ISSUE THREAD

**Issue by phenixiim** [apiaryio/dredd#661]
Hi all, 
I can't find it anywhere, so please tell me, Dredd is really testing only first level of response Body json? If I delete whatever from the second level, test are passing anyway.

Thanks a lot.

**Comment by w-vi** [comment]
@phenixiim Well not always, see the dredd documentation covering what is tested and when. http://dredd.readthedocs.io/en/latest/how-it-works/#automatic-expectations

**Comment by phenixiim** [comment]
Thanks a lot! Just a little question, is it possible to execute tests in exact order? I have a problem with authentication, which needs to be fired first and then the other tests (I have more apibs files) and sometimes the other apibs files are processed, so the tests fails. Thanks

**Comment by phenixiim** [comment]
Ok, I have discovered, that I can set up the exact docs in dredd.yml:
`blueprint: ["./apiary/auth_token.md","./apiary/inquiry.md"]`
But is thare a way to do it with
`blueprint: ./apiary/*.md`?

**Comment by phenixiim** [comment]
No, this is not working, please help, how could I set up the proper scripts run? Thanks

**Comment by honzajavorek** [comment]
@phenixiim The asterisk should work, but I believe there's a bug which causes it's not working at the moment: https://github.com/apiaryio/dredd/issues/504 However, I think using [`--path`](http://dredd.readthedocs.io/en/latest/usage-cli/#-path-p) you can overcome this limitation.

**Comment by honzajavorek** [comment]
@phenixiim Regarding authentication, please look at the [Isolation of HTTP Transactions](http://dredd.readthedocs.io/en/latest/how-to-guides/#isolation-of-http-transactions) and [Testing API Workflows](http://dredd.readthedocs.io/en/latest/how-to-guides/#testing-api-workflows) section in the documentation. They should give you pointers on how you can achieve what you need.

**Comment by phenixiim** [comment]
Thanks a lot, I have resolved it by writing standalone auth, maybe the code will be useful to somebody:
`
import json
import dredd_hooks as hooks
import requests

stash = {}
api_username = "XXX"
api_password = "XXX"
api_uri = "XXX"

@hooks.before_each
def add_token(transaction):
    if 'token' in stash:
        print('adding a token')
    else:
        stash['token'] = obtain_token()
    transaction['request']['headers']['Authorization'] = "Bearer " + stash['token']

def obtain_token():
    data = {
               "api_login_form": {
                   "username": api_username,
                   "password": api_password
               }
           }
    url = api_uri
    response = requests.post(url, json=data)
    parsed_body = json.loads(response.text)
    token = parsed_body["token"]
    return token

`
