### ISSUE TITLE
insert parametrs in dredd.yml 

### ISSUE THREAD

**Issue by RedDevilHat** [apiaryio/dredd#666]
Hello guys, how i can insert parametrs from other yml file fin dredd.yml?

**Comment by honzajavorek** [comment]
@RedDevilHat I'm afraid there's no way to do this. However, most of the settings can be overridden by a command line parameter: http://dredd.readthedocs.io/en/latest/usage-cli/

You can use `dredd.yml` for configuration which doesn't change and if there's something dynamically set according to what's in a different file, give it a sensible default in the `dredd.yml` file and then run Dredd with a command line option which overrides it. You could also easily script it - imagine a bash file like this:

```sh
value=$(' ... read the other yaml and extract the option value ... ')
dredd --option="$value"  # the rest of options is in ./dredd.yml
```

Would that work for you?

**Comment by honzajavorek** [comment]
@RedDevilHat Feel free to get back and re-open. Didn't hear from you, closing for now.
