### ISSUE TITLE
Validating inside arrays

### ISSUE THREAD

**Issue by Heanthor** [apiaryio/dredd#690]
I'm frustrated by dredd's inability to validate inside JSON arrays. My API response has the following layout:

```json
{
   "code": 200,
   "status": "success",
   "data": [
      {
         "id": "xxx",
         "type": "xxx",
         "title": "xxx"
      }]
   }
}
```

which dredd validates by checking if "code", "status", and "data" are present. I cannot find any way to make gavel validate the contents of the "data" array. Is the only option to write custom hooks and do the work myself?

**Comment by honzajavorek** [comment]
@Heanthor Unfortunately, yes, at the moment. This is a known issue:

- #177 (for cases when you provide JSON example in `+ Body` and let Gavel.js to generate the underlying JSON Schema for you)
- https://github.com/apiaryio/dredd/issues/449 (for cases when you use `+ Attributes` and let Drafter to generate the underlying JSON Schema for you)

As a workaround, you can:

- Either write hooks with custom assertions to ensure array items have the desired structure,
- or add a custom [`+ Schema` section](https://apiblueprint.org/documentation/specification.html#def-schema-section) with your own JSON Schema, which will override any generation and will result in validation according to your own rules.

**Comment by adityasaxena** [comment]
@honzajavorek It would help if you could provide an example of the test you mention. The documentation your link points to contains nothing useful I believe

**Comment by honzajavorek** [comment]
@adityasaxena You mean the `+ Schema` mention?

**Comment by honzajavorek** [comment]
@adityasaxena I've added an example to the specification: https://github.com/apiaryio/api-blueprint/pull/385
