### ISSUE TITLE
Can't Dredd skip hook process?

### ISSUE THREAD

**Issue by motoyasu-saburi** [apiaryio/dredd#693]
Can't skip hook process?

I testing specific only endpoint.
but all hook process is working.
I need hook of skipped endpoint not work.

Input command.  
__command__  
```
$ dredd --only 'UserController > user > add user'"
or
$ dredd --method 'GET'
```

__dredd ver__
```
4.0.5
```

__hook.js__
```
var otherAssertModule = ("assertModule");

hooks.before('SkipController > this is > skipped endpoint', function(transaction) {
  // I expected "true", but actual value is "false"
  console.log( transaction.skip );
});

hooks.after('SkipController > this is > skipped endpoint', function(transaction) {
  // "body" property is not exist if skipped this endpoint.
  var response = JSON.parse(transaction.real.body);
  // this assert process not skipped and assert fail.
 otherAssertModule.assert(response.users.name, "John")

  // actual value is "true". Expected!
  console.log( transaction.skip );
});
```

Can I skip hook process?

**Comment by honzajavorek** [comment]
Hi, I think this is the same problem as described in https://github.com/apiaryio/dredd/issues/536. It's definitely an issue and I'm afraid there's currently no workaround available. The logic responsible for skipping needs to be reworked in order to fix this.
