### ISSUE TITLE
Swagger variable parameter does not work with Dredd

### ISSUE THREAD

**Issue by belrion** [apiaryio/dredd#694]
#### Describe your problem
Parameter on Swagger using as variable cannot be processed by Dredd.

If I don't specify the default: value key word, dredd complains:
error: Compilation error in file 'swagger.yml': Required URI parameter 'id' has no example or default value. (job > /driveprocessing/v1/jobs/{id} > GET)

If I specify the default: value key word, dredd complains and skips the test:
warn: Compilation warning in file 'swagger.yml': Required URI parameter 'id' has a default value.
Default value for a required parameter doesn't make sense from API description perspective. Use example value instead. (job >/driveprocessing/v1/jobs/{id} > GET)
info: Beginning Dredd testing...
info: job > /driveprocessing/v1/jobs/{id} > GET > 200
skip: GET /driveprocessing/v1/jobs/1ba10167-4560-4973-bd92-db9a747571f5
skip: GET /driveprocessing/v1/jobs/1ba10167-4560-4973-bd92-db9a747571f5
complete: 0 passing, 0 failing, 0 errors, 2 skipped, 2 total
complete: Tests took 15ms

#### What command line options do you use?

```
$ dredd swagger.yml http://<my-end-point.com --names
```

#### What is in your `dredd.yml`?
```yaml
I don't use dredd.yml yet
```

#### What's your `dredd --version` output?

```
dredd v2.2.5 (Windows_NT 6.1.7601; x64)
```

#### Can you send us failing test in a Pull Request?
yes.

Here is the snippet of the swagger.yml file
```
paths:
  /jobs/{id}:
    get:
      tags:
      - job
      description: Job id from a previously submitted DA job can be used to find its status
      parameters:
        - name: id
          description: job id
          type: string
          in: path
          required: true
          default: 1ba10167-4560-4973-bd92-db9a747571f5
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              jobId: 
                type: string
              tasks:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                    taskType:
                      type: string
                    taskStatus:
                      type: string
```

**Comment by belrion** [comment]
find an example to use transaction.fullPath.replace() to substitute the correct value in the hooks.js.

You have to define the enum: "xx" in the swagger.yml file as part of the parameters: to replace 'xx' with the value you wanted.

**Comment by honzajavorek** [comment]
I can see `--names` in the command you were using. Wasn't it a similar problem as in https://github.com/apiaryio/dredd/issues/697? According to the output, it seems like exactly the same issue.

I just want to point out it's not entirely your fault not to notice it - at the moment it's very easy to get confused by the current output of the option - see https://github.com/apiaryio/dredd/issues/564.
