### ISSUE TITLE
Skipping test case in swagger.yml

### ISSUE THREAD

**Issue by belrion** [apiaryio/dredd#697]
#### Describe your problem
I am running a simple GET operation for the API in the form of swagger.yml file. Dredd parsed it but then skipped running the test. The test has only one response '200'.

This is on Linux with Ubuntu 14.02

#### What command line options do you use?

```
$ dredd swagger.yml http://<end-point>.com --names
```

#### What is in your `dredd.yml`?

```yaml
Not using dredd.yml
```

#### What's your `dredd --version` output?

```
dredd v2.2.5 (Linux 3.13.0-32-generic; x64)
```

#### Does `dredd --level=debug` uncover something?
After evaluating the transaction, it is skipping the test.

debug: Emitting to reporters: test start
info: job > /driveprocessing/v1/jobs/8057e436-5d64-4cbe-ada5-8a84c24cb609 > GET > 200
debug: Running hooks...
debug: Evaluating results of transaction execution #1: job > /driveprocessing/v1/jobs/8057e436-5d64-4cbe-ada5-8a84c24cb609 > GET > 200
debug: Emitting to reporters: test skip
skip: GET /driveprocessing/v1/jobs/8057e436-5d64-4cbe-ada5-8a84c24cb609

#### Can you send us failing test in a Pull Request?
```
---
swagger: '2.0'
info:
  description: This is a sample test for Job Services API
  version: 1.0.0
  title: Pose Services
  contact:
    email: chi.dang@here.com
host: <end-point>.com
basePath: /driveprocessing/v1
schemes:
- http
paths:
  /jobs/8057e436-5d64-4cbe-ada5-8a84c24cb609:
    get:
      tags:
      - job
      description: Job id from a previously submitted DA job can be used to find its status
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              jobId:
                type: string
              tasks:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                    taskType:
                      type: string
                    taskStatus:
                      type: string
                    createdTime:
                      type: string
                    drives:
                      type: array
                      items:
                        properties:
                          driveSessionId:
                            type: string
                          storageKey:
                            type: string
                          sourceVersion:
                            type: integer
                          version:
                            type: integer
                          nominalVersion:
                            type: integer

```

**Comment by belrion** [comment]
if you run with --names, it will skip the test. After removing the --names option, the test runs fine on Windows.

**Comment by honzajavorek** [comment]
Yes, the [`--names`](http://dredd.readthedocs.io/en/latest/usage-cli/#-names-n) option is [just to get the transaction names](http://dredd.readthedocs.io/en/latest/hooks/#getting-transaction-names). It just lists the names and stops Dredd.
