### ISSUE TITLE
Cache parse/compile result

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#700]
Parsing and compiling of transactions ([dredd-transactions](https://github.com/apiaryio/dredd-transactions)) can be rather slow (discovered in https://github.com/apiaryio/dredd/issues/633). We could add cache to Dredd, which would keep transactions compiled from known API descriptions serialized in a file between Dredd runs.

It's not an ideal solution to https://github.com/apiaryio/dredd/issues/633 (it would be better to make dredd-transactions fast again) but it could make Dredd testing very convenient and fast for everyday use regardless any underlying performance issues.

The cache could live somewhere in user data (i.e. `~` on UNIX-like systems, in correspondent standard location on Windows) and the cache key would be "Dredd version + input API description document hash". Contents of the cache file would be JSON with compiled transactions (i.e. output of the dredd-transactions).

You could turn on or off caching by `--cache/--no-cache` options. One of them would be on by default. This kind of naming also allows us to change which one is on by default in the future.

Too old cache files (month old, determined on file system level by last changed date of the file) would be automatically deleted in the beginning of each Dredd start (this would be ideally faster than parsing and compilation - and we want to super-optimize in the future, unlike parsing and compilation it could be delegated to a separate thread/process responsible just for deleting, while Dredd does it's regular job).

**Note:** It probably wouldn't be wise to delete cache files for older Dredd versions, because user can have multiple Dredd versions installed.

Cache could also help in CI installments, where most CIs allow user to specify cached directories. Users could add Dredd's cache directory to those which will be carried between builds and that would speedup build runtime.

The usefulness of such cache is dependent on correctness the assumption that most users run Dredd repeatedly on top of the same API description document, especially when developing the API implementation or in CI.

**Comment by Pablodotnet** [comment]
+1

**Comment by honzajavorek** [comment]
The #633 was resolved by different optimizations and currently I don't feel caching is something Dredd needs at the moment.
