### ISSUE TITLE
How to control order of tests

### ISSUE THREAD

**Issue by kxmatejka** [apiaryio/dredd#717]
Hello, I cannot figure out, how to control order of tests. I usually have case like this:

```
# Group Customers

## Customers [/customers]

### Create Customer [POST]

+ Request (application/json)

        {
            ...
        }

+ Response 201 (application/json)

        {
            ...
        }


### Delete Customer [DELETE /customer/{id}]

+ Parameters
    + id: 1 (number, required)

+ Response 204


# Group Address

## Address [/address]

### Create Address [POST]

+ Request (application/json)

        {
            ...
        }

+ Response 201 (application/json)

        {
            ...
        }

```

```
hooks.after('Customer > Customer > Create Customer', function (transaction) {
	stash['user_id'] = JSON.parse(transaction.real.body)['id'];
});

hooks.before('Customer > Customer > Delete Customer', function (transaction) {
	transaction.fullPath = transaction.fullPath.replace('/1', '/' + stash['user_id']);
});

hooks.before('Address > Address > Create Address', function (transaction) {
	// transaction.request.body modification
});
```

User was created and after deleted, but I need use his ID for group address. How to change order? Globally would suffice me if, all DELETE methods will be executed as a last.

**Comment by kxmatejka** [comment]
I tried do this through async call, but test runs without modification with parameter /customer/1. And after all I see in terminal:

```
complete: See results in Apiary at: https://app.apiary.io/oscustomers/tests/run/698891d...
hook: Deleting user id: 22833490
```

hooks.js:
```
var delete_allowed = false;

hooks.after('Address > Address > Edit customer detail', function (transaction) {
	delete_allowed = true;
});

hooks.before('Customer > Customer > Delete customer', function (transaction, done) {
	var timer;

	timer = setInterval(function () {
		transaction.skip = false;
		if (delete_allowed) {
			transaction.fullPath = transaction.fullPath.replace('/1', '/' + stash['user_id']);
			hooks.log(transaction.fullPath);
			hooks.log('Deleting user id: ' + stash['user_id']);
			clearInterval(timer);
		} else {
			hooks.log('Waiting for some test');
		}
	}, 1000);

	done();
});
```

**Comment by honzajavorek** [comment]
@kxmatejka You can influence the order of transactions by the [`--sorted`](http://dredd.readthedocs.io/en/latest/usage-cli/#-sorted-s) CLI option. Also please see [Isolation of HTTP Transactions](http://dredd.readthedocs.io/en/latest/how-to-guides/#isolation-of-http-transactions) and [Testing API Workflows](http://dredd.readthedocs.io/en/latest/how-to-guides/#testing-api-workflows) in the documentation. You may want to isolate your tests and have some setup/teardown in your hooks.

**Comment by honzajavorek** [comment]
@kxmatejka Actually, I forgot about one more option! It's workaround mentioned here: https://github.com/apiaryio/dredd/issues/456#issuecomment-247545197 Would that work for you?

**Comment by kxmatejka** [comment]
Thanks, that's exactly what I need!

**Comment by honzajavorek** [comment]
Good! 👍
