### ISSUE TITLE
Example parameter value with a closing parenthesis fails

### ISSUE THREAD

**Issue by JaredReisinger** [apiaryio/dredd#73]
Having the following in a Parameters section:

```md
+ Parameters

    + filter (required, string, `id~(valueOne|valueTwo)`) ... Includes all items which match the filter.
```

 causes dredd to report "Ambigous URI template: _theUrl_{?filter}.  Parameter not defined:'filter' on _theTestName_.

Removing the closing parenthesis from within the example value makes it work, but of course that doesn't make the underlying service happy.  I'm documenting an already-existing API, so I can't change the format of the parameter.  I suspect that the parameter parsing is looking for the first `)` without noticing that it's within the example value (back-ticks).

**Comment by netmilk** [comment]
Fixed in the blueprint parser: https://github.com/apiaryio/snowcrash/issues/109#issuecomment-49035122
