### ISSUE TITLE
Dredd should pass hook files as absolute paths to a hook handler

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#742]
Currently, it seems Dredd just passes the hookfile file names to the hook handler process. However, on Windows this does not seem to work well for relative paths. Dredd should evaluate everything, sort the files alphabetically, and pass a list of absolute paths to the hook handler. That would also solve also https://github.com/apiaryio/dredd/issues/680.

**Comment by TotempaaltJ** [comment]
This makes a lot more sense, especially as Dredd's the one mentioning the hook files it found.

**Comment by honzajavorek** [comment]
This has been implemented and released as v4.1.0. @w-vi @gonzalo-bulnes @snikch @ungrim97 @ddelnano I hope this did not break anything (it shouldn't!) Related to https://github.com/apiaryio/dredd-hooks-template/issues/22 as well.
