### ISSUE TITLE
Test is repeating unnecessarily

### ISSUE THREAD

**Issue by C-D-Lewis** [apiaryio/dredd#758]
#### Describe your problem

After describing an operation (shown below), when run dredd appears to perform the test four times instead of the expected once. This does not happen for any of the other defined operations.

```
"/actions": {
  "post": {
    "description": "Create a new action type.",
    "parameters": [
      {
        "name": "ActionTypeDocument",
        "in": "body",
        "description": "The action type to create.",
        "required": true,
        "schema": {
          "$ref": "#/definitions/ActionTypeDocument",
          "example": {
            "name": "_custom"
          }
        }
      }
    ],
    "responses": {
      "201": {
        "description": "The newly created action type",
        "schema": {
          "$ref": "#/definitions/ActionTypeDocument"
        },
        "examples": {
          "id": "Uk7WdgFAMQtehsRawgdwEkCn",
          "createdAt": 1490368131932,
          "updatedAt": 1490368131932,
          "name": "_custom"
        }
      }
    }
  }
}
```

Command output (without failed test detail)

```
warn: Parser warning in file '../swagger.json': (warning code 3) External documentation is not yet supported on line 648
info: Beginning Dredd testing...
info: Found Hookfiles: 0=./hooks.js
pass: GET /accounts duration: 404ms
pass: GET /accounts/UFNCRXfCVM87QNawaE8rrKqc duration: 268ms
pass: PUT /accounts/UFNCRXfCVM87QNawaE8rrKqc duration: 265ms
pass: POST /actions/scans duration: 280ms
pass: GET /actions/scans duration: 291ms
pass: GET /actions/scans/UFrfWVAFM9QBhsRawEKNYbXc?context=true duration: 264ms
fail: POST /actions duration: 267ms
fail: POST /actions duration: 263ms
fail: POST /actions duration: 260ms
fail: POST /actions duration: 260ms
pass: GET /actions/scans/UFrfWVAFM9QBhsRawEKNYbXc duration: 255ms
pass: DELETE /actions/scans/UFrfWVAFM9QBhsRawEKNYbXc duration: 256ms
pass: GET /time duration: 254ms
info: Displaying failed tests...
```

#### What command line options do you use?

```
dredd ../swagger.json https://api.evrythng.com \
  --hookfiles ./hooks.js \
  --header "Authorization: $DREDD_OPERATOR_API_KEY"
```

#### What is in your `dredd.yml`?

N/A

#### What's your `dredd --version` output?

```
laptop:tests chrislewis$ dredd --version
dredd v3.2.2 (Darwin 15.6.0; x64)
```

#### Does `dredd --level=debug` uncover something?

No

#### Can you send us failing test in a Pull Request?

Not sure what this means.

**Comment by C-D-Lewis** [comment]
This appears to be caused by missing the `examples` type. See difference:
```
"examples": {
  "id": "Uk7WdgFAMQtehsRawgdwEkCn",
  "createdAt": 1490368131932,
  "updatedAt": 1490368131932,
  "name": "_custom"
}
```

```
"examples": {
  "application/json": {
    "id": "Uk7WdgFAMQtehsRawgdwEkCn",
    "createdAt": 1490368131932,
    "updatedAt": 1490368131932,
    "name": "_custom"
  }
}
```

Any insight into the actual cause (or if this is undefined behavior) would be appreciated.

**Comment by honzajavorek** [comment]
@C-D-Lewis Thanks for reporting this!

I think the Swagger adapter treats each of the keys of your example object as a separate media type. It looks like the adapter isn't able to consume `example` in form of a single free-form object. I'm not sure what you do is according to [Swagger specification](http://swagger.io/specification/#exampleObject):

> The name of the property MUST be one of the Operation produces values (either implicit or inherited). The value SHOULD be an example of what such a response would look like.

It looks like we could at least fix the adapter to fail with error whenever the `examples` key doesn't match any of the produced media types. What do you think, @pksunkara?

**Comment by pksunkara** [comment]
They can be custom media types, so I don't think we should be changing the swagger parser at all. Because this is still a valid document.

**Comment by C-D-Lewis** [comment]
Thanks for looking at this! I understand what's happening now and I can see it in retrospect.

**Comment by honzajavorek** [comment]
@C-D-Lewis I'm glad we could help! So do you think this is all sorted and we can close the issue? Or do you think something should get changed to improve the experience?

**Comment by C-D-Lewis** [comment]
The explanation around custom media types is reason enough not to change it I think. Perhaps a note somewhere in the docs explaining that forgetting _any_ media types in examples will produce strange behavior.

Feel free to close!

**Comment by honzajavorek** [comment]
Thanks!
