### ISSUE TITLE
Run test coverage on AppVeyor as well

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#763]
Currently, the test coverage is being collected only on Travis CI. However, some parts of Dredd code are platform-specific, so there are gaps in the coverage when particular code takes care of Windows.

<img width="905" alt="image" src="https://cloud.githubusercontent.com/assets/283441/24666074/946669f8-195f-11e7-96cc-1437074916de.png">

Adding Coveralls to `appveyor.yml` is simple:

```yml
on_success:
  - "npm run coveralls && exit 0"
```

Rewriting `scripts/coverage.sh` and `scripts/coveralls.sh` to something platform-independent (CoffeeScript / JS) is a different story 😬 

### Related

- https://github.com/apiaryio/dredd/issues/55
- https://github.com/nickmerwin/node-coveralls/pull/164
- https://github.com/nickmerwin/node-coveralls/pull/124
- https://github.com/nickmerwin/node-coveralls/issues/114#issuecomment-236953331

**Comment by netmilk** [comment]
Is this really needed? Do we have any means how to monitor coverage in multiple environments?

**Comment by honzajavorek** [comment]
@netmilk I'd say Coveralls should display a sum of coverage sent for a particular PR, from all CIs. But I did not verify that. If that's not the case, then of course this would be useless.

**Comment by honzajavorek** [comment]
This should have been closed when closing https://github.com/apiaryio/dredd/issues/1244
