### ISSUE TITLE
Hook HTTP request sending

### ISSUE THREAD

**Issue by shadowhand** [apiaryio/dredd#770]
In my application, it is possibly to inject a HTTP request as a fully constructed object without having to make an actual HTTP request. (This is possible in PHP because of [PSR-7 HTTP Messages](http://www.php-fig.org/psr/psr-7/). Other languages certainly have similar complete-http-as-code functionality.) Our primary testing environment thus avoids the need to have a HTTP server running, and all tests are run via this injection.

I have read the hooks documentation extensively and I see no way to achieve this with dredd. Based on what I see in the [lifecycle docs](https://dredd.readthedocs.io/en/latest/how-it-works/#execution-life-cycle) there is no way to take control of request sending to avoid a complete HTTP round trip. Having this functionality would be extremely beneficial to us, as we could continue to avoid having an HTTP server running in our test boxes.

Refs #650

**Comment by honzajavorek** [comment]
I understand your point, but Dredd is meant to check end-to-end compliance of your server.

While different languages can have a similar complete-http-as-code functionality, it would be very difficult to make this work and maintain such feature cross-language. On the other hand, all languages talk HTTP. For Dredd, HTTP is the integration layer and the thing to test.

You are correct in that even if you filed this issue specifically for the [dredd-hooks-php](https://github.com/ddelnano/dredd-hooks-php) project, for the PHP hook handler it's not possible to intercept the actual HTTP request from hooks as the hooks handler is not the one performing it. Performing the HTTP request is an essential part of the actual testing and Dredd needs to have that part fully under its control to ensure correct and uniform behavior (in other words, you can make the request in various ways with various parameters and if Dredd wasn't the single entity responsible for making the request, you couldn't rely on how the request is made - e.g. whether HTTP proxy support is present or not, etc.).

I don't think this is a direction we would like to pursue. I'd rather focus on making the HTTP roundtrips and overall Dredd performance faster, but I'd keep the HTTP as an essential, core, and the only integration layer with the server under test.

Mentioning @netmilk to put his thoughts here as well, but closing for now. If there's more people gathering around this idea or proposals on how to implement it, I'm happy to re-open.

**Comment by shadowhand** [comment]
@honzajavorek thanks for your feedback, we'll take it into consideration.
