### ISSUE TITLE
Swagger with Spring 4.6 (rest api )- Is there a way I can add my auth token to all request headers?

### ISSUE THREAD

**Issue by robinsonrengaraj** [apiaryio/dredd#778]
#### Describe your problem
I want to add authorization token to all request headers.
Eg: header("Authorization","xxxxxxxxx")

**Comment by honzajavorek** [comment]
Hi @robinsonrengaraj, what exactly is "Sprint rest"? This is something you'd normally do by [Dredd hooks](https://dredd.readthedocs.io/en/latest/hooks/).

**Comment by robinsonrengaraj** [comment]
Hey
Its Spring mvc ( rest api).

**Comment by honzajavorek** [comment]
Spring is a framework in Java.

There are no Java [hooks](https://dredd.readthedocs.io/en/latest/hooks-new-language/) yet. You would either use a different language particularly for the hooks (Go, JS, Perl, PHP, Python, Ruby), but then you might be limited in what's possible to do with your application in the hooks. E.g. to setup some fixtures in the database, you'd need to create an ad-hoc connection just for the hooks, not being able to leverage any of the goodies the Spring framework offers you. For instance, see the [JS example](https://dredd.readthedocs.io/en/latest/hooks-nodejs/#handling-sessions) of modifying the transaction and adding a header.

The other option would be to [contribute Java hooks](https://dredd.readthedocs.io/en/latest/hooks-new-language/).

**Comment by robinsonrengaraj** [comment]
Thank you for the detail response.
