### ISSUE TITLE
Processing blueprint files from a glob expression

### ISSUE THREAD

**Issue by yakovkhalinsky** [apiaryio/dredd#79]
Curious whether you guys have this in your roadmap as a future improvement.

For example:
`dredd path/to/blueprint/files/**/*.md http://localhost:8080/api`

**Comment by netmilk** [comment]
Hi, just a note that this was implemented some time agou. You can now use glob expression or url as a blueprint path and you can specify asditional paths with use of `-p` or `--path` parameter.
