### ISSUE TITLE
ability to prepare transaction.real.body before validation

### ISSUE THREAD

**Issue by balupton** [apiaryio/dredd#792]
We have a situation where our API specification provides HTML responses that we would like properly and manually indented for readability. However the API server actually returns a mostly minified responses. It would be great if we were able to compare the prettified/beautified versions of both the expected data, and the actual/real data.

Right now, it seems the only option is to have the exact partially minified (and unreadable) response inside our API specification file. As parsing only the transaction.expected.body through a beautifier is not enough, the transaction.real.body must be as well.

I've looked at the docs, but it seems transaction.real is not provided to the beforeValidation hook, which is where this needs to occur. It is only passed to the after hooks according to the docs.

**Comment by balupton** [comment]
turns out the docs are wrong, and `beforeValidation` does include `transaction.real.body`, woot woot

**Comment by honzajavorek** [comment]
Thanks for filing this! `beforeValidation` should have `transaction.real.body` set. Could you please point me to a place where this is incorrectly mentioned in the docs? Or would you send a PR with a fix? 😉

**Comment by honzajavorek** [comment]
I checked the docs and can't find where it would be wrong. Without further information we're unable to fix this.
