### ISSUE TITLE
Custom template to add annotation for spring data 

### ISSUE THREAD

**Issue by ayushoo7** [apiaryio/dredd#794]
If you want to share an idea :bulb:, feel free to delete all this and just write what you want. If you are reporting a bug :bug:, remove this paragraph and fill following:

In model class generated I want some annotation to be generated for it to persist in db using spring data. Used template but I can only put static code if want to introduce some dynamic param like {{#myanotation}} then can specify from properties or .yml file it would be great 

java -jar swagger-codegen-cli-2.2.1.jar generate -i api.yml -c conf.json -l spring -o %TMP_SRC_DIR%  -t C:\Users\template

api.yml --> yaml for apis as we as models
%TMP_SRC_DIR% --> output directory any 
template folder had  model.mustache and api.mustache which I want to modify

Scenario want to generate required set of files as dont want to change model classes manually

**Comment by ayushoo7** [comment]
Please can some one help me for this

**Comment by honzajavorek** [comment]
Hi @ayushoo7, this is an issue tracker of Dredd testing tool. Dredd tests API implementation against the Swagger API description documents, which is useful with the design-first approach when creating HTTP APIs.

Unfortunately I do not understand what is your problem and to me, it seems to be unrelated to Dredd. It looks like you have some problems with the `swagger-codegen-cli` tool. In that case, you should probably file an issue [here](https://github.com/swagger-api/swagger-codegen/issues).

If I'm wrong and you manage to explain the issue in other words, I'd be happy to re-open this.

**Comment by ayushoo7** [comment]
Thanks honzajavorek yes its related to swagger-codegen-cli tool. Sorry for opening at wrong place.
Thanks

**Comment by honzajavorek** [comment]
@ayushoo7 No problem, that happens 🙂
