### ISSUE TITLE
Question: --path example

### ISSUE THREAD

**Issue by sisillV** [apiaryio/dredd#796]
Hi Dredd Team,
I install dredd 2 days ago and I need help from you about this:

"To test various scenarios, you will want to write each of them into a separate API description document. To load them during a single test run, use the --path option."

Please give me example I could't make it run. For example with 3.json files.

Thank you!
BR,
Stanislava

**Comment by sisillV** [comment]
I found this:
'dredd --path ./testAPIEx.json ./testAPIEx2.json http://test.com:11111 --reporter=html --output='
still can not run from dredd config file

**Comment by honzajavorek** [comment]
Hi Stanislava! You should be able to run Dredd with multiple API descriptions like this:

```
dredd something1.json http://example.com --path=something2.json --path=something3.json
```

This should load all three descriptions. You should be able to specify this also in the `dredd.yml` configuration file. Make sure you have the `path` and `blueprint` entries like this:

```yaml
blueprint: something1.json
path: ['something2.json', 'something3.json']
```

Would that work for you?

**Comment by honzajavorek** [comment]
@sisillV I hope your question is answered. If you have anything more to this, feel free to comment or file a new issue.
