### ISSUE TITLE
x-example not working for array types

### ISSUE THREAD

**Issue by Pscheidl** [apiaryio/dredd#798]
#### Describe your problem

Example attribute "x-example":"someExample" is not picked up for parameter "type": "array". Instead a value of "%5Bobject%20Object%5D" is inserted.

JSON snippet:

```json
"parameters": [
          {
            "in": "query",
            "name": "transactionId",
            "type": "array",
            "description": "Transaction identifier",
            "required": true,
            "x-example": "1,2",
            "items": {
              "type": "integer",
              "format": "int64",
            }
          }
        ]
```

Actual request by Dredd:

```text
method: GET
uri: /transactions?transactionId=%5Bobject%20Object%5D
headers:
    Accept: application/json;charset=UTF-8
    User-Agent: Dredd/3.5.0 (Windows_NT 6.1.7601; x64)
    Content-Length: 0

body:
```

#### What command line options do you use?
```
$ dredd ./swagger.json http://localhost:8080
```

#### What is in your `dredd.yml`?
Nothing. Not used.

#### What's your `dredd --version` output?

```
dredd v3.5.0 (Windows_NT 6.1.7601; x64)
```

#### Does `dredd --level=debug` uncover something?

No.

**Comment by honzajavorek** [comment]
Thanks for the report! `array` request parameters are not supported yet. The support needs to be added to the Fury Swagger Adapter. cc @pksunkara

**Comment by honzajavorek** [comment]
I'd actually merge this with https://github.com/apiaryio/dredd/issues/791.
