### ISSUE TITLE
No support for brackets in query param names (like status[])

### ISSUE THREAD

**Issue by bsacharski** [apiaryio/dredd#799]
#### Describe your problem
It would seem that Dredd has a problem with query params that have brackets in their name (like `status[]`). This seem to be properly supported by a Swagger though, so one would assume that Dredd should also support that

#### What command line options do you use?

```
$ dredd swagger.json http://server_address
```

#### What is in your `swagger.json`?
```
...
"parameters": [
{
    "name": "status[]",
    "in": "query",...
}
...
]
```

#### What's your `dredd --version` output?
```
dredd v3.5.0 (Linux 3.16.0-4-amd64; x64)
```

#### Does `dredd --level=debug` uncover something?
```
error: Compilation error in file 'out/hapi.swagger.json': Failed to parse URI template: /partner{?status[],limit,offset}
Error: SyntaxError: Expected "(", "*", ",", ":", "}" or [a-zA-Z0-9_.%] but "[" found. (partner > /partner > Get a list of all partner objects
```

**Comment by honzajavorek** [comment]
Thanks for the report! Looks like this is something which needs to be fixed in the [Fury Swagger Adapter](https://github.com/apiaryio/fury-adapter-swagger/), cc @pksunkara @kylef

**Comment by pksunkara** [comment]
@honzajavorek How so? Adapter doesn't do anything regarding it. It just forwards it to dredd.

**Comment by honzajavorek** [comment]
@pksunkara It's compilation / syntax error, and those are from Fury. Dredd doesn't add any custom syntax errors AFAIK.

**Comment by kylef** [comment]
@pksunkara the adapter is generating a URI Template (`/partner{?status[],limit,offset}`) which is not valid. The `[` and `]` character should be escaped within the template I believe.

**Comment by kylef** [comment]
A fix for this problem should be contained within https://github.com/apiaryio/fury-adapter-swagger/pull/109.

**Comment by honzajavorek** [comment]
This gets fixed and released with https://github.com/apiaryio/dredd-transactions/pull/80 in several minutes.
