### ISSUE TITLE
Check for links to closed issues in docs

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#812]
Often issues get linked from docs as part of a note why something isn't implemented or supported yet. When this changes, the docs don't get updated. The build process for docs could check for links to issues / pull requests and break the build if they're closed, because in that case it means the docs need to be updated.

### Example

<img width="744" alt="image" src="https://user-images.githubusercontent.com/283441/27705102-22f6a67e-5d0d-11e7-99aa-99cac60d6933.png">

...while both https://github.com/apiaryio/fury-adapter-swagger/issues/68 and https://github.com/apiaryio/fury-adapter-swagger/issues/67 are already closed.

**Comment by hobofan** [comment]
Could probably be done with [remark](https://github.com/wooorm/remark-lint) + a new rule. https://github.com/davidtheclark/remark-lint-no-dead-urls looks like a good starting point.

**Comment by honzajavorek** [comment]
Poor man's implementation in Sphinx extension could be:

```python
from sphinx.util import logging

logger = logging.getLogger(__name__)

...

res = requests.get(refuri)
if 'class="State State--green"' not in res.text:
    logger.info("GitHub Issue linked, but not open: {}".format(refuri))
```

**Comment by honzajavorek** [comment]
I don't think this is a real issue we should be solving. From time to time, we should check if docs contain relevant information, including the prose, and this should be a part of that.
