### ISSUE TITLE
How to run single api in whole apiary file with dredd

### ISSUE THREAD

**Issue by miendt** [apiaryio/dredd#830]
For example, apiary file: 
## Signup [/signup/]
In apiary file, I have 2 api as above, so how to run each `## Signin [/signin/]` api?
Could you please give me some suggestion,
Thanks  !

**Comment by honzajavorek** [comment]
Hi @miendt, sorry for such late response. One [API Blueprint](https://apiblueprint.org/) file typically describes one API. The `/signin/` and `/signup/` are usually called _endpoints_ or _resources_. If you use Dredd with an API Blueprint file containing two endpoints, Dredd should automatically test each of them.

I recommend you to go through the [Quickstart](https://dredd.readthedocs.io/en/latest/quickstart.html), step-by-step. Also, [dredd-example](https://github.com/apiaryio/dredd-example) contains full working example of Dredd and a simple API.

Does that answer your question?

**Comment by miendt** [comment]
@honzajavorek  Thank you for your support,
Also, I found solution for run single api such as:
+ Step 1: get names as `dredd --names`
==> After get names, for ex: `Signin > Sign In`
+ Step 2: Run apib use `--only="Name'sAPIEndpoint"`
==> For ex: Run `dredd --only="Signin > Sign In"`

**Comment by honzajavorek** [comment]
@miendt Good! Still, this would be rather called _running a single endpoint_, but I'm glad you found what you needed 🙂
