### ISSUE TITLE
Make GOPATH environment variable optional (now mandatory)

### ISSUE THREAD

**Issue by vladosaurus** [apiaryio/dredd#832]
From Go 1.8 onward it is optional to specify the GOPATH environment variable:
https://golang.org/cmd/go/

as seen here:
https://github.com/apiaryio/dredd/blob/master/src/hooks-worker-client.coffee#L131

**Comment by honzajavorek** [comment]
@ddelnano @snikch What do you think about this?

**Comment by ddelnano** [comment]
@honzajavorek the default should be `$HOME/go` if it is not set.  So we just need to provide that as a default.  I can try and submit a patch for that sometime this week.

**Comment by snikch** [comment]
Makes sense to me 👌

**Comment by honzajavorek** [comment]
This is being addressed by @vladosaurus' own PR: https://github.com/apiaryio/dredd/pull/835 👍

**Comment by honzajavorek** [comment]
I believe this has been already tackled by https://github.com/apiaryio/dredd/pull/928.
