### ISSUE TITLE
Add support for RAML 1.0 specification

### ISSUE THREAD

**Issue by galkin** [apiaryio/dredd#837]
Could Dredd support [raml](https://raml.org) specification?
There is nice [node.js parser](https://npmjs.com/raml-1-parser) for the 1.0 RAML

**Comment by honzajavorek** [comment]
It could! Basically, adding support for a new API description format goes like this...

Dredd consumes [API Elements](https://api-elements.readthedocs.io/en/latest/). It uses [Fury.js](https://github.com/apiaryio/fury.js) to turn any API description format (currently API Blueprint and Swagger 2.0) into API Elements.

To produce API Elements for various formats, Fury.js uses [adapters](https://github.com/search?q=topic%3Afury+org%3Aapiaryio&type=Repositories). So the first and the most important step to add support for RAML to Dredd would be to create an adapter for Fury, similar to [the one for Swagger](https://github.com/apiaryio/fury-adapter-swagger). The Fury.js maintainers (@apiaryio/adt) would definitely give a hand and advice to anyone who starts with this.

-------

**Note:** A scheme of Dredd's parsing stack is in https://github.com/apiaryio/dredd/issues/820, I'd be happy to re-draw it and add it to docs if there's someone who actually needs it.

**Comment by sichvoge** [comment]
Having support for RAML 1.0 in Dredd would be seriously cool. Guess the difficulty might be to write a parser for a RAML document into API Elements.

**Comment by ChrisDillinger** [comment]
uh for giggles, what would be some prerequisite knowledge needed to help out here?

**Comment by honzajavorek** [comment]
@ChrisDillinger I'd say you need a knowledge of RAML, [API Elements](https://api-elements.readthedocs.io/en/latest/), and JavaScript.

**Comment by honzajavorek** [comment]
Does [this announcement](https://blogs.mulesoft.com/dev/api-dev/open-api-raml-better-together/) change something? Does it still make sense to support RAML in Dredd?

**Comment by galkin** [comment]
Close as outdated
