### ISSUE TITLE
Set request body using `x-examples` or similar (or: expose more vendor properties in transactions?)

### ISSUE THREAD

**Issue by erinaceous** [apiaryio/dredd#876]
I've used [Restlet Studio](https://studio.restlet.com) to design an API which I export as "Swagger 2.0 with Restlet Extensions", and I'm not sure whether this is their own vendor-specific property, but example request bodies I've given for POST resources is set in an `x-examples` field in the `parameters`:

      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/Mission"
        x-examples:
          application/json: "{\n  \"name\": \"Second test mission\",\n  \"platform_serial_ID\"\
            : 2\n}"

I gather that for every acceptable body mimetype (`application/json` being one of them) a single example can be given.

I thought of writing a Python hook to copy `transaction[...]['x-examples']['application/json']` to `transaction[...]['request']['body']`, but (correct me if I'm wrong) the transaction only stores the original schema for the **response** rather than the request parameters.

Would it therefore be possible to add `requestSchema` to the transaction object similarly to how `expected.bodySchema` is added?

**Comment by kylef** [comment]
Hi @erinaceous,

The key for an example is `x-example` and not `x-examples`. Although, in this case you have a schema so you can place `example` directly into your schema.

**Comment by honzajavorek** [comment]
@erinaceous Exactly as @kylef wrote. Does it solve your problem?

**Comment by honzajavorek** [comment]
@erinaceous If you have any issues with this, feel free to continue here and we can re-open this if needed.
