### ISSUE TITLE
Mysterious key appearing in body

### ISSUE THREAD

**Issue by johngluckmdsol** [apiaryio/dredd#887]
#### Describe your problem

I really want to use dredd.  Currently, I'm using 4.50 with a Ruby Application and OpenAPI 2.0 

I have a controller called MessagesController.  My routes.rb looks like this
``` 
scope 'v1' do
  resources :messages
  post '/messages
end
```
My open api looks like this
```
paths:
  /messages:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: "Blah"
      parameters: 
        - in: body
          description: "The information required to send a message"
          name: messages
          required: true
          schema:
            $ref: '#/definitions/messages'
  messages:
    type: object
    properties:
      messages:
        type: array
        description: "A list of messages, currently only one item is supported."
        items:
          $ref: '#/definitions/message'
        minItems: 1
        maxItems: 1
  message:
    type: object
    properties:
      stuff_goes_here:
```
I took out a bunch of stuff that was irrelevant

**THE PROBLEM:** When I run the command line, I see the following in my server log
```
Started POST "/v1/messages" for 127.0.0.1 at 2017-09-29 19:08:09 -0700
Processing by MessagesController#send_message as JSON
  Parameters: {"messages"=>[{"stuff_goes_here"}], "message"=>{"messages"=>[{"stuff_goes_here}]}]}
Completed 400 Bad Request in 0ms (Views: 0.1ms)
```

Note the body contains two properties, `messages`, which I expect, and `message`, _which I don't expect_ and is somehow **magically** added.  I am convinced that there is no possible way I am telling dredd to this so I think dredd, or one of its dependencies, is being "smart" and attempting to guess at what the structure of my body will be based on my controller. Is that what's happening? I guess this because when I change my controller and routes to point to FoosController, I see

```
New request from a remote host, data: {:remote_host=>nil, :remote_ip=>"127.0.0.1"}
Started POST "/v1/foos" for 127.0.0.1 at 2017-09-29 19:44:23 -0700
Processing by FoosController#send_message as JSON
  Parameters: {"foo"=>{}}
Completed 400 Bad Request in 1ms (Views: 0.2ms)
```

How can I make it stop being clever?  I attempted to use before hooks to modify the request but this didn't work, so if I can do it this way, please leave detailed instruction.  I have spent the better part of the day attempting to figure this out.
#### What command line options do you use?

```
$ dredd openapi.yml http://localhost:3000 --level=debug --language=ruby --hookfiles=./spec/dredd_hooks.rb
```

#### What is in your `dredd.yml`?
Not using

#### What's your `dredd --version` output?

```
dredd v4.5.0
```

#### Does `dredd --level=debug` uncover something?
not really

#### Can you send us failing test in a Pull Request?
It simply tells me the request isn't valid because my application validates against my JSON schema, which we've tried to sync as best as possible with the open api doc.  The body needs to only contain messages: [].

**Comment by johngluckmdsol** [comment]
Also, are you planning to support Open API 3.0 and, if so, when?

**Comment by honzajavorek** [comment]
Hi @johngluckmdsol! Thanks for using (or trying to use) Dredd, and for filing this issue. On the first sight I'd say this looks like a strange bug. There is no "smart" logic which should add properties. The problem needs investigation and we need to be able to reproduce the problem.

Regarding the Open API 3.0, at the moment a clear decision is still pending in Apiary. Of course anyone can come and contribute the support at any time, and we'll be there to help them - see https://github.com/apiaryio/dredd/issues/837#issuecomment-320020909 Opening a separate issue dedicated to Open API 3.0 support is the least you can do to bring attention to the matter at this moment (there's none existing yet, AFAIK).

**Comment by w-vi** [comment]
We definitely plan to support OpenAPI 3.0 the question is when and the answer is yet to be determined.

**Comment by johngluckmdsol** [comment]
Nevermind.  This isn't your bug
