### ISSUE TITLE
Test failing: CLI - Swagger Document When loaded from file When Swagger is loaded with warnings should print warning to stdout

### ISSUE THREAD

**Issue by matthewl-biomatters** [apiaryio/dredd#892]
When I run `npm test` on `master` it fails with:

```
CLI - Swagger Document When loaded from file When Swagger is loaded with warnings should print warning to stdout:
     AssertionError: expected 'info: Beginning Dredd testing...\npass: GET (200) /machines duration: 44ms\ncomplete: 1 passing, 0 failing, 0 errors, 0 skipped, 1 total\ncomplete: Tests took 51ms\n' to include 'warn: Parser warning'
```

And it's failing in my unrelated PR (#891).

**Comment by honzajavorek** [comment]
Thanks! The tests are indeed failing for a different reason than your PR. It's probably related to failing master in Dredd Transactions - https://github.com/apiaryio/dredd-transactions/pull/108#issuecomment-337252277 No fear 😎! Special Judicial Squad member @michalholasek is on his mission to figure it out.

**Comment by michalholasek** [comment]
Fixed by https://github.com/apiaryio/dredd/pull/900.
