### ISSUE TITLE
Ability to use custom reporters 💡

### ISSUE THREAD

**Issue by stipsan** [apiaryio/dredd#922]
# EDIT

Shucks, I hit enter while adding the title, didn't mean to post it just yet!

# EDIT (again)

I can see that while the built in reporters can be used multiple times even there does not seem to be a way to add external ones:

https://github.com/apiaryio/dredd/blob/54135db22e529a127e3b8208366a8bae4c669456/src/options.coffee#L52-L57

https://github.com/apiaryio/dredd/blob/54aa8a38273b6a4286abe5b706e85bf7da19aea8/src/configure-reporters.coffee#L36-L49

I'm wondering if you would consider allowing it, and if a PR for that would be welcome 😄 

One of the things I'd like to do in my custom reporter is to change up this:
https://github.com/apiaryio/dredd/blob/54aa8a38273b6a4286abe5b706e85bf7da19aea8/src/reporters/x-unit-reporter.coffee#L73-L81

We have mile long JSON Schemas and big payloads. The ability to change the output to the following is a **huge** improvement:
```coffeescript
prettyDiff = require 'jest-diff'

      diff = """
      Message:
      #{test.message}
      Diff:
      #{prettyDiff(test.expected, test.actual)}
      Request:
      #{prettifyResponse(test.request)}
      Expected:
      #{prettifyResponse(test.expected)}
      Actual:
      #{prettifyResponse(test.actual)}
```

This is not the only use case I have where the option to add my own reporter to dredd would be awesome:
* post GitHub PR comments on failures with a markdown formatted diff save a step with drilling down deep on CI logs.
* update a README.md with a list over skipped tests to encourage refactors so that skips are no longer needed.
* adapt junit/xunit output so it's more useful in a CircleCI context. Basically:
This is not very useful:
<img width="1010" alt="skjermbilde 2017-11-21 kl 20 03 30" src="https://user-images.githubusercontent.com/81981/33091547-b6328e1a-cef7-11e7-8087-13eb6d802825.png">

But this is extremely helpful (but require changes to the junit output that is more compatible with CircleCI):
  
<img width="1009" alt="skjermbilde 2017-11-21 kl 20 07 36" src="https://user-images.githubusercontent.com/81981/33091552-bac07366-cef7-11e7-815f-233cfade30c2.png">

btw I think it would be better if this weren't commented out:
https://github.com/apiaryio/dredd/blob/54aa8a38273b6a4286abe5b706e85bf7da19aea8/src/configure-reporters.coffee#L50-L52

IMO it's not user friendly to silently ignore any setting :)

**Comment by honzajavorek** [comment]
@stipsan These are awesome ideas! In https://github.com/apiaryio/dredd/issues/765, we thought about supporting [TAP](https://testanything.org/) ([see also this](https://github.com/sindresorhus/awesome-tap)). That would allow people to easily extend Dredd with any reporter they like, and it would allow us to completely remove some of the built in reporters.

Do you think that would solve your issues? Is TAP protocol powerful enough to support everything you would need to implement the reporters you mentioned?

**Comment by stipsan** [comment]
Yes absolutely TAP would be powerful enough! 😄 Great news!

I will close this issue and subscribe to #765 👍

**Comment by honzajavorek** [comment]
Great! Thanks, this validates the thoughts we had about TAP 🙂
