### ISSUE TITLE
Dredd installation problems on docker

### ISSUE THREAD

**Issue by naumanbasheer** [apiaryio/dredd#923]
I am having problems with installing dredd globally on my docker container where it is giving me some kind of permission error. 

It fails when it is trying to make one of the underlying libraries.  Here is the commands that I ran 

```
FROM buildpack-deps:trusty
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update && apt-get install -y nodejs
RUN chown -R keyflow /usr/lib/node_modules
RUN npm install -g dredd
```

It starts failing when installing dredd

```
Step 11/11 : RUN npm install -g dredd
 ---> Running in 89b997b4c06b
/usr/bin/dredd -> /usr/lib/node_modules/dredd/bin/dredd

> protagonist@1.6.8 install /usr/lib/node_modules/dredd/node_modules/protagonist
> node-gyp rebuild

gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.9.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/dredd/node_modules/protagonist/.node-gyp"
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/lib/node_modules/dredd/node_modules/protagonist/.node-gyp/8.9.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/dredd/node_modules/protagonist/.node-gyp"
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/lib/node_modules/dredd/node_modules/protagonist/.node-gyp/8.9.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/dredd/node_modules/protagonist/.node-gyp"

```

**Comment by honzajavorek** [comment]
It looks like there are some issues with compiling the native API Blueprint parser Dredd includes. See [this](https://dredd.readthedocs.io/en/latest/installation.html#why-i-m-seeing-node-gyp-or-python-errors). When the compilation fails, npm should skip it and Dredd should use the JavaScript version of the parser. I'm not sure why npm didn't skip the compilation in your case - maybe the errors were so fatal they brought down npm as well. Would you mind using `npm install -g dredd --no-optional` instead to completely avoid the compilation?

**Comment by honzajavorek** [comment]
@naumanbasheer Any updates on this?

**Comment by honzajavorek** [comment]
@kratz74 Did `npm install -g dredd --no-optional` work for you?

**Comment by joost** [comment]
For me `--no-optional` did work in a `node:latest` docker image. Thanks.

**Comment by honzajavorek** [comment]
An official and up-to-date Docker image is now available at [apiaryio/dredd-docker](https://github.com/apiaryio/dredd-docker). Please check it out and let me know if it works for you. Thanks!
