### ISSUE TITLE
prepublish vs prepare vs prepublishOnly

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#945]
As of npm@5, `prepublish` scripts are deprecated. Use `prepare` for build steps and `prepublishOnly` for upload-only. See the deprecation note in `npm help scripts` for more information.

**Comment by honzajavorek** [comment]
@michalholasek relying on #705 to address this, sooner or later 😏

**Comment by michalholasek** [comment]
@honzajavorek
![Yep](http://replygif.net/i/797.gif)
