### ISSUE TITLE
Setting transaction fail in before hook still runs the test

### ISSUE THREAD

**Issue by mlambley** [apiaryio/dredd#948]
I have a hook which looks like:

```
use Dredd\Hooks;

Hooks::beforeEachValidation(function(&$transaction) {
    if ($somethingBad) {
        $transaction->fail = 'Bad thing happened';
    }
});
```

I would expect the transaction to not run at all. Instead, it runs the request on my server, displays the expected and actual, but then afterwards displays:

```
[31mfail[39m: Failed in after hook: Bad thing happened
```

I can change it to:

```
error_log('Something bad happened');
$transaction->skip = true;
```

Which is an acceptable workaround, but could there instead be a way to either:
- Make the transaction not run when it is already marked as failed, or 
- Make transaction->skip an optional string rather than just a boolean, so a "skip reason" can be displayed, or
- Something I haven't considered?

Please let me know if there is further information which you need.

```
//Command
node dredd.js

//Version
3.5.1

//dredd.js
const insecure = require('insecure');
var Dredd = require('dredd');
var configuration = {
    server: 'https://my.internal.url',
    options: {
        'path': ['resolved.json'],
        'dry-run': false,
        'names': false,
        'level': 'info',
        'silent': false,
        'only': [],
        'header': [],
        'user': null,
        'hookfiles': ['./hooks/commonFunc.php','./hooks/commonHooks.php', './hooks/*Hooks.php'],
        'language': './vendor/bin/dredd-hooks-php',
        'reporter': ['html'],
        'output': ['./report.html'],
        'inline-errors': true,
        'color': true,
        'timestamp': false,
        'hooks-worker-timeout': 50000,
        'hooks-worker-connect-timeout': 1500,
        'hooks-worker-connect-retry': 500,
        'hooks-worker-after-connect-wait': 100,
        'hooks-worker-term-timeout': 5000,
        'hooks-worker-term-retry': 500
    }
};
var dredd = new Dredd(configuration);
insecure();
dredd.run(function (error, stats) {
    // your callback code here
});
```

**Comment by honzajavorek** [comment]
@mlambley Please check out the [execution life cycle](https://dredd.readthedocs.io/en/latest/how-it-works.html#execution-life-cycle) in the docs. If you want to prevent the HTTP request from happening, you should be using "before(Each)" instead of "before(Each)Validation".
