### ISSUE TITLE
x-example: 0 in parameters doesn't work

### ISSUE THREAD

**Issue by yyamano** [apiaryio/dredd#949]
#### Describe your problem

I get "Required URI parameter 'id' has no example or default value." error with the following swagger file.  "x-example: 1" works fine, but " x-example: 0" doesn't. 

This might be the same issue as #677

```
paths:
  /users/{id}:
    get:
      parameters:
        - name: id
          in: path
          type: integer
          format: int32
          required: true
          x-example: 0
      responses:
        200:
```

```
error: Compilation error in file 'bug/api.yml': Required URI parameter 'id' has no example or default value. ( > /v1/users/{id} > GET)
warn: Compilation warning in file 'bug/api.yml': Ambiguous URI parameter in template: /v1/users/{id}
No example value for required parameter in API description document: id ( > /v1/users/{id} > GET)
error: Error when processing API description.
```

#### What command line options do you use?

```
$ dredd api.yml http://127.0.0.1:3000 --hookfiles=hooks.js
```

#### What is in your `dredd.yml`?

```yaml
---
swagger: "2.0"
info:
  version: "1.0"
  title: Example API
host: www.example.com
basePath: /v1
schemes:
  - http
produces:
  - application/json; charset=utf-8
paths:
  /users/{id}:
    get:
      parameters:
        - name: id
          in: path
          type: integer
          format: int32
          required: true
          x-example: 0
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
```

#### What's your `dredd --version` output?

```
dredd v4.9.2 (Darwin 15.6.0; x64)
```

#### Does `dredd --level=debug` uncover something?

No.

#### Can you send us failing test in a Pull Request?

No.

**Comment by honzajavorek** [comment]
Thanks for reporting this!

**Comment by kylef** [comment]
The property `example` is used to describe a parameter example value in OAS 2. "x-example" is purely an unknown extension to the parser. If you switch out the line for example this should work as expected.

```yaml
      parameters:
        - name: id
          in: path
          type: integer
          format: int32
          required: true
          example: 0
```

**Comment by honzajavorek** [comment]
@kylef 

> The property `example` is used to describe a parameter example value in OAS 2.

Since when? I don't believe that's true. There is a reason [we have `x-example`](https://help.apiary.io/api_101/swagger-extensions/#x-example).

**Comment by kylef** [comment]
@honzajavorek My opologies, you are correct. I am getting Parameter Object and Schema Object confused. The behaviour of example is the opposite.

I've just tried to verify this bug and I believe it has already been fixed, either in Dredd or our OAS 2 parser and when I run the latest version of Dredd with the document I am not seeing the error and the path contains the example value so I think we can leave this issue closed.

```
$ dredd foo.yaml  http://127.0.0.1:3000
info: Beginning Dredd testing...
error: GET (200) /v1/users/0 duration: 9ms
error: Error connecting to server under test!
info: Displaying failed tests...
fail: GET (200) /v1/users/0 duration: 9ms
fail: Error connecting to server under test!
request:
method: GET
uri: /v1/users/0
...

complete: 0 passing, 0 failing, 1 errors, 0 skipped, 1 total
complete: Tests took 15m
```

**Comment by honzajavorek** [comment]
OK, let's leave this closed. It's one year old 😞 If the issue was (also) in interpreting 0 as false, I'm aware of that and I have other issues to track that.

**Comment by rodoabad** [comment]
@honzajavorek can you reference the issue here? Thanks!

**Comment by honzajavorek** [comment]
I'd say it's mainly https://github.com/apiaryio/dredd/issues/677 and https://github.com/apiaryio/dredd-transactions/issues/70
