### ISSUE TITLE
Possibility to skip Swagger validation

### ISSUE THREAD

**Issue by znevrly** [apiaryio/dredd#956]
Before executing tests Swagger validation is performed. If contains errors tests won't run. Please add CLI option to skip validation.

**Comment by honzajavorek** [comment]
@znevrly Why would you want to do that? I can't see benefit in testing erroneous API description file. Also, some errors prevent Dredd to be able to run the tests at all. Would you try to better explain what exactly you want to achieve?

**Comment by znevrly** [comment]
Hi,
Well we have additional properties such "emoji" in specification. When trying to run tests, validation fails
 e.g.
"attribute definitions.ProfileSummary.emoji is unexpected",
"attribute definitions.MediaFile.emoji is unexpected",
"attribute definitions.Plan.emoji is unexpected",
"attribute definitions.PageEntry.emoji is unexpected"

Complete skip is maybe bad idea but I just want allow certain properties in the validator? Any idea how to achieve it to run the tests?

thx.

**Comment by honzajavorek** [comment]
Ha! Now that sounds way more reasonable. In that case, I'd probably propose Dredd to allow additional properties and at worst to just report them in warnings as unsupported/ignored. This would need to be implemented in the [Swagger adapter](https://github.com/apiaryio/fury-adapter-swagger) though. @kylef, what do you think about this?

**Comment by MikeRalphson** [comment]
@znevrly is there any reason you cannot use a compatible specification (vendor) extension and call your property `x-emoji` instead?

**Comment by znevrly** [comment]
Well...it's possible. Thanks.

**Comment by honzajavorek** [comment]
IMHO this is resolved then.
