### ISSUE TITLE
How to use blueprint for resource creates when id is provisioned by server?

### ISSUE THREAD

**Issue by gobengo** [apiaryio/dredd#96]
Hey, I have the following in my blueprint.

I'm trying to 'create a new app'. When I do this, the server provisions and id and includes it in the response body JSON. It also includes a location header in the response which is a relative URL to the newly created app resource. This location header should be considered opaque, but happens to be using the newly provisioned id.

```
### Create New App [POST]

Create a new app

Requires authorization to create apps. App creator is the subject of the access
token.

+ Request

    + Headers

            Content-Type: application/json

    + Body

            {
                "name": "example-map",
                "version": "0.0.0"
            }

+ Request

    + Headers

            Content-Type: application/json

    + Body

            {
                "version": "0.0.0"
                "elements": [{
                    "component": {
                        "name": "streamhub-wall"
                    }
                }]
            }

+ Response 201

    + Headers

            location: /apps/5408ddd782f3910000000004

    + Body

            {
                "id": "5408ddbb82f3910000000002",
                "url": "/apps/5408ddbb82f3910000000002"
            }
```

Whenever I run dredd against this, it fails because the location header in practice is some id other than what's in the blueprint.

Is there any way to author my blueprint to ensure that the location header is present in the response, but not fail the thing just because it's a new unique id?

```
fail: headers: Value of the ‘location’ must be /apps/5408ddd782f3910000000004.

request: 
body: 
{
  "name": "example-map",
  "version": "0.0.0"
}
headers: 
    Content-Type: application/json
    User-Agent: Dredd/0.3.9 (Darwin 13.3.0; x64)
    Content-Length: 54

uri: /apps/
method: POST


expected: 
headers: 
    location: /apps/5408ddd782f3910000000004

body: 
{
    "id": "5408ddbb82f3910000000002",
    "url": "/apps/5408ddbb82f3910000000002"
}

statusCode: 201


actual: 
statusCode: 201
headers: 
    access-control-allow-origin: *
    location: /apps/5408e0ec82f3910000000012
    content-type: application/json; charset=utf-8
    content-length: 81
    date: Thu, 04 Sep 2014 22:00:12 GMT
    connection: keep-alive

body: 
{
  "id": "5408e0ec82f3910000000012",
  "url": "/apps/5408e0ec82f3910000000012"
}
```

**Comment by netmilk** [comment]
Reopening after discussion in #108

**Comment by stephanheinze** [comment]
:+1:

**Comment by netmilk** [comment]
Hi, 

we recently changed the way how we validate headers in Gavel, please refer to: https://github.com/apiaryio/gavel.js/pull/53. Only values of content-negotiation significant headers are treated as constants. This functionality is in Dredd > 0.4.8. 

For example value of the `Location` header can be different in real response then given in the blueprint. 

This should fix this issue when you rely on data provisioned by server and you have no way how to retrieve it and modify expectation in before hooks. 

Adam
