### ISSUE TITLE
Blueprint should be accessed directly from apiary

### ISSUE THREAD

**Issue by Georgian** [apiaryio/dredd#966]
#### Describe your problem

Couldn't find this issue anywhere else.

It would be really nice to edit the blueprint in apiary, then simply run dredd. Right now I have to copy the entire blueprint from apiary, replace all '\r' occurences with '\n' (I know, right?), then save the blueprint into the 'apiary.apib' file. 

My yml is configured to push test results to apiary. Are they not providing an easy way to access the raw blueprint?

#### What is in your `dredd.yml`?

reporter: apiary
custom:
  apiaryApiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  apiaryApiName: gs
dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: grails run-app
server-wait: 100
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: apiary.apib
endpoint: 'http://localhost:8090/gs/api'

#### What's your `dredd --version` output?

dredd v5.0.0 (Windows_NT 10.0.16299; x64)

**Comment by ido567** [comment]
Did you try to specify the URL of the API blueprint (in Apiary) in the `blueprint` key of your configuration?

**Comment by honzajavorek** [comment]
Hi, thanks for the issue! I'm sorry for not being responsive, it had to slip through my radar. This would indeed make the experience more smooth, so 👍 However, I think this is almost the same story as in https://github.com/apiaryio/dredd/issues/366, so I'm going to close this issue as a duplicate. Also note this workaround - https://github.com/apiaryio/dredd/issues/366#issuecomment-258211867
