### ISSUE TITLE
Is it possible to add extra transactions?

### ISSUE THREAD

**Issue by iamdanthedev** [apiaryio/dredd#976]
Say I want to have more tests on a sensitive route, is it possible to programmatically add more transactions concerning the route? I am using js interface to dredd if that matters

Thanks!

**Comment by honzajavorek** [comment]
I think you could use the `beforeAll` hook for that. It takes a list of transactions and it's up to you how you modify the list before the Dredd testing starts. Would that work for you?

**Comment by honzajavorek** [comment]
Closing in favor of https://github.com/apiaryio/dredd/issues/995

**Comment by iamdanthedev** [comment]
Hello!
Thanks for quick response, I apologise that it took me a little bit longer 
Thanks again :)
