### ISSUE TITLE
Add option for failing on empty array

### ISSUE THREAD

**Issue by fgblomqvist** [apiaryio/dredd#996]
A lot of my endpoints are supposed to return an array of items. Of course, this array could be empty in a real-case-scenario if the filters don't match anything or there simply aren't any items. This results in Dredd saying that all those endpoints passed because the result matches the JSON Schema (e.g. an empty array is always valid).

However, I find that this is not very useful for testing. After all, imo most of the time you want to make sure that the formatting/output of the individual items is correct. One could argue that all you gotta do is add a hook that adds at least one item to your storage. Though, I think it could be easy to forget about this when adding new endpoints.

E.g. you add a new endpoint, forget to add a hook, push it, the CI says everything is good since dredd was fine with the empty array that was returned during the test, and then you end up with an endpoint that might not match the docs.

Therefore, I propose adding an option that forces dredd to fail when an array is empty. I'm not sure what the best approach would be, since sometimes maybe you're fine with empty arrays if they're not the "root" array. Maybe such an option would only cause dredd to fail if the response is just an array and it is empty, or if the response is an object and one of it's keys goes to an array and that array is empty. Or maybe this is out of the scope of dredd?

**Comment by michalholasek** [comment]
If I understand your use case correctly, you can use `afterAll` hook to achieve that "global" level assertion whether your response payload contains empty array(s) (or not).

**Comment by fgblomqvist** [comment]
You are certainly correct. Though, I would use the afterEach hook since this is something I would want to check for each test separately. Thanks for the advice!

**Comment by honzajavorek** [comment]
Implementing a global flag for this wouldn't be straightforward, as this is something specific to each format and your usage of the format. In both API Blueprint and Swagger you can write your own JSON Schema - see [docs](https://dredd.readthedocs.io/en/latest/how-to-guides.html#making-dredd-validation-stricter). Dredd just takes whatever JSON Schema it gets and validates against it.
