### ISSUE TITLE
Use host option defined in OpenAPI standard

### ISSUE THREAD

**Issue by BastianHofmann** [apiaryio/dredd#997]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema

The OpenAPI standard specifies a host value (and scheme values). Those could be used to derive the host used by dredd (instead of providing the second CLI argument).

I'm open to providing a pull request.

**Comment by michalholasek** [comment]
Hello @BastianHofmann, I am sorry for getting back to you so late.

> I'm open to providing a pull request.

That would be wonderful, please do! 🙂

**Comment by honzajavorek** [comment]
This could be problematic as often you test different APIs (production, staging, development) with the same document. The host is "environment", which can change easily. Surely Dredd could pick up the default value from the API description document - the [API Elements](http://apielements.org/) provide the value. However, is it really so useful? If people just run Dredd without specifying host and it defaults to testing production, isn't it possibly harmful / leading to mistakes? (Consider Dredd testing of POST/DELETE/etc. or with hooks, which could affect the API state.)

**Comment by honzajavorek** [comment]
I don't think we want to do this for the reasons I wrote in my previous comment. I'm open to a discussion though and happy to re-open this issue in the future.
